### ISSUE TITLE
PhpStorm + Ubuntu 18.04 not working

### ISSUE THREAD

**Issue by Aleksandar-Mitic** [beyondcode/tinkerwell-community#105]
I expirience issues on Linux Ubuntu using PhpStorm. PhpStorm does not recognize Tinkerwell app.  
I have installed latest version 2.2.1 of Tinkerwell and latest version of PhpStorm. 2019.3

[screenshot](https://paste.pics/82ccfb657da22d7aa8422dcb4cbca82b)

**Comment by chqshaitan** [comment]
Yes, i am having the same issue, fortunately the app runs fine on its own

**Comment by killgt** [comment]
Same issue here. Decompiled the phpstorm plugin, seems to load the path from the json:

`return (String)jsonObject.get((Object)"tinkerwellPath") + File.separator + "tinkerwell" + File.separator + "tinker.phar";`

Looking into ~/.config/Tinkerwell/settings.json seems to be correct (tinkerwellPath) (a temp path that changes on every run). Maybe it's no finding the json settings file...

`            appHome = appDirs.getUserDataDir("Tinkerwell", (String)null, (String)null, true);
`

We'll probably need an update on the phpstorm plugin side.

Maybe we should get a 'real' installation besides the appimage

**Comment by sschlein** [comment]
Hi folks,

we'll look into this issue early next week, please follow this thread for updates :)

**Comment by sschlein** [comment]
Maybe we didn't but it's still on the list as a high priority 🙈

**Comment by herpaderpaldent** [comment]
Got same issue this is very unfortunate

**Comment by mauricehofman** [comment]
Any updates on this? I've got the same problem.

**Comment by sgarwood** [comment]
It would be nice to have an update on this.

**Comment by johshej** [comment]
Same issue for me.

**Comment by tylerssn** [comment]
Same issue for me. I made the purchase strictly for PHPStorm convenience.

Looking forward to using Tinkerwell. Is there any workaround for now? Perhaps renaming the Tinkerwell appimage or moving it to a location that PHPStorm expects to see it?

**Comment by njames** [comment]
Bump... this is still an issue. The plugins in Ubuntu 18.04 just don't seem to work with PHP Storm 2020.1.2 or in Sublime. 
Can we please have a config option to  specify where Tinkerwell is installed?

**Comment by herpaderpaldent** [comment]
Bump

**Comment by amcsi** [comment]
+1
paid for the license, and right off the bat I can't use it on PhpStorm on Linux, because it thinks the Tinkerwell app is not installed when in fact it is.

**Comment by sschlein** [comment]
I have released docs for the plugins here https://beyondco.de/docs/tinkerwell/basic-usage/ide-plugins

Unfortunately, we are likely not able to provide plugins for Linux and Windows in the same way that the plugins work for macOS. You can find more information about this in the docs.

**Comment by sgarwood** [comment]
Very annoying, especially considering the PHPStorm IDE support was marketed and listed as a selling point when purchasing this product. 

I do not recall seeing, nor do I believe there were any disclaimers stating that the IDE Plugin was only supported on Mac OSX.

**Comment by sschlein** [comment]
@sgarwood If this was a major selling point for you and you don't want to use the standalone app, please send me an email with your order id or license key to support@beyondco.de and I can give you a refund.

**Comment by mikeerickson** [comment]
Talk about pulling the ripcord!  This response is littered throughout the repo for a number of issues.  When you decide to charge for a product, you assume the responsibility of supporting the features your label as features. Not to mention supporting those customers which have paid you for the product. 

I think a better statement here would be your failed ability to live up to what you have sold and offer refunds to anybody who requests one, no questions asked.

**Comment by sschlein** [comment]
We generally offer refunds if you are not satisfied with our products. Feel free to email anytime and I'll send you a refund and disable the license.

**Comment by herpaderpaldent** [comment]
How about a partial refund, as you have made promise about the products functionality that you could not deliver. 
Likewise the involved manufacturer of the Diesel-Skandal.

**Comment by daom89** [comment]
Also not working on Windows 10 x64 with php 2020.1 😐

**Comment by sschlein** [comment]
In case you missed it and are still subscribed to this issue:

We have released a new dedicated Tinkerwell PHPStorm plugin that does not connect to the Tinkerwell app and does work on macOS, Linux and Windows!

Merry Christmas!

**Comment by Aleksandar-Mitic** [comment]
Awesome! I already installed and it work's great on Ubuntu 20.04 and PhpStorm 20.3. Thanks for **not** letting this stays unresolved for Linux users.
