### ISSUE TITLE
Sort SSH connections alphabetically

### ISSUE THREAD

**Issue by joelhinz** [beyondcode/tinkerwell-community#107]
I have about 40 servers in Forge and it's a tiny but annoying problem to find them in the list each time I need to connect to something. Auto-sorting them would be great, or by clicking the "Label" field above. :)

(Ubuntu 19.10, Tinkerwell 2.2.1)

**Comment by sschlein** [comment]
I'm closing this issue because there is another feature request that also includes this :)

**Comment by joelhinz** [comment]
Not a problem @sschlein, but I'd appreciate if you'd also mention or link that issue so I can keep track of it. Thanks. :)
