### ISSUE TITLE
Includes and requires don't work as expected/intended

### ISSUE THREAD

**Issue by mlanth** [beyondcode/tinkerwell-community#114]
When including/requiring a file (which may include helper functions, classes, etc) the contents are not available to be used outside of the file execution.

Reproduction steps:
1. Include/Require PHP file with function
2. Try and use the function

![image](https://user-images.githubusercontent.com/7073891/75260243-4cf55680-57b7-11ea-9949-85432965fcb6.png)
![image](https://user-images.githubusercontent.com/7073891/75260810-27b51800-57b8-11ea-87f4-9cf2da260dc4.png)

**Comment by mpociot** [comment]
That's the default behavior of Psy shell, which Tinkerwell uses under the hood. 
You could try using a custom Tinkerwell driver to require the file before Tinkerwell evaluates the code. 

https://github.com/tinkerwellapp/drivers
