### ISSUE TITLE
Cmd + Z closes the tab.

### ISSUE THREAD

**Issue by mathieutu** [beyondcode/tinkerwell-community#127]
Hi, when several tabs are open, pressing Cmd + Z in a tab closes it, and all the code in it is lost.

It's not the case when only one tab is open.

PS: I'm on an `AZERTY` keyboard. Maybe is my cmd+z interpreted in tinkerwell like a cmd+w for any reason?

Thanks.

**Comment by mouuuton** [comment]
Same issue here. AZERTY keyboard as well.

**Comment by sschlein** [comment]
I labeled this as a feature request for AZERTY keyboards and not a bug because there must be something going on behind the scenes of electron apps. Not sure we can solve it.

**Comment by mpociot** [comment]
This is already fixed
