### ISSUE TITLE
Allow "<?php" at the beginning of files

### ISSUE THREAD

**Issue by curtisblackwell** [beyondcode/tinkerwell-community#128]
I like to use the VS Code extension, which requires `<?php` at the start of the file to properly syntax-highlight.

When I start a file with `<?php`, I get this error from Tinkerwell:

```
Parse error: Syntax error, unexpected '<' on line 1
```

**Comment by devyk** [comment]
Or might be simpler to just strip them out during insertion both manually and using ide plugins.

**Comment by desaintflorent** [comment]
Would love to have a working solution for his too 👍

**Comment by dmyers** [comment]
Also if you save the file from Tinkerwell while in `HTTP` mode, it will prepend `<?php` to the file too. This drove me crazy when I later reopened the file again an it wouldn't work.

**Comment by sschlein** [comment]
This was released with 2.8.0 last week :)
