### ISSUE TITLE
Keep ssh connections seperate from tabs

### ISSUE THREAD

**Issue by Treggats** [beyondcode/tinkerwell-community#132]
I've noticed when I have two ssh tabs open that the first stops working when the second is connected via ssh.

Tinkerwell version 2.3.1 (OSX)

Steps to reproduce:

- connect to a site/server in default tab
- run code specific to that site/server
- create new tab and connect to a different site/server
- run code specific to this site/server
- try running code from step 2 (this fails)

**Comment by sschlein** [comment]
Solved with 2.8.x
