### ISSUE TITLE
Php warning color readability problem

### ISSUE THREAD

**Issue by joseaneto** [beyondcode/tinkerwell-community#134]
I am using Tinkerwell 2.4.0 and the Github theme, I'm having readability problems caused by the color of the "PHP warnings" (fatal errors use red and is ok), yellow, as you can see in the screenshot, is really difficult to read.

Same happens with other light theme like Solarized Light.

![](https://i.imgur.com/OMmwH0N.png)

**Comment by peterthomson** [comment]
Hoping we can over-ride this using a custom theme. But I can't figure out how to do that either.

**Comment by pf1gura** [comment]
Since custom themes are not coming soon per #185, are there plans to address this issue? All predefined light themes have this problem.

**Comment by shawnlindstrom** [comment]
A high contrast dark theme would be a good addition. I'm colorblind and have cone dystrophy. So, light themes are out and I can't read red on a dark background. I use Darcula now and it's fine except for the error messages. Even a toggle to make them white or a yellow or something with ore contrast would be incredibly helpful and appreciated.
