### ISSUE TITLE
Table view not working with non-numeric primary keys

### ISSUE THREAD

**Issue by dakira** [beyondcode/tinkerwell-community#135]
When setting the Eloquent primary key to something other than id, the respective column just shows zeroes. Here's an example using Caleb Porzios Sushi:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Sushi\Sushi;

class Language extends Model
{
    use Sushi;

    protected $primaryKey = 'code';

    public function getRows()
    {
        $path = base_path('vendor/commerceguys/intl/resources/language/'
            . config('app.locale') . '.json');

        if (! file_exists($path)) {
            $path = base_path('vendor/commerceguys/intl/resources/language/en.json');
        }

        return $languages = collect(json_decode(file_get_contents($path), true))
            ->map(function ($languageName, $code) {
                return ['code' => $code, 'name' => $languageName];
            })->values()->toArray();
    }
}

```

Without a custom primaryKey I get this:
<img width="768" alt="id as primary" src="https://user-images.githubusercontent.com/576555/76130851-8b3b1300-600c-11ea-99ee-36c8c3f692b0.png">

With a custom primaryKey I get this:
<img width="769" alt="code as primary" src="https://user-images.githubusercontent.com/576555/76130876-9e4de300-600c-11ea-895d-08a4f7adcf19.png">

**Comment by mpociot** [comment]
I was unable to reproduce this issue (but I also remember modifying some parts of the table view) - so I guess this issue has been resolved 

![image](https://user-images.githubusercontent.com/804684/92397383-09e14c00-f127-11ea-870f-3cb8401b89c1.png)
