### ISSUE TITLE
Wrong characters when using open in tinkerwell PHPstrom

### ISSUE THREAD

**Issue by yhortuk** [beyondcode/tinkerwell-community#136]
Prefix **\Reg** in fully specified namespace causes encoding errors. I suppose it's being parsed as some keyword during transition between phpstrom and tinkerwell. Is there any way we can fix it?
I'm having utf-8 encoding and example below properly copied manually between the apps.

Original:

```
\Registration\Models\User::query()->hasRole("reseller");
```

Produces:
```
\Registration\User\Models\User::query()-\ԛ�J��\�[\��N
```

**Comment by arthur1472** [comment]
It would be nice if this got some more attention and a fix. Pretty frustrating having to copy and paste my code from my IDE to Tinkerwell every time just to get auto completion.

**Comment by mpociot** [comment]
This can be closed, as the new Tinkerwell plugin no longer allows you to open the desktop app
