### ISSUE TITLE
Not work well with old laravel version and wrong on detect laravel version

### ISSUE THREAD

**Issue by hoangnh228** [beyondcode/tinkerwell-community#139]
Laravel version is 5.1, uses PHP 5.6 and run in Homestead
Please see the screenshot
https://gyazo.com/4efec7b5d6d19cb0eee46dce11bdb2ab
The model result did not show all attributes value, just show some model info
On right click, it always shows Laravel version is 7.0, not detect correct version of my project

**Comment by mpociot** [comment]
The model attributes are not all shown because of the way the model gets serialized (that also is the case in "php artisan tinker"). You can try returning all attributes using `->toArray()`

The context menu information is not correct and needs to be fixed in an upcoming version.
