### ISSUE TITLE
SSH ProxyJump Option

### ISSUE THREAD

**Issue by luisdalmolin** [beyondcode/tinkerwell-community#14]
I have some servers that I need to connect using another server as a proxy in the middle. For that, I need to use the `ProxyJump` SSH option.

This would make the SSH connection string look like this:

```bash
ssh -o ProxyJump=user@proxy-server.com user@final-server.com
```

**Comment by SaundersB** [comment]
I'd also like to use this feature as well. I have a custom config in my ~/.ssh/config something like this:

`Host development
    HostName <ip_address>
    User <username>
    ForwardAgent yes
    KeepAlive yes
`

**Comment by luisdalmolin** [comment]
Yeah, maybe it doesn't need to be the ProxyJump option in the UI, but seems like Tinkerwell doesn't use things configured in `~/.ssh/config` when using SSH.

https://twitter.com/luisdalmolin/status/1230455909077463040

**Comment by SaundersB** [comment]
Agreed. I can't use Tinkerwell on my staging servers due to compliance reasons I have a bastion host. As for my local environment in a docker container I haven't had the time to get the SSH connection working. I'd love to see Tinkerwell support the local `~/.ssh/config`.

**Comment by tomschlick** [comment]
Another vote for using the config in `~/.ssh/config`. Can't access prod boxes without it 😢

**Comment by luisdalmolin** [comment]
@mpociot Any chances we can get this? It would make my life so much easier :)

**Comment by rhys-steele** [comment]
Another vote for this feature! Much needed.

**Comment by edd-smith** [comment]
Another vote. Unable to use on prod servers accessed via Bastion server at present.

**Comment by rickhurst** [comment]
Another vote for being able to use the proxy settings in `~/.ssh/config` to connect via ssh!

**Comment by arjanwestdorp** [comment]
A workaround that I've found is setting up port forwarding. Execute the following in your terminal and keep it running:
```
ssh -L 2225:127.0.0.1:22  user@final-server.com -i ~/.ssh/id_rsa -o "ProxyCommand ssh -q -W %h:%p user@proxy-server.com" -N
```
Now you can configure tinkerwell with these settings:
![image](https://user-images.githubusercontent.com/7716654/110321751-6c51d100-8012-11eb-9ef9-a18525399806.png)

**Comment by sschlein** [comment]
I'm closing this issue as we don't plan to add that anytime soon. That doesn't mean that this will never be part of Tinkerwell but it won't be in the near future.

**Comment by gander** [comment]
The thread was for both ProxyJump and SSH Config after @mpociot combined these topics. Several people voted for **_SSH Config_**. And suddenly @sschlein closes it, stating the reason he explained in another thread as:

> We don't have an official roadmap and decide this on the go. Mostly based on the things that we like to have for us 😅
> We [...] carefully decide how important a feature is and how much business value it has
_Originally posted by @sschlein in #508_

I understand that we need to clean up before the end of the year, but silencing ALL voices that need RATIONAL features is not the right way to go.

**Comment by ahoiroman** [comment]
Too bad :-/ I am using very restrictive ssh settings and laravel forge-created ssh-users are never allowed to connect directly.

**Comment by MrKoopie** [comment]
Another vote here.
