### ISSUE TITLE
New Driver: orchestral/testbench (or just for custom packages in general)

### ISSUE THREAD

**Issue by spaceemotion** [beyondcode/tinkerwell-community#143]
I'm currently working on a custom package and would love to do a couple tests with it by running a Tinkerwell session. Right now I either have to

- write the lines in a unit test, or
- have it installed in a real laravel app

The package is using https://github.com/orchestral/testbench under the hood.

Not sure if there needs to be a driver for this one exactly (since people might just write packages without it), or if the driver should bootstrap a new laravel app, and use  the Service Provider as specified in the composer.json (under the extras, for autodiscovery).

**Comment by sschlein** [comment]
we are actually playing around with this instead of a driver:

https://twitter.com/marcelpociot/status/1225556964035432451

**Comment by spaceemotion** [comment]
Well for that kind of thing i actually got spatie‘s phpunit-watcher. I am only using phpunit as a way to run any kind of code to test some scenarios, but they’re not meant to be „resl“ tests. (just for tinkering)

**Comment by xitox97** [comment]
Does the tinkerwell already support for testing or not?

**Comment by mpociot** [comment]
This is a cool idea, if you want to send a PR to the driver repo, I'd happily merge it :)
https://github.com/tinkerwellapp/drivers
