### ISSUE TITLE
VScode (windows 10) Command "tinkerwell.openInTinkerwell" not found

### ISSUE THREAD

**Issue by NoxxieNl** [beyondcode/tinkerwell-community#145]
Hiya,

Referencing issue #74 I still have this issue.
Even after a clean re-install of the plugin in VScode I still get the message that all three commands are not found...

Running Windows 10 x64, tinkerwell 2.5.0

As of this moment (writing this), the VScode plugin is on version 2.2.0 and the last release date was 02-02-2020.

**Comment by xitox97** [comment]
I also have this issue

**Comment by stancl** [comment]
Same on Ubuntu 19.10

**Comment by nyl2k8** [comment]
![awh](https://user-images.githubusercontent.com/5878890/78024777-dc5ece00-7350-11ea-8de5-97130d4936f9.PNG)

OS: Windows 10 x64
VSCode: 1.43.2
TinkerWell: 2.0.0

**Comment by shahidkarimi** [comment]
Any update on this bug?

**Comment by devcircus** [comment]
I haven't seen an answer from anyone on the tinkerwell team regarding this since the repo was opened. It's been mentioned many times. 🤷🏽‍♂️

**Comment by larsverp** [comment]
Why is this issue still a thing 2 months later? Without this feature Tinkerwell is not very useful for me.

**Comment by stancl** [comment]
And now I'm on macOS, where "Open with Tinkerwell" works, but, uh, "works"?

<img width="855" alt="Screenshot 2020-05-20 at 16 27 44" src="https://user-images.githubusercontent.com/33033094/82458396-e8485000-9ab6-11ea-86e6-0220393a34f0.png">

**Comment by devcircus** [comment]
@mpociot can anyone shed any light on this? Looks like a lot of devs have paid for this but never got it working in vscode, including myself. Several issues have been added here. I have a license, have Tinkerwell installed, have the extension installed, but always get ```tinkerwell.run```, ```tinkerwell.openInTinkerwell```, etc. not found. Any help would be appreciated.

**Comment by sschlein** [comment]
Hey @devcircus - we are aware of the issue but have very limited resources as we are just a two-person company and Tinkerwell doesn't pay all our bills. We are working on other things that improve your overall user experience with all Beyond Code tools at the moment and look into contracting someone to support us on these issues. This is why I can't give you a date when this will be fixed.

If this is a critical feature for you and you don't need Tinkerwell without it, please send us an email with your order number at support@beyondco.de and I can give you a refund.

**Comment by NoxxieNl** [comment]
@sschlein could we do something to speed up some things? Or help out in anyway?

**Comment by sschlein** [comment]
@NoxxieNl Thank you a lot for this, but I don't think you can at the moment. We are going to finish some major things in the next 2-3 weeks and focus on getting the other stuff done after that :)

**Comment by devcircus** [comment]
@sschlein 
Completely understand and thanks for the response. It's not mission-critical, just nice to have. Really just wanted to see a response to know you were aware. Just noticed several issues on the same topic, each with several "same here" replies, so I knew it wasn't just me having the problem.

**Comment by sschlein** [comment]
I have released docs for the plugins here https://beyondco.de/docs/tinkerwell/basic-usage/ide-plugins

Unfortunately, we are likely not able to provide plugins for Linux and Windows in the same way that the plugins work for macOS. You can find more information about this in the docs.
