### ISSUE TITLE
Multiple PHP binaries

### ISSUE THREAD

**Issue by GTCrais** [beyondcode/tinkerwell-community#146]
I use WAMP for local development, and I have multiple PHP binaries, so when I installed Tinkerwell, for some reason by default it listed 2 PHP binaries in Settings -> Preferences -> Advanced, and basically the software just halted.

I manually selected only 1 PHP binary, and now it works, so this is just a heads up for something to check out.

**Comment by mpociot** [comment]
This is currently not on our road map as I feel that this is quite an edge case. But we might come back to this at some point in the future

**Comment by grafmouse** [comment]
+1 for this feature! It would be great to define all wanted binaries and select it per tab to use with selected version.
