### ISSUE TITLE
Tinkerwell not recognising WordPress?

### ISSUE THREAD

**Issue by logicelf** [beyondcode/tinkerwell-community#150]
Hi folks,

Hoping someone can point me in the right direction or point out if I'm making a stupid mistake.

It doesn't seem to matter what working directory I run functions from - PHP is throwing fatal errors when I run any WordPress-specific functions. I can run PHP functions fine - but anything WordPress-specific returns an undefined function message ("PHP Fatal Error: "Call to undefined function [whatever_function()] in Psy Shell code on line 1").

I've tried from the root of WP installs using both VVV and Local, and from various subdirectories in each. I've also tried saving and opening PHP files from various locations and running functions from there. Tinkerwell just doesn't seem to be detecting WordPress, or loading its driver for it (that's what I assume is happening, but that may be a faulty assumption).

I'm on macOS with the latest version of Tinkerwell (2.5.0) and it's using the default /usr/bin/php binary.

Am I missing something really, really obvious here? Any pointers would be gratefully received.

**Comment by mpociot** [comment]
What do you see in the context menu of tinkerwell? It should show you the Wordpress version it detected. If that is not the case, maybe the Wordpress driver does not work for you?

This is what it’s using to detect if it’s running in Wordpress :
https://github.com/tinkerwellapp/drivers/blob/master/src/Drivers/WordpressTinkerwellDriver.php#L10

**Comment by logicelf** [comment]
Thanks for the reply - I don't see that label. Additionally, if I change the working directory to (for instance, using VVV) ~/vagrant-local/www/wordpress-one/public_html (which definitely contains wp-load.php) then the output pane gives me the HTML of a WP error page - e.g. https://www.dropbox.com/s/vd6klhc6riqq247/Screenshot%202020-03-14%2013.53.07.png?dl=0

The site is functioning properly while this is happening.

Something odd is happening for me here, but I can't put my finger on it ...

**Comment by logicelf** [comment]
Hi,

Any further ideas on this one?

**Comment by KevinBatdorf** [comment]
@logicelf I was able to get it working by SSHing into Homestead

<img width="1423" alt="Screen Shot 2020-03-22 at 5 56 17 PM" src="https://user-images.githubusercontent.com/1478421/77247744-75f9f180-6c66-11ea-8c96-240b2ebc89dd.png">

**Comment by logicelf** [comment]
Hi @KevinBatdorf ,

Thanks for the suggestion, but that's not working for me - while I can SSH into the local VVV box with Terminal, iTerm, etc., Tinkerwell gives the following error when using the same credentials:

Failed to parse (unnamed) as a valid auto format key: bcrypt_pbkdf function returned failure, parameters invalid

I get this with basic auth, and while using my public key - which seems to suggest an issue with Tinkerwell's OpenSSH implementation.

@mpociot I'd really appreciate some input from you here.

**Comment by logicelf** [comment]
Update:

So - however odd it is that it can't use the same key that I can use in any CLI - I **can** get Tinkerwell to log in to the Vagrant box by using the keyfile at `~/.vagrant.d/insecure_private_key`. From there, I can configure the relevant `/srv/www/[whatever_site]/public_html` directory to look at inside the box - and Tinkerwell can, at last, see the WordPress installation and run WordPress commands.

However, this is clunky and requires having separate configs for each site in Tinkerwell, etc. - which is obviously a bit tedious. Could we please look at why this isn't working when opening the directories from the host machine?

**Comment by logicelf** [comment]
Another update:

I simply cannot get this working with Local. It's not recognising the WordPress installations in the Docker containers.

@mpociot Are you monitoring these issues? I have to say I'm disappointed not to have seen any input at all from you here - this _is_ a paid product, after all.

**Comment by sschlein** [comment]
We are monitoring the issues here but mostly handle things that affect a broader user group – simply because we can't afford digging into every single issue that is related to a unique development setup. If you can't use the app for the intended use case, you can always send an email at support@beyondco.de and we can process a refund for you.

**Comment by logicelf** [comment]
VVV and Local are probably the two most used local environments for WordPress development. Tinkerwell specifically states support for WordPress. With respect - in what way would any of this be a 'unique development setup'?

**Comment by sschlein** [comment]
I don't know what VVV is and how you define local as you are mentioning Docker (no easy setup with Docker at the moment). Normal local setups work without any issues. Googling "tinkerwell Wordpress" shows multiple videos and tutorials on how people use it. This is one example: https://rosswintle.uk/2020/01/tinkerwell-for-wordpress-developers/

**Comment by logicelf** [comment]
> I don't know what VVV is
https://varyingvagrantvagrants.org/ - used by plugin, theme and core developers

>  how you define local as you are mentioning Docker
Local (https://localwp.com/) uses Docker

> Normal local setups work without any issues
What is a 'normal' local setup? We're developers - please be specific.

> Googling "tinkerwell Wordpress" shows multiple videos and tutorials on how people use it
That is literally the only one I can see (with a couple of articles pointing to it). Please give one or more examples from the 'multiple' you see?

Thanks.

**Comment by andrefredette** [comment]
@logicelf I've been able to get Tinkerwell to work with Local by setting the database host in wp-config.php to "localhost:[path to mysql socket]" where [path to mysql socket] is the path indicated in the database tab of the site in Local. Doing that made the WordPress "can't connect to the database" errors go away and Tinkerwell could then properly operate using it's WordPress driver. Hope that helps.

**Comment by logicelf** [comment]
@andrefredette Thank you so much - that does indeed work perfectly. I would never have thought to try that, as the error ("Call to undefined function") didn't seem to be related to a database connection issue (at least as far as it presented itself to me).

Very grateful for your help. :)

**Comment by tareq1988** [comment]
I'm using **Laravel Valet** and I can confirm I'm having the exact issue. 

Opening the WordPress site folder gives me this output:
![image](https://user-images.githubusercontent.com/153669/80898675-b99d4c00-8d38-11ea-931e-eb3aeb4ee087.png)

According to the solution of @andrefredette:

```
define( 'DB_HOST', 'localhost:/tmp/mysql.sock' );
```

If I put this to `wp-config.php`, the error goes away and it can connect successfully. But it should work without a hack like this.

**Comment by mpociot** [comment]
I think this is limited to the way that phar execution in PHP works 🤔

**Comment by jreviews** [comment]
Thanks for sharing this. Using MAMP on Mac, this also worked for me:

`
define('DB_HOST', 'localhost:/Applications/MAMP/tmp/mysql/mysql.sock');
`

**Comment by mpociot** [comment]
Maybe we can solve this by modifying the WordPress Tinkerwell driver,

**Comment by chetansatasiya** [comment]
@mpociot I am using a https://varyingvagrantvagrants.org/ for WordPress Development and Tinkerwell showing a always connection issue. https://prnt.sc/vr7yfc

Can you help me to figure out and it work for me?
