### ISSUE TITLE
Doesn't remember last Laravel site

### ISSUE THREAD

**Issue by edalzell** [beyondcode/tinkerwell-community#153]
I thought Tinkerwell remembered the last laravel site opened but it's not doing that.

Any chance this will be coming in an upcoming release?

**Comment by wrabit** [comment]
+1, I have to reopen the same project before things start working again.

**Comment by mpociot** [comment]
Yeah, I'm working on this. It's on our list :)

**Comment by sschlein** [comment]
That's actually possible since 2.7 or 2.8 =)
