### ISSUE TITLE
TinkerWell v2.5.0 SSH and PHP Fatal error:  Call to undefined function dd()

### ISSUE THREAD

**Issue by tsonevpetyo** [beyondcode/tinkerwell-community#157]
Hello, i have issue with tinkerwell for 2 days now... In the past 60 days i was using it without any problems but... Here is the situation I am connecting to ssh to Forge server and laravel project v6.12. Everything works normally except the dd() and dump(). Btw we did not change something in the project which might cause such issue. So i tried to test this straight via php artisan in the working dir - everything works as expected. Also i uninstalled tinkerwell together with it's app data - same... In the context menu it shows that Laravel 7 was detected but actually as i said above we are using 6.12. I tried to change the version from preferences to 6 and set another php binary, but no joy... 

OS: Catalina 10.15.3 (19D76)
Remote Laravel Version: 6.12

**Comment by n8udd** [comment]
I am also now having the same issue. I can't use DD in Tinkerwell, and get the error "PHP Fatal error:  Call to undefined function dd() in Psy Shell code on line..."

**Comment by sampittman** [comment]
Here as well!
![image](https://user-images.githubusercontent.com/47398926/80783389-d9652200-8b36-11ea-8596-3e915558c57d.png)

**Comment by keithbrink** [comment]
I was experiencing this issue, and then from an unrelated issue I found the tip to try changing the PHP binary in Tinkerwell's advanced preferences to `/usr/local/bin/php` (mine was set to `/usr/bin/php`). That seems to have resolved this issue as well.

**Comment by mpociot** [comment]
Yeah this might be due to the PHP version.
Besides that - there's no real need for dd in Tinkerwell, right? :D 
Just use `dump`

**Comment by tsonevpetyo** [comment]
@mpociot dump does not work for me... Also my php bin is pointing to ```/usr/local/bin/php```

![image](https://user-images.githubusercontent.com/62121640/81391596-09f41f80-9126-11ea-8e00-f441e0303a85.png)

**Comment by n8udd** [comment]
I don't think it's a PHP version as sometimes it works and others it doesn't. Usually a restart of Tinkerwell fixes it.

I regularly use DD rather than dump as I don't want the code below to execute.

A also turned off live code execution.

**Comment by brocard** [comment]
i need dd return to tinkerwell

**Comment by nikolov-tmw** [comment]
I'm running into this same issue and the most I could find out is that Composer thinks that the `/$vendorDir/symfony/var-dumper/Resources/functions/dump.php` file has already been included. Poking around `autoload_real.php`, I can see that the file is in the `$includeFiles` array and has a key of `667aeda72477189d0494fecd327c3641`.

However doing `empty($GLOBALS['__composer_autoload_files']['667aeda72477189d0494fecd327c3641'])`(before looping through `$includeFiles`) gives me `false`. 

`echo implode("\n", get_included_files())` shows that `phar:///tmp/.mount_tinkerWWTgQp/resources/tinkerwell/tinker.phar/vendor/symfony/var-dumper/Resources/functions/dump.php` is already included.

`file_get_contents( 'phar:///tmp/.mount_tinkerWWTgQp/resources/tinkerwell/tinker.phar/vendor/symfony/var-dumper/Resources/functions/dump.php' )` shows that the `dump()` function in it is namespaced under `namespace _PhpScoperc223a629f245;`.

So it seems like the Tinkerwell autoloader perhaps has the same md5(?) hash for `/symfony/var-dumper/Resources/functions/dump.php` as my project's autoloader. Which would make sense if Composer generates the hash solely based on the path within the vendor directory and doesn't take into account file size or anything else.

A hacky workaround that seems to do the trick for me in my custom TinkerwellDriver is to add this in my `bootstrap` method before including the file I need:

```
$GLOBALS['__composer_autoload_files'] = [];
```

This makes Composer unaware of any files it loaded from Tinkerwell's autoloader(which if all of them are uniquely namespaced anyway shouldn't present any issues, right 🤔 ) and allows my own files to be loaded. And I can now use `dump()` again :smile: 

@mpociot is this "workaround" something that could be added to Tinkerwell itself? If you're namespacing all of your vendor dependencies, it doesn't make sense to pollute Composer's `$GLOBALS['__composer_autoload_files']`.

**Comment by filipac** [comment]
@mpociot constantly get into dd or dump not defined bug.

**Comment by gopalkriagg** [comment]
@mpociot Please fix this issue. I am getting this error in some Laravel projects.
```
PHP Fatal error:  Call to undefined function dump() in Psy Shell code on line 1
```
For my current work, I rely heavily on dump (as I am doing some kind of analysis on data). I really look forward to use Tinkerwell because I can fold the nested arrays.

**Comment by mpociot** [comment]
I can't seem to reproduce this error. Does this happen on every Laravel Version for you? Only remote, or also locally?

Would be good if you could give me some steps to reproduce this. I can use dd and dump in my Laravel projects 🤔

**Comment by domainoverflow** [comment]
@mpociot I have experienced it in both remote and local.

**Comment by techguydev** [comment]
I am also having this same errro
