### ISSUE TITLE
v2.6.0 don't show anythings (blank screen)

### ISSUE THREAD

**Issue by vcazacu** [beyondcode/tinkerwell-community#160]
After update to 2.6.0 Tinkerwell CLI (table) do not show the results on SSH connection. I don't change anything from 2.5.0!
OS: Linux Mint v19 and OS X Catalina 10.14

![Screenshot from 2020-03-19 18-57-32](https://user-images.githubusercontent.com/369354/77093450-a3029600-6a13-11ea-95dc-f754ca55b195.png)

**Comment by henriksjodahl** [comment]
Don't know if you solved this, but under "view" in your navigation bar you may "Toggle Output" to show / hide the output window

**Comment by azeranex** [comment]
> Don't know if you solved this, but under "view" in your navigation bar you may "Toggle Output" to show / hide the output window

It's already has output window but there is nothing show at all.

**Comment by vcazacu** [comment]
I haven't solved it yet. When I reinstalled v2.5 the application works properly.

**Comment by vcazacu** [comment]
I work in laravel in the cloud. In local mode everything is ok. The ssh connection is ok.

**Comment by vcazacu** [comment]
We did not find any log files to verify why it is not working.

**Comment by themightychris** [comment]
I'm seeing the same, but v2.6.0 is my first version. Where do you find any log files to see what might be going on?

**Comment by sschlein** [comment]
> I work in laravel in the cloud. In local mode everything is ok. The ssh connection is ok.

What do you mean with "laravel in the cloud"

**Comment by vcazacu** [comment]
My laravel app is on external server (Kamatera). I use VSCode to edit app through ssh.

**Comment by vcazacu** [comment]
Is there someone in the same conditions and Tinkerwell works fine?

**Comment by azeranex** [comment]
I ssh to docker container and it also doesn't work. I can run php in ssh fine.

**Comment by vcazacu** [comment]
I want to reinstall v2.5, but I don't know where to download it...

**Comment by sschlein** [comment]
https://tinkerwell.app/download/electron/Tinkerwell-2.5.0.dmg :)

**Comment by vcazacu** [comment]
Thanks!
Tinkerwell v2.5 works very well for me. Sadly, if I close the app it will make update to v2.6 and don't works anything. Must be uninstall and reinstall v2.5.
I hope that v2.6 will be fix it!

**Comment by vcazacu** [comment]
Can I block automatically update?

**Comment by Jason4869** [comment]
I have this same issue on windows 10 while SSHing into an Alpine linux container.  I'm not getting anything returned when running against SSH connection in version 2.6.  I had to downgrade to version 2.5, which corrected the issue.  Unfortunately, I need to keep deleting the auto downloaded update that is pending in `AppData\Local\tinkerwell-updater`.  On a side note, it would be nice for auto update to be an optional setting.

Hopefully the devs are looking into this.  The title of this issue isn't very clear and it hasn't yet been marked as a bug.  If there are any logs or anything more I can provide the dev team to get this addressed, please let me know.

**Comment by Rwarlock** [comment]
> I have this same issue on windows 10 while SSHing into an Alpine linux container. I'm not getting anything returned when running against SSH connection in version 2.6. I had to downgrade to version 2.5, which corrected the issue. Unfortunately, I need to keep deleting the auto downloaded update that is pending in `AppData\Local\tinkerwell-updater`. On a side note, it would be nice for auto update to be an optional setting.
> 
> Hopefully the devs are looking into this. The title of this issue isn't very clear and it hasn't yet been marked as a bug. If there are any logs or anything more I can provide the dev team to get this addressed, please let me know.

Hey Jason, I am having the same issue. 
From where have you downloaded version 2.5. I don't have 2.5 version. 
I bought the app yesterday.

**Comment by mpociot** [comment]
This should be fixed in the next release
2.6.0 makes use of some posix methods that might not be available
