### ISSUE TITLE
Working Directory Redis issues

### ISSUE THREAD

**Issue by mikemand** [beyondcode/tinkerwell-community#161]
I'm loving Tinkerwell so far. However, I am unable to use it in my own working directories, which kind of limits what I do with it.

If I use the folder icon on the sidebar to set my working directory to any of my projects, it seems to work at first. When I try to run any code, however, I receive this error in Tinkerwell:

```
   Error 

  Class 'Redis' not found

  at vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:74
    70|      * @throws \LogicException
    71|      */
    72|     protected function createClient(array $config)
    73|     {
  > 74|         return tap(new Redis, function ($client) use ($config) {
    75|             if ($client instanceof RedisFacade) {
    76|                 throw new LogicException(
    77|                         extension_loaded('redis')
    78|                                 ? 'Please remove or rename the Redis facade alias in your "app" configuration file in order to avoid collision with the PHP Redis extension.'

  • A class import is missing: You have a missing class import. Try importing this class: `Illuminate\Support\Facades\Redis`. 

      [2m+20 vendor frames [22m
  21  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Laravel\Telescope\TelescopeServiceProvider))

      [2m+4 vendor frames [22m
  26  phar:///Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar/src/Drivers/LaravelTinkerwellDriver.php:24
      Illuminate\Foundation\Console\Kernel::bootstrap()
```

It doesn't make any sense, because I can use Valet to run my project just fine. I do have PhpRedis installed and configured:

```
➜ cat /usr/local/etc/php/7.4/conf.d/ext-redis.ini
───────┬─────────────────────────────────────────────────────────────────────────
       │ File: /usr/local/etc/php/7.4/conf.d/ext-redis.ini
───────┼─────────────────────────────────────────────────────────────────────────
   1   │ [redis]
   2   │ extension="redis.so"
───────┴─────────────────────────────────────────────────────────────────────────

```

I have removed the Facade alias (I also tried it with the alias set to `RedisManager` instead of just `Redis`) and I know the connection is working because, again, my project works when I run it in the browser and I can see data in Redis.

Let me know what other information might help resolve this. I am not entirely sure what I need to provide.

**Comment by mpociot** [comment]
Hi!

Please make sure that you have selected the correct PHP binary in Tinkerwell!
The issue could be that Tinkerwell is using the default OSX version of PHP, while it should use the version from Homebrew located at /usr/local/bin/php

**Comment by mikemand** [comment]
Hi Marcel,

Oh boy, is my face red. 😳 I completely overlooked that setting. Thank you!

As a suggestion, could you make that either a text field or a dropdown in a later version?

**Comment by squatto** [comment]
I think that one way to help people avoid this problem would be to show the output of `php -v` beneath the path, similar to the way that PhpStorm does:

![image](https://user-images.githubusercontent.com/748444/81135718-8fa18080-8f16-11ea-99e4-3ae84f4c244a.png)

Settings > Languages & Frameworks > PHP, click `...` next to the `CLI Interpreter` dropdown.

**Comment by mpociot** [comment]
We'll show the PHP version on the settings page in the next version
