### ISSUE TITLE
No desktop Integration in Linux version

### ISSUE THREAD

**Issue by JunaidQadirB** [beyondcode/tinkerwell-community#162]
Looks like Tinkerwell doesn't support desktop integration, which means I cannot launch it from my desktop apps screen or pin it to my dock and always have to go to the Appimage and click it or run it from the terminal.
As described in the [Desktop integration](https://docs.appimage.org/reference/desktop-integration.html) section of AppImage documentation, it must be configured.
Thanks,

**Comment by gsmeira** [comment]
Hi, I'm using Ubuntu here and I create a desktop entry like this: 

1) Create a folder `/opt/Tinkerwell` and move the AppImage inside. (you can put the AppImage wherever you feel better, I like the `/opt/` folder).

2) Download the Tinkerwell icon image: https://tinkerwell.app/images/icon.png

3) Move the image to the folder `/opt/Tinkerwell`

4) Create a file `tinkerwell.desktop` (like this one below) and save inside the folder `/usr/share/applications/`

```
[Desktop Entry]
Version=2.6.0
Name=Tinkerwell
Comment=The magical code editor that runs your code.
Exec=/opt/Tinkerwell/Tinkerwell-2.6.0.AppImage
Path=/opt/Tinkerwell
Icon=/opt/Tinkerwell/icon.png
Terminal=false
Type=Application
Categories=Development;
```

That's it!

EXTRA: For executing Tinkerwell anywhere from the terminal, you can do this: `ln -s /opt/Tinkerwell/Tinkerwell-2.6.0.AppImage /usr/bin/tinkerwell`. If you created this symlink you can simplify your desktop entry exec value for `Exec=tinkerwell`

**Comment by mpociot** [comment]
As this is not easily integrated into the current build process I'm using for electron, this will need some time

**Comment by stilliard** [comment]
Another work around atm is to use AppImageLauncher: https://github.com/TheAssassin/AppImageLauncher
