### ISSUE TITLE
Can't load multi pane share code

### ISSUE THREAD

**Issue by KevinBatdorf** [beyondcode/tinkerwell-community#165]
When I try to load this share, it only shows the right pane:

https://tinkerwell.app/shares/KevinBatdorf/56b9c348-60cf-4f99-a147-aacfabe41249

<img width="1423" alt="Screen Shot 2020-03-22 at 5 59 24 PM" src="https://user-images.githubusercontent.com/1478421/77247783-e274f080-6c66-11ea-8c7c-6bba8388cae5.png">

It would also be nice if I could choose to not include a screenshot in the share. I wanted to share the code with teammates but needed to make the text white to hide the output.

**Comment by mpociot** [comment]
You can also create secret shares - maybe that helps with the white text at least. I'll look into the issue with loading multi-pane shares
