### ISSUE TITLE
Command line open tinker with project folder support

### ISSUE THREAD

**Issue by godkinmo** [beyondcode/tinkerwell-community#166]
Is anything like that can quickly open tinkerwell with specific folder
`open -a /Applications/Tinkerwell.app --projectPath=$(pwd)`

I want to setup a `zshconfig` like this

```
function tinkerwell() {
     if [ -d 'Application/Tinkerwell.app' ]; then
        # open ...
     fi
}
```

**Comment by stilliard** [comment]
This would be a fantastic improvement :+1: much faster than going back to recently opened each time

**Comment by godkinmo** [comment]
I think is something like this in Electron app
https://discuss.atom.io/t/how-to-get-startup-arguments-from-electron-app/35353

**Comment by fylzero** [comment]
+1 This needs to be a thing.  I've been Google'ing and trying to see if I can get to open a working directory from command line for a while now.

**Comment by skydiver** [comment]
if anyone is interested, here is my current solution:

```bash
#!/bin/bash

if [[ $# -eq 0 ]] ; then
    PATH=$(pwd)
elif [ $1 = "." ]; then
    PATH=$(pwd)
else
    HEAD=$(dirname "$1")
    HEAD=$(cd "$HEAD" && pwd)
    PATH="$HEAD/$(basename $1)"
fi

PATH=$(echo $PATH | /usr/bin/base64)

/usr/bin/open "tinkerwell://?cwd=$PATH"
```

```bash
# opens current folder
$ tinker

# opens current folder
$ tinker .

# opens "laravel-demo" in current directory
$ tinker laravel-demo

# opens absolute path
$ tinker /Users/martin/code/larave-demo
```

**Comment by godkinmo** [comment]
> if anyone is interested, here is my current solution:
> 
> ```shell
> #!/bin/bash
> 
> if [[ $# -eq 0 ]] ; then
>     PATH=$(pwd)
> elif [ $1 = "." ]; then
>     PATH=$(pwd)
> else
>     HEAD=$(dirname "$1")
>     HEAD=$(cd "$HEAD" && pwd)
>     PATH="$HEAD/$(basename $1)"
> fi
> 
> PATH=$(echo $PATH | /usr/bin/base64)
> 
> /usr/bin/open "tinkerwell://?cwd=$PATH"
> ```
> 
> ```shell
> # opens current folder
> $ tinker
> 
> # opens current folder
> $ tinker .
> 
> # opens "laravel-demo" in current directory
> $ tinker laravel-demo
> 
> # opens absolute path
> $ tinker /Users/martin/code/larave-demo
> ```

Just update my zsh functions
```bash
function tinkerwell {
  if [ $# -eq 0 ] || [ $1 = "." ]; then
    TW_PATH=$(pwd)
  else
    TW_PATH=$1
  fi

  TW_PATH=$(echo -n $TW_PATH | base64)

  open "tinkerwell://?cwd=$TW_PATH"
}
```

**Comment by sschlein** [comment]
@godkinmo I'd like to put this into a blog post on the Tinkerwell website. Do you have a Twitter handle (or a blog, something else) that I can link to to give your credit for this?

**Comment by godkinmo** [comment]
@sschlein 
hey, my twitter account is @hokkingfong

**Comment by sschlein** [comment]
https://tinkerwell.app/tutorials/8-open-tinkerwell-from-your-command-line-with-zsh
