### ISSUE TITLE
Processing indicator and sidebar button feedback.

### ISSUE THREAD

**Issue by m50** [beyondcode/tinkerwell-community#170]
So, I've been using tinkerwell to run benchmarks of something, and I have no notice that it's actually doing ANYTHING when I run them. These are multi-minute long runs, and I just have to sit there and wait.

Some sort of processing indicator would be nice.

Additionally, if you click on the buttons on the sidebar, there is no feedback that they've been pressed, so some sort of background color change or something would be useful to tell that I actually click it.

Sometimes I think that I missed the button, and click it a couple more times, just to be sure, since there is no feedback that tinkerwell is doing anything.

**Comment by mpociot** [comment]
The current indicator is the mouse cursor that changes (the gif recording somehow messed up the activity cursor):
![indicator](https://user-images.githubusercontent.com/804684/81164092-1181c000-8f90-11ea-8acf-8572183a206b.gif)
