### ISSUE TITLE
VS code extension: Tinkerwell not installed

### ISSUE THREAD

**Issue by ajthinking** [beyondcode/tinkerwell-community#172]
I have Tinkerwell :dizzy: desktop app installed and working 

Installed the VS code plugin version 2.0.0 and relaunched
![image](https://user-images.githubusercontent.com/3457668/77755398-7eb74280-702d-11ea-8d59-60ce97f902ba.png)

If I focus on a file
![image](https://user-images.githubusercontent.com/3457668/77755459-9db5d480-702d-11ea-93b3-f0eeec7d1a8c.png)

and then execute `Run with Tinkerwell` gives
![image](https://user-images.githubusercontent.com/3457668/77755352-66472800-702d-11ea-814b-990f3dbe6999.png)

How can I resolve this issue?
Mac OS catalina 10.15.1

**Comment by tylerssn** [comment]
Same in PHPStorm. I assume there are guides somewhere stating how to make the AppImage available globally, I just have not found them :man_shrugging:

**Comment by sschlein** [comment]
I have released docs for the plugins here https://beyondco.de/docs/tinkerwell/basic-usage/ide-plugins – it also includes links to the GitHub issues that we are going to use to fix the macOS bugs.

Unfortunately, we are likely not able to provide plugins for Linux and Windows in the same way that the plugins work for macOS. You can find more information about this in the docs.

**Comment by ajthinking** [comment]
I the exact same issue - not only OPEN but also RUN. There are no links to to the RUN issue in the beyondcode docs, or am I missing something?
