### ISSUE TITLE
How does class Aliasing works on Tinkerwell app?

### ISSUE THREAD

**Issue by aglipanci** [beyondcode/tinkerwell-community#174]
I have the same project, locally, on vagrant and on a remote SSH server. The class aliasing will work for me only on the remote server, both local options (local directory and inside a vagrant vm) it won't work.
Error: `Class 'User' not found in Psy Shell code on line 1`

I have models on a Models directory inside the app.

I just want to understand how I can make this work everywhere the same because considering there is no autocompletion writing complex statements using the full namespace it's impossible, making the app useless.

**Comment by mpociot** [comment]
I'm using Laravels class alias autoloader: https://github.com/laravel/tinker/blob/master/src/ClassAliasAutoloader.php

**Comment by mangrovestudios** [comment]
@aglipanci did you resolve your issue?

**Comment by aglipanci** [comment]
@mangrovestudios no I didn't.
