### ISSUE TITLE
Eloquent calls with orderBy dont appear sorted in Table View

### ISSUE THREAD

**Issue by mikeerickson** [beyondcode/tinkerwell-community#176]
The following

```
$users = App\Models\Vendor::all('contact_fname as first name','contact_lname as last name','contact_email as email')->sortBy('contact_lname');
```

will correctly display results in table, however, the `sortBy` command is not used when displaying data.  I must perform a secondary click on the column header to sort data.

![image](https://user-images.githubusercontent.com/183153/78196805-62a20f80-7438-11ea-9f04-5f938a3f9709.png)

**Comment by mpociot** [comment]
Good catch. This will be fixed in the next version
