### ISSUE TITLE
Cannot use traits in Custom driver class

### ISSUE THREAD

**Issue by antonkomarev** [beyondcode/tinkerwell-community#178]
I've created a trait file `.tinkerwell/TestTrait.php`:
```php
<?php

trait TestTrait
{
}
```

And trying to use it in my `.tinkerwell/CustomTinkerwellDriver.php`:

```php
<?php

class CustomTinkerwellDriver extends LaravelTinkerwellDriver
{
    use TestTrait;
}
```

It crashes and default context menu is not loading.

Is there is a way to use traits?

Even better to use namespaced traits. For example add to PSR-4 loader `.tinkerwell` directory as `DotTinkerwell\\` namespace.

**Comment by mpociot** [comment]
That's currently not possible as those additional files are not being required/autoloaded - I don't see the use for that right now. Maybe we will add this to the driver loader sometime later
