### ISSUE TITLE
Allow the split between the Query Inspection pane and Output pane to be freely adjusted

### ISSUE THREAD

**Issue by axit-joost** [beyondcode/tinkerwell-community#18]
Adjust the split, or divider, or bar between the two panes. Can't think of the correct term, so for reference, I am talking about this one:

![image](https://user-images.githubusercontent.com/13835397/69245153-99246f80-0ba6-11ea-8d20-481ed6ad5fff.png)

**Comment by sschlein** [comment]
Closing because of duplication
