### ISSUE TITLE
Install failure with 2.6.0

### ISSUE THREAD

**Issue by ksorbo** [beyondcode/tinkerwell-community#180]
Previously had 2.3 installed.

Autoupdated failed so I downloaded 2.6.0.

Run the install. 

It runs through the install dialog on Windows 10

Stops with popup:

`This file does not have an app associated with it for performing this action, Please install an app or, if, one is already installed, create an association in the Default Apps Settings Page.`

 I have tried direct install and running the installer.exe in the tinkerwell-updater folder. Same message.

**Comment by mpociot** [comment]
Are you still experiencing this issue? You are the first one that reports installation errors on Windows
