### ISSUE TITLE
Namespace incorrectly applied

### ISSUE THREAD

**Issue by dmarkussen** [beyondcode/tinkerwell-community#184]
I opened a new Laravel model and the output is giving me an error.  Appears to be applying the namespace to the model class despite Tinkerwell aliasing it.  This is a fresh install on Windows 10.

![image](https://user-images.githubusercontent.com/12942331/78623076-71c7f980-784c-11ea-8f58-d0f704c17cc3.png)

**Comment by mpociot** [comment]
This is currently an issue with the way that the code gets evaluates. Please use the FQN on the model class instead, like this:

```php

namespace App;

class VipCode extends \Illuminate\Database\Eloquent\Model
{

}

```
