### ISSUE TITLE
add ⌘+⌃+F to allow fullscreen

### ISSUE THREAD

**Issue by reed-jones** [beyondcode/tinkerwell-community#188]
For all my other apps, <kbd>⌘</kbd><kbd>⌃</kbd><kbd>F</kbd> sets the app to fullscreen in its own desktop. For some reason this doesn't seem to work with tinkerwell, and I can't figure out how to set it to actual fullscreen either...

**Comment by mpociot** [comment]
![image](https://user-images.githubusercontent.com/804684/81162118-f3ff2700-8f8c-11ea-82e1-ca4b0c2cdf9d.png)
The shortcut for fullscreen mode is in the "view" menu

**Comment by reed-jones** [comment]
Thanks 😄 If there was a way to rebind these in the settings somehow that would be amazing 👍 I already have that shortcut configured for something else
