### ISSUE TITLE
Tab Completion Support

### ISSUE THREAD

**Issue by bkintanar** [beyondcode/tinkerwell-community#193]
Tinker supports tab completion. It would be great if Tinkerwell supports it as well.

![image](https://user-images.githubusercontent.com/685928/79957387-15074880-84b4-11ea-9fbc-b98ae911e342.png)

**Comment by mpociot** [comment]
I'm going to close this one for now. I might look at integrating the Monaco editor in the future, when this issue gets resolved: https://github.com/microsoft/monaco-editor/issues/1658
