### ISSUE TITLE
Bug: Action shortcuts not working with Vim keymap

### ISSUE THREAD

**Issue by nickknissen** [beyondcode/tinkerwell-community#194]
When `Use VIM keymap` is enabled its not possible to use Ctrl + R, Ctrl + O, Ctrl + P shortcuts.
This is most likely because VIM keymap overrides the action shortcuts because it works when `Use VIM keymap` is disabled.

OS: Windows 10
Version: 2.6.0

**Comment by mpociot** [comment]
Yeah, I don't think there's much I can do right now, because the codemirror keymaps get prioritized over the native shortcuts.
