### ISSUE TITLE
Feature Request: Saved Favorites

### ISSUE THREAD

**Issue by ericvanjohnson** [beyondcode/tinkerwell-community#196]
I find myself running several of the same commands in multiple projects over and over again. Today I created a poor man's favorites section in my tinker. I thought it might be a nice feature to be able to add favorite commands somewhere in the application that are accessible later. Kind of like how Tables and Sequel Pro do for SQL commands.  

_For the record, the basic solution I came up with today was to just start copying them to a Comment Block I keep in the window_ 
![](https://www.evernote.com/l/AAHDhGpYgapHUpgfOlU1pgvlAjMgGWLxcuEB/image.png)

**Comment by mpociot** [comment]
You can already use the current "Share" functionality for this and create a "secret share".
But we will definitely look into an easier way of saving favorites in the future.
