### ISSUE TITLE
Have anyone got this to work with Laravel Valet and WordPress?

### ISSUE THREAD

**Issue by lmartins** [beyondcode/tinkerwell-community#197]
I've bought Tinkerwell a few weeks back and for the life of me I can't get it work properly on my install. I've pointed it to the PHP binary that is given out by the shell, and when I have a echo statement it outputs it at first, but I put anything WordPress it blows up:

```
PHP Fatal error:  Call to undefined function get_categories() in Psy Shell code on line 5
```
After this, commenting the WordPress functions and adding a simple echo again gives back an empty results pane.

The app is pointing to the root folder of a valet site running WordPress.

Anyone seen this behaviour?

**Comment by mpociot** [comment]
This is the way that Tinkerwell detects if the selected project is a wordpress project:
https://github.com/tinkerwellapp/drivers/blob/master/src/Drivers/WordpressTinkerwellDriver.php#L10

Make sure that this evaluates to true. If your setup is different from the default wordpress driver, you might need to create your own driver.

**Comment by lmartins** [comment]
This does evaluate true. Funny thing is that sometimes it works, sometimes it doesn't. Can't figure out why, but can rely on this either.

PHP binary is also pointing to the correct location.
