### ISSUE TITLE
Duplicate Emails Submitted

### ISSUE THREAD

**Issue by roni-estein** [beyondcode/tinkerwell-community#200]
Hi I recently upgraded to 2.6.0

I rarely use tinker, I'm trying to get it more into my workflow. However I was extracting a facade from a common task I do, sending a fax from a laravel email.

`Fax::to('1231231233')->file('test-fax.pdf')->send();`

Long story omitted, but when running this in a phpunit test or regular tinker, there is no duplicate issue. However tinkerwell does have the issue still. I have tinkerwell set to only fire on command + R.

Please let me know if you need any files or containing code to run to reproduce this.

This is the code that's being hit in the end that runs twice.

```
php
 @dump($this->to); //I thought an array might be the issue, it wasn't.
        Mail::to($this->to)
            ->later($this->when, new FaxFromEmail(fax_path($this->file)));
```

**Comment by roni-estein** [comment]
Still weird, this issue persists. This is in a very only laravel 5.8 project thats been transitioned to laravel 6. I'm sure there are other issues, but time permitting, I'll rebuild this segment into a package and test it out on a fresh laravel 7 app that I can open source. I'll post it here and revisit this issue.

**Comment by sschlein** [comment]
This seems to be a very specific problem that we might not be able to solve. I recommend running your code manually with CMD+R for your scenario anyway.

**Comment by telkins** [comment]
Hi @sschlein I just came here after discovering that my Tinkerwell script seems to run twice.  I'm not sure if it's the same problem that @roni-estein is having.

My script was fairly simple, but I made it even simpler:
```php
\Log::debug('running');
```
I clear my log and then execute the script via CMD+R and I get the following:
```
[2020-11-23 10:58:18] local.DEBUG: running  
[2020-11-23 10:58:18] local.DEBUG: running  
```
I'm not sure how critical this is or whether or not I'm missing something, but I'm trying to use Tinkerwell to track down a problem and the fact that it seems to be running my code twice makes it messy and more difficult.

FYI...I'm running the following:
 - Tinkerwell version 2.10.2
 - Homestead v10.15.2
 - Laravel Framework 7.26.0
 - PHP 7.4.8
 - Tinkerwell connecting to Laravel project on homestead

Please let me know whether or not you have any questions/suggestions.  Thx.

**Comment by telkins** [comment]
A quick follow-up....

If I make a single change, for example:
```php
\Log::debug('runningg');
```
And allow Tinkerwell to execute the script automatically, then it only appears to run once:
```
[2020-11-23 10:58:18] local.DEBUG: running  
[2020-11-23 10:58:18] local.DEBUG: running  
[2020-11-23 11:10:19] local.DEBUG: runningg  
```

But if I then manually execute the script via CMD+R, then it runs twice:
```
[2020-11-23 10:58:18] local.DEBUG: running  
[2020-11-23 10:58:18] local.DEBUG: running  
[2020-11-23 11:10:19] local.DEBUG: runningg  
[2020-11-23 11:10:25] local.DEBUG: runningg  
[2020-11-23 11:10:25] local.DEBUG: runningg  
```

**Comment by aerni** [comment]
I'm running into the exact same issue that @telkins describes. CMD + R runs everything twice. Really weird.
