### ISSUE TITLE
Unable to use tinkerwell for SSH on a remote server only

### ISSUE THREAD

**Issue by Rwarlock** [beyondcode/tinkerwell-community#201]
I added an SSH connection to the remote server by properly entering all the details correctly. I also ensured the I was able to connect to the system with the same SSH using the terminal. Which eliminates the possibility of the wrong Private Key. 

I am using windows 10.

I tried the same with the local setup using Laragon and I was able to successfully run command for my WordPress website.  Which eliminates the possibility of the wrong PHP binary. 

Every time I try to run command I get a blank screen. 

I have tried both v2.6 and v2.5. It doesn't seem to work. 

Please help.

**Comment by vladski** [comment]
I am having same issue on Mac with v2.6.0 connected to remote server over SSH 

- in CLI mode the output is always blank
- however in HTTP mode it works fine

**Comment by mpociot** [comment]
Could you see if /tmp is writeable for the user that connects via SSH?

**Comment by vladski** [comment]
You mean SSH user? In my case I am connecting to AWS with ec2-user. What do you mean access to /tmp?

**Comment by Rwarlock** [comment]
I am using tinkerwell on windows and checked that I have the write access. Screenshot attached.
![image](https://user-images.githubusercontent.com/21139188/81285442-2720e380-907d-11ea-87af-aefbd3591b18.png)

I hope this is what you meant in your reply.
