### ISSUE TITLE
features missing

### ISSUE THREAD

**Issue by seifodev** [beyondcode/tinkerwell-community#204]
just installed tinkerwell on linux and figured out that some features are missing in action menu such as:
- See queries in selected code 
- Install composer package 

also I have a problem with phpstorm plugin that cannot recognize tinkerwell installation

**Comment by paul-gene** [comment]
Tinkerwell is a PHP shell.

Why do you want to install a Composer package via Tinkerwell? Just SSH into the server as normal if you must....

**Comment by seifodev** [comment]
> Tinkerwell is a PHP shell.
> 
> Why do you want to install a Composer package via Tinkerwell? Just SSH into the server as normal if you must....

I do not need it, I jsut saw someone revewing the application where these options were exist.
so the question is why are these options missing in mine

**Comment by sschlein** [comment]
The package install was a feature of version 1. We asked users and nobody used it so we got rid of it with version 2 =)

**Comment by seifodev** [comment]
> The package install was a feature of version 1. We asked users and nobody used it so we got rid of it with version 2 =)

OK what about the query inspection and IDE plugin problem ?

**Comment by mpociot** [comment]
The query inspection can be triggered by selecting code and run CTRL+Shift+P
We're still investigating issues with the IDE plugin under linux

**Comment by adriaanzon** [comment]
@mpociot How can I trigger query inspection under macOS? It used to work with Shift-Command-R but that doesn't seem to be the case anymore.

**Comment by gbachev** [comment]
Hi,

Just bought the Tinkerwell app (MAC OS) and can't trigger the query inspection - it was one of the reasons I bought it in the first place. My version is 2.8.1. Tried CMD+SHIFT+R and CTRL+Shift+P

If you have removed the feature from the app, please also update the docs as it's misleading: https://beyondco.de/docs/tinkerwell/advanced-usage/query-inspection

Best,
Georgi

**Comment by sschlein** [comment]
I just tested with 2.8.1 on my Mac and it works as intended. Did you select the code before you pressed the shortcut?
