### ISSUE TITLE
Feature Request: Alternate "Row" Layout (vs current "Column")

### ISSUE THREAD

**Issue by alexfierro** [beyondcode/tinkerwell-community#205]
Hey guys, love the product. Sorry if this already exists, but I checked the features/options and can't find it if it does.

Basically, I was hoping for the option to stack the 2 panes (input/output) on top of each other vs. how they are now (side-by-side). So instead of columns, we'd have the option to make them rows. This would be really handy because many of the Eloquent method chains I need to tinker with get long and having the extra width would be handy. 

In case this isn't clear, here's a picture explaining what I'm looking for (and a simple option under View would be a perfect spot for a simple toggle).

![column-vs-row-layout](https://user-images.githubusercontent.com/9098303/80727689-03d1c380-8ad4-11ea-8585-20dc137b61f6.png)

**Comment by MohammadAbusaleh** [comment]
this would be a great feature, I also looked through the docs couldn't find anything.

**Comment by johanrosenson** [comment]
I wish for this features to be available in the new version hinted in the latest newsletter.

**Comment by mpociot** [comment]
This will be in the next release 🎉
