### ISSUE TITLE
'Watch File' broken?

### ISSUE THREAD

**Issue by jesseleite** [beyondcode/tinkerwell-community#207]
Hey @mpociot, thank you for implementing the 'Watch File' feature (#60)!  However, I just want to test and it doesn't seem to be working.  Am I doing something wrong here (see gif), or is it broken?

![2020-05-06 08 46 48](https://user-images.githubusercontent.com/5187394/81178964-ffdfee80-8f76-11ea-850a-5bfce44f20e5.gif)

**Comment by sschlein** [comment]
Is this still the case with 2.8.3? Works here :)

**Comment by jesseleite** [comment]
@sschlein Still broken on 2.8.3 here.

**Comment by mpociot** [comment]
@jesseleite Does it stil happen on the latest version of Tinkerwell? We're unable to reproduce it.

**Comment by jesseleite** [comment]
Just tested, still seems broken on 2.8.5 here; Assuming that's latest version?

**Comment by sschlein** [comment]
Can you try different code editors? Older versions did not strip out the starting php tag but recent versions do. It is not directly a Tinkerwell issue as it works for us and others but I'd really like to know the issue on your machine so that we can have a solution for this.

**Comment by jesseleite** [comment]
Same issue with VSCode.  In the screenshot above, I'm just using terminal Vim (my main editor).  `<?php` tags never get stripped out.  My watched file looks like...

```php
<?php

echo 'Hello?';
```

If it helps, I could 🍐 / screenshare with one of you?
