### ISSUE TITLE
Font not being rendered correctly

### ISSUE THREAD

**Issue by jusdeleon** [beyondcode/tinkerwell-community#209]
Not sure if this is an issue with the [Cascadia Code](https://github.com/microsoft/cascadia-code) font or the app, but I tried another custom font called [Hack](https://github.com/source-foundry/Hack) and it rendered correctly.

<img width="1433" alt="tinkerwell" src="https://user-images.githubusercontent.com/8758708/81247370-6d118380-904c-11ea-9d1e-0d5257ee3d9b.png">

**Comment by mpociot** [comment]
This will be fixed in the next release
