### ISSUE TITLE
Be able to get script progress or flush output

### ISSUE THREAD

**Issue by pstephan1187** [beyondcode/tinkerwell-community#210]
I often execute long-running scripts with tinkerwell, many of which take over an hour to run. I would love to be able to get the progress of that script somehow. Echoing, printing, dumping, etc don't show up until after the script has finished. I would love to see a mode that outputted those statements to the screen immediately. Something like an artisan command (where we could make use of progress bars) would be preferred, but just simply pushing the responses back immediately would be great.

Keep up the great work. I love tinkerwell and I use it nearly every day!

**Comment by nm777** [comment]
This would be useful to me as well. You can use the following short script as an example. If you run this directly from the tinker shell, you'll see each dot appear one at a time. Using Tinkerwell, nothing appears for 10 seconds, then all 10 dots appear once the script is finished.

```
for ($i=0; $i<10; $i++) {
    echo '.';
    sleep(1);
}
```

Thank you again for a wonderful product!

**Comment by JonathanAspeling** [comment]
+1 Here would love this!

**Comment by mpociot** [comment]
This will be in the next release 🎉
