### ISSUE TITLE
Can not run tests

### ISSUE THREAD

**Issue by setkyar** [beyondcode/tinkerwell-community#211]
Can not run tests and getting the following error

> TypeError: Argument 3 passed to PHPUnit/TextUI/TestRunner::doRun() must be of the type array, bool given on line 12

Tinkerwell Version - 2.7.0
Laravel Version - 7 (also tried with Laravel 6)

![image](https://user-images.githubusercontent.com/4435358/81363542-97754680-9109-11ea-9c87-cc3792206c87.png)

**Comment by Mohammed-Alama** [comment]
I need a solution too

**Comment by sschlein** [comment]
Does this still happen with 2.8.3? Is Tinkerwell using the correct PHP version? Please check in the advanced settings

**Comment by setkyar** [comment]
@sschlein still does not work for me on Version 2.8.3 (2.8.3).

The following is for my own application

![image](https://user-images.githubusercontent.com/4435358/87293720-ba1c4500-c528-11ea-9e23-e651b0642c0a.png)

The following is tinkerwell's default result

![image](https://user-images.githubusercontent.com/4435358/87293797-d4562300-c528-11ea-9956-eec4532cb866.png)

**Comment by SignoreOladayo** [comment]
> Does this still happen with 2.8.3? Is Tinkerwell using the correct PHP version? Please check in the advanced settings

This still happens in 2.8.4 with the same error.

**Comment by sschlein** [comment]
I've been able to get the same output on my machine, we'll look into it.

**Comment by mpociot** [comment]
I just fixed this locally. I will publish a release that contains this fix later today.
The problem occurred due to changes in PHPUnit >= 8.5.4
