### ISSUE TITLE
Pasting or navigating scrollable text causes tabs to disappear

### ISSUE THREAD

**Issue by jasonvarga** [beyondcode/tinkerwell-community#214]
Pasting text long enough to cause the window to scroll causes the tabs to disappear.

![U3AQEC](https://user-images.githubusercontent.com/105211/81588190-27272900-9386-11ea-8fb8-b0a86682e25c.gif)

It also happens if you already have scrollable text and you cmd+arrow to jump to the end.

**Comment by squatto** [comment]
YES!! I was talking to @mpociot about this on Twitter and I had no idea why my tabs kept disappearing. I spent the majority of my time in tab-less Tinkerwell 😂 

Good catch!

**Comment by squatto** [comment]
I just accidentally figured out how to get your tabs back when they disappear: click the "Run Code" button in the toolbar. This one:

![image](https://user-images.githubusercontent.com/748444/82417473-d45e0900-9a38-11ea-8330-8cc7b77d2889.png)

You have to **click** it - using the hotkey to run your code won't work.

Hopefully that helps the bug get tracked down!

**Comment by mpociot** [comment]
This is not fixed in my local build, I'll tag a release later today.
