### ISSUE TITLE
Error starting Tinkerwell

### ISSUE THREAD

**Issue by 1jason1** [beyondcode/tinkerwell-community#215]
Hello, Im having issues just getting Tinkerwell to run even the default code that comes with Tinkerwell. Fresh install, open the app with Tinkerwell set to default. Uninstalled and re-installed. I'm at a loss, cannot figure out how to get it to work with even opening local laravel 6x and 7x projects. 

PHP runs fine on my system, please advise.

* Using 2.7.0 version of Tinkerwell
* PHP 7.4.2 

Code to run:
```PHP
/**
 * Welcome to Tinkerwell!
 *
 * You can tinker using the built-in
 * Laravel 7 application and use all the
 * nice Laravel features right away.
 *
 * Try modifying this file - the changes will
 * be automatically evaluated as you type.
 */

$movies = [
    [
        'name' => 'Back to the Future',
        'released_in' => 1985,
    ],
    [
        'name' => 'Ghostbusters',
        'released_in' => 1984,
    ],
    [
        'name' => '2001: A Space Odyssey',
        'released_in' => 1968,
    ]
];

collect($movies)
    ->sortBy(function ($movie) {
        return Arr::get($movie, 'released_in');
    })
    ->values()
    ->toArray();
```

Gets the following error:

```
TypeError 

  Argument 1 passed to _PhpScoperc223a629f245\Psy\Shell::add() must be an instance of _PhpScoperc223a629f245\Symfony\Component\Console\Command\Command, instance of Psy\Command\ParseCommand given, called in phar:///Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar/vendor/symfony/console/Application.php on line 395

  at phar:///Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar/vendor/psy/psysh/src/Shell.php:129
    125| 
    126| 
    127| 
    128| 
  > 129| public function add(\_PhpScoperc223a629f245\Symfony\Component\Console\Command\Command $command)
    130| {
    131| if ($ret = parent::add($command)) {
    132| if ($ret instanceof \_PhpScoperc223a629f245\Psy\ContextAware) {
    133| $ret->setContext($this->context);

      [2m+4 vendor frames [22m
  5   phar:///Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar/index.php:181
      _PhpScoperc223a629f245\Psy\Shell::__construct(Object(_PhpScoperc223a629f245\Psy\Configuration))

  6   /Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar:14
      require("phar:///Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar/index.php")
```

**Comment by sschlein** [comment]
Sorry for the late response, does it work after checking your PHP executable?

**Comment by 1jason1** [comment]
I was just now able to check, I use MAMP PRO as my environment so I tried several PHP versions.


Tried PHP 7.0.33
[cid:D1F05D05-DC44-480E-B398-F4CC99D90CD8@localdomain]

Another PHP version gets the error.

[cid:1F9A2BD8-DE20-446E-99E3-524CF04B010E@localdomain]





On Jul 9, 2020, at 7:38 AM, Sebastian Schlein <notifications@github.com<mailto:notifications@github.com>> wrote:



Sorry for the late response, does it work after checking your PHP executable?

**Comment by sschlein** [comment]
Can you please update your issue comment on github? Seems like you replied to the email and we can see your unique unsubscribe link and no screenshot.

**Comment by 1jason1** [comment]
Here are the attachments, screenshots are results from selecting different php versions.

<img width="1540" alt="PastedGraphic-3" src="https://user-images.githubusercontent.com/5578451/87339792-bb3f7900-c50c-11ea-88ec-5430220e7e6a.png">
<img width="1472" alt="PastedGraphic-2" src="https://user-images.githubusercontent.com/5578451/87339801-bed30000-c50c-11ea-82f1-8671aef1d1aa.png">

**Comment by sschlein** [comment]
The 2nd screenshot shows the issue (PHP version 7.0 is not enough to run some packages). 

I'm not sure about the first one yet.

**Comment by 1jason1** [comment]
Yeah, the PHP 7.0 screen shot was just to show that part works as expected.

**Comment by 1jason1** [comment]
@sschlein @mpociot Any ideas to get this to work? Just installed the latest version on my mac and still have the same issue.

Thanks!
Jason

**Comment by mpociot** [comment]
Hey Jason,

So you’re using 7.3.9?
Do you have any other version available to test? Does artisan tinker work from the command line for you?

**Comment by 1jason1** [comment]
Im using Tinkerwell 2.8.5, MacOs v 10.15.5, PHP 7.3.11, Laravel 7.25.0

**Comment by 1jason1** [comment]
Tinker does work from the command line for all the projects; 5.8.38, 7.25.0. In Tinkerwell I've tried the default site, and all my other sites with no success. 

Error with Laravel 5.8.38
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/5578451/90171964-ef09fa80-dd67-11ea-83e5-a6b5698e3b6e.png">

Error with Laravel 7.25.0
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/5578451/90172138-2d071e80-dd68-11ea-84ea-0f06d3798f53.png">

**Comment by sschlein** [comment]
@1jason1 this mostly happens if Tinkerwell is using the wrong PHP version. Can you select the correct binary again? We had a bug in a previous version that reverted to a broken path even if it worked before.

**Comment by sschlein** [comment]
I know that it must be odd to ask this again and again but these issues have been related to the wrong PHP executable for many many people and so I have no other solution for it :(
