### ISSUE TITLE
Table view hides SQL error messages

### ISSUE THREAD

**Issue by sebsel** [beyondcode/tinkerwell-community#216]
The table view is great for viewing results from an Eloquent query, especially when the query gets complex.

But, like most of us, I make mistakes in my SQL. The table view then just says: 'Error. No results found.'

I then have to do Cmd+Shift+C to go to CLI-mode, Cmd+R to rerun and see the error, fix it, go Cmd+Shift+T to the table-mode again, Cmd+R to rerun.

It would be very useful if errors can be displayed in the table-view itself. The easiest way is just to fall back to CLI-mode if no results are detected?

**Comment by mpociot** [comment]
This will be added to the next release
