### ISSUE TITLE
Allow to resize query log view

### ISSUE THREAD

**Issue by roberto-aguilar** [beyondcode/tinkerwell-community#217]
Currently is only possible to resize horizontally between to code and the results section, but not vertically between the query log and the results.

If you run the code while displaying the query, it is with the intention to debug how the query behaves, but there's too little room for it right now, and i think that was possible in the first versions of the application, not sure when it was removed.

![image](https://user-images.githubusercontent.com/5356595/82075227-88f6d400-96a1-11ea-938f-de3f5a55a5ea.png)

Please let me know if i can help in any way, @mpociot 😃 

Love to the Tinkerwell team ❤️

**Comment by mpociot** [comment]
The upcoming version of Tinkerwell is going to display the query in a much nicer way, so we won't need the ability to resize the query log view anymore.

![image](https://user-images.githubusercontent.com/804684/92399627-e3bdab00-f12a-11ea-97cc-f9991ab03398.png)

**Comment by roberto-aguilar** [comment]
It looks amazing, thank you, @mpociot 🤘
