### ISSUE TITLE
Strip out <?php from the start of the user input

### ISSUE THREAD

**Issue by antonkomarev** [beyondcode/tinkerwell-community#218]
If code starts from `<?php` we receiving an error:
> PHP Parse error: Syntax error, unexpected '<' on line 1

This might be fixed by just checking if code starts from `<?php` and stripping it out from user input before each execution. Code in text area wouldn't be changed but it will be ignored by parser. Then it will be much easier to run demo scripts  right after copy-pasting them.

**Comment by sschlein** [comment]
This has been released with 2.8.x
