### ISSUE TITLE
There is no Show Query menu in Windows

### ISSUE THREAD

**Issue by misbahansori** [beyondcode/tinkerwell-community#219]
I see video from Andre Madarang about Tinkerwell and I can see he can show the query for selected code. But when I using my Tinkerwell I cannot see that menu.

![Screenshot_42](https://user-images.githubusercontent.com/20674057/82266330-9e1a7e00-9993-11ea-95e9-0349c9b5cf5a.png)

![Screenshot_43](https://user-images.githubusercontent.com/20674057/82266401-cace9580-9993-11ea-87a1-057804e5673a.png)

**Comment by tjespers** [comment]
This is not a windows only problem, the whole Query inspector feature seems to be missing in v2.7.0? It's not in the menu's on Mac either and CMD+Shift+R does nothing in this version while it worked before.

<img width="546" alt="Screenshot 2020-05-24 at 14 15 49" src="https://user-images.githubusercontent.com/13832165/82753834-2dc39080-9dc9-11ea-9b0e-0676efbbe6ed.png">

**Comment by joisarjignesh** [comment]
In Ubuntu 18.04 same issue (does not see query action)

**Comment by sschlein** [comment]
Can you please check if it works with the latest version? We have created Tinkerwell docs here: https://beyondco.de/docs/tinkerwell/advanced-usage/query-inspection

**Comment by joisarjignesh** [comment]
@sschlein not working on latest as well v2.8.3  and laravel v7.19.0 (detected by tinkerwell)

if i select a code and then press ctrl+shift+r it will replace all window in ubuntu 18.04

**Comment by marezelej** [comment]
Not working on 2.10.1 windows with Laravel 7.

**Comment by mpociot** [comment]
This will be fixed in the next version

**Comment by gustavo9601** [comment]
Run query Inspection Not Working in 2.19.0, when will be the next realease that fix that bug ?
