### ISSUE TITLE
Req: Add shortcut keys/actions (⌘+k, ⌘+/)

### ISSUE THREAD

**Issue by Barry20** [beyondcode/tinkerwell-community#22]
Some that I find I am looking for frequently:

- ⌘+K clear window (this would be nice for both script pane and result pane)
- ⌘+/ comment line or selection

**Comment by Barry20** [comment]
Looks like there is some crossover with #3 and the comment toggle, this is the shortcut used with PHPStorm, I'm not sure if its the same with Sublime text key bindings, if so shut this down! :)

**Comment by mpociot** [comment]
We currently use the editor shortcuts from sublime text in combination with the Codemirror key-bindings.
Cmd + / is already implemented and Cmd+K behaves the same way as in Sublime Text from what I can tell.
