### ISSUE TITLE
Problem with Sublime Text plugin

### ISSUE THREAD

**Issue by dchatry** [beyondcode/tinkerwell-community#220]
I would like to use Tinkerwell with Sublime Text but can't seem to get it to work.

I have the latest version of Tinkerwell (2.7.0), I installed the Tinkerwell plugin for Sublime Text, I can see the two new items in the contextual menu "Run with/Open in Tinkerwell", but when I click I get the following error in the console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "/Users/damien/Library/Application Support/Sublime Text 3/Installed Packages/Tinkerwell.sublime-package/Tinkerwell.py", line 57, in run
  File "/Users/damien/Library/Application Support/Sublime Text 3/Installed Packages/Tinkerwell.sublime-package/Tinkerwell.py", line 41, in getPHPBinary
KeyError: 'phpBinary'
```

Apparently it's expecting a `phpBinary` path from a plist file, I checked the plist file but it doesn't contain the key 'phpBinary' or anything related.

**Comment by wingsline** [comment]
Same issue here. It seems this plugin wasn't updated to work with Tinkerwell 2. If you downgrade to v1, it works, but vscode won't work then...

Tried to add the phpBinary to the plist, then you get a new error:

```
Could not open input file: /Applications/Tinkerwell.app/Contents/Resources/tinker.php
```

Seems like this plugin wasn't updated for quite some time (3 months now).

**Comment by sschlein** [comment]
I have released docs for the plugins here https://beyondco.de/docs/tinkerwell/basic-usage/ide-plugins – it also includes links to the GitHub issues that we are going to use to fix the macOS bugs.
