### ISSUE TITLE
DataTables throws a warning when a key contains a period

### ISSUE THREAD

**Issue by squatto** [beyondcode/tinkerwell-community#224]
I pulled some data from an API today and ran it through `Arr::dot($array)` to flatten it while still keeping the structure, and then used `Arr::only()` to pull out the keys I wanted to see:

```php
$api->getInventoryItems()
    ->filter(function (array $item) {
        return !empty($item['metadata']['print_sku']);
    })
    ->map(function (array $item) {
        return Arr::only(
            Arr::dot($item),
            [
                'id',
                'code',
                'price',
                'update_source',
                'metadata.print_sku',
                'metadata.print_url',
            ]
        );
    });
```

What I ended up with is this structure:

```php
[
  [
    "id" => 42165121,
    "code" => "ABC123",
    "price" => 29.95,
    "update_source" => "Shopify",
    "metadata.print_sku" => "wood-sign-15x5",
    "metadata.print_url" => "TBD",
  ],
  // ...
]
```

This is great in CLI mode, but when I switch to table mode, I get the following DataTables warning (twice):

![Screen Shot 2020-05-21 at 4 34 06 PM](https://user-images.githubusercontent.com/748444/82612772-e6e35a00-9b80-11ea-9911-e4d716ab8d84.png)

The table *does* render, but the values don't show for any key with a period in them:

![Screen Shot 2020-05-21 at 4 35 24 PM](https://user-images.githubusercontent.com/748444/82612840-14c89e80-9b81-11ea-91fb-03afc1a2196c.png)

Looking through the DataTables docs, it looks like you just need to make sure to escape periods in the parameter name: https://datatables.net/reference/option/columns.data#string

![image](https://user-images.githubusercontent.com/748444/82613047-9fa99900-9b81-11ea-820e-322ab2cfe6d3.png)

Thanks!

**Comment by mpociot** [comment]
This is now fixed and will be added to the next Tinkerwell release
