### ISSUE TITLE
Add JSON Tinker Mode

### ISSUE THREAD

**Issue by antonkomarev** [beyondcode/tinkerwell-community#225]
It will be great to have some kind of option to see JSON pretty printed output.

Right now I'm doing it like this:
```php
dd(json_encode(json_decode($json), JSON_PRETTY_PRINT));
```

Output is no so great
```js
"""
{\n
    "type": "User",\n
    "id": "6ff63a53-6c3a-42ee-a9c1-f00a097c2917",\n
    "attributes": {\n
        "username": "test-user",\n
        "created_at": "2020-05-21T15:45:32+00:00"\n
    }\n
}
"""
```

I'd prefer to receive it with some kind of special helper method which will produce valid json without line breaks characters at the end of each line and without empty quotes on the both sides of output:
```json
{
    "type": "User",
    "id": "6ff63a53-6c3a-42ee-a9c1-f00a097c2917",
    "attributes": {
        "username": "test-user",
        "created_at": "2020-05-21T15:45:32+00:00"
    }
}
```

**Comment by antonkomarev** [comment]
I've thought a bit more and now I think it will be better to add new Tinker Mode: JSON
And it will always try to represent output as pretty printed JSON.

**Comment by antonkomarev** [comment]
Using this way we could display it without `"""` and `\n`, but anyway it's too boring to write all the time :D
```php
echo json_encode(json_decode($json), JSON_PRETTY_PRINT);
```

**Comment by mpociot** [comment]
We're not going to add a new JSON mode anytime soon, I'll close this for now.

**Comment by niladam** [comment]
@mpociot While i agree that adding a new mode seems a bit overkill, how about some easier solution to pretty printing a json response/object ?
