### ISSUE TITLE
Turn off deprecated warning

### ISSUE THREAD

**Issue by edalzell** [beyondcode/tinkerwell-community#226]
Hey there,

I seem to be getting a deprecated error every time I connect to the DB:
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/6069653/83338164-5a1e5780-a276-11ea-8bcb-fca6a922d88b.png">

Currently using Laravel 5.8.

Anyway to turn these warnings off?

**Comment by sschlein** [comment]
Hey, this is something that is related to your local PHP configuration and not related to Tinkerwell specifically. You can turn off these warnings in your PHP.ini
