### ISSUE TITLE
Issues working with Stripe SDK 

### ISSUE THREAD

**Issue by dlaytonjames** [beyondcode/tinkerwell-community#227]
Hi folks

I'm probably doing something really dumb here but given

use Stripe\Stripe;
use Stripe\Subscription;

Stripe::setApiKey("sk_test_**");

$sub = Subscription::retrieve('sub_***');

I get 

PHP Fatal error:  Class 'Stripe/Stripe' not found in Psy Shell code on line 4

**Comment by dlaytonjames** [comment]
The above works in artisan tinker

the code below works in tinkerwell using the stripe client

use Stripe\StripeClient;

$stripe = new StripeClient(
  'sk_test_*********'
);

$stripe->subscriptions->retrieve(
  'sub_******',
  []
);

**Comment by jasonvarga** [comment]
Make sure that you're working within your project. Click the folder icon then choose your Laravel project.

**Comment by dlaytonjames** [comment]
yep 100%, it's defo in my project

**Comment by sschlein** [comment]
@dlaytonjames Have you been able to resolve this? I don't think that we have a general issue and it seems to relate to your project or local setup (pls check your PHP executable in the advanced settings)

**Comment by dlaytonjames** [comment]
anything specific i should check for?
![Screen Shot 2020-07-14 at 15 08 26](https://user-images.githubusercontent.com/4245429/87435639-ec3ead00-c5e3-11ea-9678-694cb045d824.png)

**Comment by dlaytonjames** [comment]
issue still there, if you think it's local env issue then feel free to close and i'll carry on with normal cli tinker which works fine.
