### ISSUE TITLE
Could not open tinkerwell.phar

### ISSUE THREAD

**Issue by niteen1593** [beyondcode/tinkerwell-community#228]
I have installed tinkerwell 2.7.0 today on my Windows 10 2004 machine and I am getting following error
![image](https://user-images.githubusercontent.com/62459792/83872740-32d0fa00-a750-11ea-9ca2-c522ad7e985f.png)
System details
Windows 10 2004 x64
PHP 7.4.6
Tinkerwell 2.7.0

**Comment by sschlein** [comment]
@niteen1593 does it work with the newest version 2.8.3?

**Comment by niteen1593** [comment]
with 2.8.3 also I am getting same problem.
![image](https://user-images.githubusercontent.com/62459792/87299608-ff8d4200-c529-11ea-8778-7edda615cfb2.png)

**Comment by mpociot** [comment]
Do you have any idea how we could reproduce this?

**Comment by niteen1593** [comment]
It is happening on windows system when php is installed on WSL (Windows subsystem Linux) and using [Windows interoperability with Linux](https://docs.microsoft.com/en-us/windows/wsl/interop). but it shows correct php version on setting page as you can seen in above comment but in editor shows error.

**Comment by mpociot** [comment]
I wasn't able to reproduce this issue locally. If the error still exists for you, feel free to reopen it.
