### ISSUE TITLE
Editor not working as expected

### ISSUE THREAD

**Issue by Wulfheart** [beyondcode/tinkerwell-community#229]
When I have the function ``ReadableHumanNumber(1234, true, 2)`` and I want to replace ``Human`` with something else, e.g. ``Foobar``, then I navigate to the ``H``, delete ``Human`` and then type ``Foobar``. However this results in this function
````` 
ReadableFoobar(1234, true, 2)
````

Is there any way to change this? I didn't find any settings regarding this and it's slowing me down.

**Comment by sschlein** [comment]
We are limited by the editor component and this doesn't seem to be an issue other users, so I'm closing this for the moment. This doesn't mean that we won't to it at any time in the future, but it is not something that will get our priority soon.
