### ISSUE TITLE
Doesn't work on linux.

### ISSUE THREAD

**Issue by inmanturbo** [beyondcode/tinkerwell-community#231]
When I run the AppImage from terminal I just get this:
```
Warning: require_once(phar:///tmp/.mount_TinkerlUd7AS/resources/tinkerwell/tinker.phar/vendor/composer/autoload_static.php): failed to open stream: phar error: internal corruption of phar "/tmp/.mount_TinkerlUd7AS/resources/tinkerwell/tinker.phar" (actual filesize mismatch on file "vendor/composer/autoload_static.php") in phar:///tmp/.mount_TinkerlUd7AS/resources/tinkerwell/tinker.phar/vendor/composer/autoload_real.php on line 28

Fatal error: require_once(): Failed opening required 'phar:///tmp/.mount_TinkerlUd7AS/resources/tinkerwell/tinker.phar/vendor/composer/autoload_static.php' (include_path='.:/usr/lib64/php') in phar:///tmp/.mount_TinkerlUd7AS/resources/tinkerwell/tinker.phar/vendor/composer/autoload_real.php on line 28
```
And none of the code runs. I did pay money for this because it said it works on linux.

**Comment by micksp** [comment]
Works fine for me on linux. I'm on ubuntu 18.04.
I put tinkerwell as symlink in /usr/local/bin/tinkerwell to /opt/Tinkerwell-2.7.0.AppImage
(the appimage is executable)

**Comment by inmanturbo** [comment]
> Works fine for me on linux. I'm on ubuntu 18.04.
> I put tinkerwell as symlink in /usr/local/bin/tinkerwell to /opt/Tinkerwell-2.7.0.AppImage
> (the appimage is executable)

Same here. Symlinked from opt. (As I usually do with  AppImages)

I'm not on Ubuntu, I'm on Clear Linux but the distro shouldn't really matter with an AppImage, I also tried on Centos8. When running as root It does load the test script at least, but then it just freezes there and never actually evaluates any code. I'm able to log into beyondcode and retrieve my license and download the latest version etc but it just isn't working for me for some reason. I had the same issue month ago and just gave up and set up a php kernel on a jupyter notebook server instead. But now I'm on another project where I would really like to use it and it just isn't working. It's too bad; it is a really great tool.

**Comment by micksp** [comment]
That really sucks. It is a great tool, but support lacks and docs is not great as well. I learn as i go, really. 
Anyway, maybe you could try setting it up in a local container-like solution and share your work directory into the container.  
A tip as an aside: I use clockwork to look under the hood of laravel projects and it often fills the gap. It's realy very helpfull, though not a replacement. Check it out here https://github.com/itsgoingd/clockwork

**Comment by inmanturbo** [comment]
Thanks for the suggestion. I'll check it out.

**Comment by njames** [comment]
Note for the OP: I set up a directory ~/AppImages and used AppImage Launcher to well launch them. 
https://github.com/TheAssassin/AppImageLauncher

Then then behave like "real apps" and become findable from the dash etc.

HTH

**Comment by inmanturbo** [comment]
@njames I appreciate this, I'll give it a try and see if it helps at all. The issue Though isn't being able to find it in the dash. I can create my own desktop entry and add the image to my path just fine -- It just doesn't work. It either freezes or gives me startup errors. Particularity path errors within the archive, which is strange. I'm not sure why. The app seems to be unable to autoload dependencies from within the archive. I have no issues on this system with composer or phars nativity or otherwise. Seems like a bug, but there is a lot of documentation to help sort it out.

Thank you though -- that looks like a vary handy little repo there and I'll probably begin using it regularly to save me some time spent doing some of that stuff manually.

**Comment by sschlein** [comment]
@inmanturbo have you been able to solve this? I also tried on Ubuntu 18.04 and have no issues.

**Comment by sschlein** [comment]
@inmanturbo Unfortunately, we have no resources to test our apps across all Linux distributions, so I doubt that we'll be able to debug/fix this in the near future. I know that this is not the answer that you'd like to hear but I can't come up with a sufficient business case to do it without increasing the price of Tinkerwell multiple times (and selling a lot).

I'll update the Tinkerwell website/docs to make it clear that we have only tested Tinkerwell on Debian derivates and can't guarantee that the app works on other versions. If that makes it unusable for you, please email us your license key or order number at support@beyondco.de so that we can do a refund.

**Comment by sschlein** [comment]
Updated FAQ on system requirements: https://tinkerwell.app/faq/#jump-to-2
