### ISSUE TITLE
How can you exit file watch?

### ISSUE THREAD

**Issue by earnjam** [beyondcode/tinkerwell-community#233]
I was testing out file watching, but then I couldn't find a way to bring the code editor back. I tried to set the working directory, revert back to the default laravel app, etc. Nothing seemed to work. Is there something I'm missing?

I was finally able to fix it by directly editing `~/Library/Application Support/Tinkerwell/vuex.json` and change `isWatching` to `false` and then restarting the app.

**Comment by sschlein** [comment]
<img width="379" alt="Bildschirmfoto 2020-06-15 um 10 48 52" src="https://user-images.githubusercontent.com/2911113/84637371-e62ab300-aef5-11ea-8a07-51e8506eb7e8.png">

**Comment by earnjam** [comment]
Yikes. 🤦 

I'm pretty sure I looked there since that's how you turn on file watch and it still showed "Watch File" as if to choose a different file. But I maybe I just glossed over it. 

Sorry for the trouble.
