### ISSUE TITLE
tinkerwell helper doesn't work

### ISSUE THREAD

**Issue by Petoches** [beyondcode/tinkerwell-community#234]
Hello,

Im recently purchased tinkerwell and installed the package tinkerwell helper.

i made a simple controller returning a string to the webpage with the helper tinker($test), but nothing happen, tinkerwell isn't opening and even though i let him open manually the var $test doesn't exist.

i'm on MacOs High Sierra running a simple app through docker.

**Comment by molnarjg** [comment]
Similar issue with same scenario. Using Tinkerwell 2.8.1 under Win10 using VSCode.

`exec(): Unable to fork [open &quot;tinkerwell://?`

`PHP Notice:  Undefined variable: test in phar://C:/Users/{}/AppData/Local/Programs/Tinkerwell/resources/tinkerwell/tinker.phar/index.php(109) : eval()'d code on line 1`

**Comment by princejohnph** [comment]
Same issue for me.

PHP Notice:  Undefined variable: temp0 in phar:///tmp/tinker_compressed.phar/index.php(109) : eval()'d code on line 1

**Comment by mpociot** [comment]
I'll close this and continue the discussion here: https://github.com/beyondcode/tinkerwell-helper/issues/6
