### ISSUE TITLE
Line number reported over SSH doesn't seem stable or accurate

### ISSUE THREAD

**Issue by simensen** [beyondcode/tinkerwell-community#236]
When connecting via SSH, I get output like this:

```
PHP Notice:  Undefined index: missing in phar:///tmp/tinker_compressed.phar/index.php(108) : eval()'d code on line 97
```

I have yet to figure out if the "line 97" is a consistent offset from where the actual line number that should be reported. The only thing I'm pretty sure about is that "line 97" isn't the actual line that caused the problem.

Is there some internal math I can do? Like, is there always a fixed extra header or something that is added that I can say, "oh, if it says line 97, it's actually like 93 because it is always 4 lines too high"?

**Comment by njames** [comment]
Can confirm :point_up: 

Also when opening files that have been saved by tinkerwell when they have added a comment banner to the top, the editor seem to be out by those number of lines initially. 

I have placed my cursor and started typing to find my text being entered 6 lines above. 

Also files saved multiple times get multiple banners. 

Sorry to add to @simensen 's issue but these seemed like related behaviours.
My install is 2.8.5 on Linux (AppImage)

**Comment by mpociot** [comment]
We currently strip out all lines that contain any PHP comment, so you could subtract that from the given code line.
