### ISSUE TITLE
Typing does not show any text in CLI or testing mode.

### ISSUE THREAD

**Issue by admench** [beyondcode/tinkerwell-community#237]
Simply put I only see 1 pane... with 1 line at the top, and I cannot type into it. I've been using Tinkerwell for months, but now I cannot use it.

![Screenshot 2020-06-18 at 18 34 15](https://user-images.githubusercontent.com/672916/85053430-63725400-b192-11ea-9963-a603b2898ad3.png)

Using v 2.7.0
OS X 10.15.3

Tried macbook pro keyboard and external keyboard.
Any tips to get it working again would be GREATLY appreciated. Many thanks

**Comment by admench** [comment]
I've tried reinstalling Tinkerwell and also restarting mac.

Can I delete some preference files perhaps somewhere?

**Comment by admench** [comment]
PHP info:

![Screenshot 2020-06-18 at 18 38 44](https://user-images.githubusercontent.com/672916/85053804-f90de380-b192-11ea-9a43-2925a3fd5819.png)

I have not changed PHP version for many months, simply using a Valet setup. Same issue in SSH mode.

**Comment by sschlein** [comment]
<img width="345" alt="Bildschirmfoto 2020-06-18 um 19 39 30" src="https://user-images.githubusercontent.com/2911113/85053904-7f2e2800-b19b-11ea-86b6-5dddcfce400d.png">

?

**Comment by admench** [comment]
Y
E
S

Thank you Sebastian! Much appreciated! Strangely even after reinstalling and it isn't watching a file, it shows up with 1 pane not 2. Anyway, I'm happy it is fixed by doing this for now.
