### ISSUE TITLE
Ignore leading `<?php` tag

### ISSUE THREAD

**Issue by simensen** [beyondcode/tinkerwell-community#238]
I'm using Tinkerwell extensively with one of my projects where I actually have a `tinkers/` directory for some one-off manual reports that don't have other better places to live in my repo. I like to be able to edit these files in Tinkerwell itself but also in PhpStorm.

The downside is that to get proper formatting in PhpStorm, I need to have `<?php` at the top of the file. If I open the file with Tinkerwell, and try to run it, it complains:

```
PHP Parse error: Syntax error, unexpected '<' on line 1
```

Otherwise, I'd consider trying to use Tinkerwell in PhpStorm directly, but I'm not sure how to get it to work with my SSH connections. I think it is related to #124 which was closed so I don't know if I should create a new issue for that or not.

Since I've never had PhpStorm integration working for my project, I'm not sure how the integration works and whether I can run a whole file or not. If I can, then I assume there is already something in place to let someone run a PHP file that starts with `<?php`. Or maybe not. :)

**Comment by mpociot** [comment]
This will be in the next release
