### ISSUE TITLE
SSH connection copy/duplicate

### ISSUE THREAD

**Issue by c17r** [beyondcode/tinkerwell-community#239]
For a small client I have multiple environments running from a single server so the SSH connections are identical except for `App Folder`. Having a `Duplicate` button where the new label is `Copy of <original>` would be handy.

Thanks for creating Tinkerwell, it's been fabulous.

**Comment by mpociot** [comment]
This will be added to the next release

**Comment by c17r** [comment]
I updated to v2.9.0 and how is this supposed to work? The MOTD listed this as "context menu". Regardless of whether I single or double left click the entry, a right click doesn't show anything. If I right click quickly it looks like a context menu tries to appear but immediately hides again. I'm not 100% sure how I did it -- either trying to quickly click the context menu or key combination -- but all I've managed to do is unintentionally delete my existing SSH entries.

**Comment by sschlein** [comment]
Any hint to your operating system?

**Comment by c17r** [comment]
Windows 10

**Comment by gander** [comment]
Was it added or not? In #507 I asked for this functionality, but they declined saying they don't need it. Removed?
