### ISSUE TITLE
Feature Request: Implement support for Laravel Debugbar

### ISSUE THREAD

**Issue by Tray2** [beyondcode/tinkerwell-community#240]
I think it would be an awesome feature if it was possible to integrate the Laravel Debugbar or at least make it possible to add as an plugin.
[https://github.com/barryvdh/laravel-debugbar](https://github.com/barryvdh/laravel-debugbar)

**Comment by sschlein** [comment]
Could you provide more information about that? Where would you like to use it?

**Comment by Tray2** [comment]
I would like to have it in CLI mode. That way you can test the effeciency of your Query Builder/Eloquent queries before using them in your code. It would also make it easier to see the resulting SQL from the query you built along with the result.

So if I do something like this

```php
Book::where('format_id', '1')->get();
```
I would see something like this

```sql
select * from `books` where `books`.`format_id` = 1 and `books`.`format_id` is not null
```

Together with the information about the execution times and memory usage

```
22ms 5MB 
```

**Comment by mpociot** [comment]
@Tray2 The next version of Tinkerwell will allow you to see the queries executed in specific lines of code: https://twitter.com/marcelpociot/status/1291027008718331905
