### ISSUE TITLE
Tinkerwell not working. Blank screen

### ISSUE THREAD

**Issue by ekrist1** [beyondcode/tinkerwell-community#241]
Just bought Tinkerwell and installed the software, but it only show a blank screen. Preferences and adding a licence do not react. There are no visible error-messages.

Any guidance how to correct this?

OS: macOS Catalina 10.15.5
PHP: 7.4.7 (located /usr/local/bin/php). Homebrew

<img width="1082" alt="Screenshot 2020-06-30 at 20 09 44" src="https://user-images.githubusercontent.com/8544305/86162365-f6a27680-bb0e-11ea-9581-36e7b4b7de22.png">

**Comment by ahmic** [comment]
Same here. You can try the previous version until they fix latest

https://tinkerwell.fra1.digitaloceanspaces.com/tinkerwell/Tinkerwell-2.7.0.dmg

**Comment by ekrist1** [comment]
> Same here. You can try the previous version until they fix latest
> 
> https://tinkerwell.fra1.digitaloceanspaces.com/tinkerwell/Tinkerwell-2.7.0.dmg

Thanks. The 2.70 version seems like working.

**Comment by sschlein** [comment]
You can update from 2.7 to 2.8 and this works. It's an issue on the first install of tinkerwell that we fix at the moment. 2.8.1 incoming shortly.

**Comment by sschlein** [comment]
2.8.1 is live :)

**Comment by BramVanBerkel** [comment]
Hi, still having the same issue on 2.8.1:
<img width="1545" alt="image" src="https://user-images.githubusercontent.com/15030624/86286511-de058f80-bbe6-11ea-8d33-26321cf5d092.png">

**Comment by BramVanBerkel** [comment]
Hi, is this issue still on the radar? Do I need to open a new issue or can I help debug this?

**Comment by sschlein** [comment]
It's here: https://github.com/beyondcode/tinkerwell-community/issues/247

We've already fixed this and are bundling multiple things into a release at the moment.
