### ISSUE TITLE
Display execution time, memory usage, compare implementations

### ISSUE THREAD

**Issue by deligoez** [beyondcode/tinkerwell-community#243]
It would be really great to see an execution time and memory usage for performance testing purposes.

Especially if we can run code side by side and compare them (time, usage) in percent.

![Screen Shot 2020-07-02 at 00 49 30](https://user-images.githubusercontent.com/3030815/86294890-1a90b580-bbfe-11ea-988b-43dfb6e72539.png)

**Comment by mpociot** [comment]
This will be added in the next release

**Comment by MatanYadaev** [comment]
Hey @mpociot , I don't see the memory usage, how can I turn it on?
