### ISSUE TITLE
Search SSH Connections

### ISSUE THREAD

**Issue by SudoGetBeer** [beyondcode/tinkerwell-community#244]
Hello,

could you make it possible to delete ssh connections and some way to order them? Or to search for them?
We have a lot ssh connections configured so that would help me a lot.

Thanks!

**Comment by mpociot** [comment]
You can already delete a SSH connection by selecting it and press the backspace button.
But I agree. Searching would be a nice little UI improvement. We'll add it to our backlog!

**Comment by SudoGetBeer** [comment]
Wow that was fast.

I noticed a minor bug when using the forge api.

Tinkerwell also loads revoked(archived?) servers. So we also get old domains and on some ssh connection the wrong IP (same domain but on multiple servers?). Is it possible that you only load non revoked servers?

**Comment by mpociot** [comment]
This will be fixed in the next release

**Comment by SudoGetBeer** [comment]
@mpociot hey just wanted to aks if the searching in ssh connections is still on the backlog? Maybe something like CMD+P in Tableplus?
