### ISSUE TITLE
Query inspection not available MAC / 2.8.1

### ISSUE THREAD

**Issue by gbachev** [beyondcode/tinkerwell-community#245]
Hi,

Just bought the Tinkerwell app (MAC OS) and can't trigger the query inspection. My version is 2.8.1.

I have read this thread: https://github.com/beyondcode/tinkerwell-community/issues/204
Tried CMD+SHIFT+, CTRL+SHIFT+P, CMD+SHIFT+P as suggested in the Tinkerwell docs and in the fore-mentioned thread but no-luck. It's missing in the context menu, too.

Please, advise how to activate the query inspection :)

If you have removed the feature from the app, please also update the docs as it's misleading: https://beyondco.de/docs/tinkerwell/advanced-usage/query-inspection

Best,
Georgi

**Comment by sschlein** [comment]
Please don't cross-post in multiple issues :)

https://github.com/beyondcode/tinkerwell-community/issues/204#issuecomment-654068160
