### ISSUE TITLE
Tinkerwell non responsive

### ISSUE THREAD

**Issue by njames** [beyondcode/tinkerwell-community#246]
Version 2.8.1 on Ubuntu 19.10

TW App  is non responsive to enter code or change mode, change working dir. 
Can watch file, open files (nothing updates in editor)

![image](https://user-images.githubusercontent.com/491726/86583623-ed118680-bfc6-11ea-8449-26e1666fd71a.png)

I have uninstalled and reinstalled a new app image and rebooted my laptop.

Still no Tinkerwell. 

Thoughts?

**Comment by njames** [comment]
Solution was to find my config directory in `~/config/Tinkerwell` rename it to `.old` and restart Tinkerwell and then reapply the licence.

**Comment by njames** [comment]
Aside from that and a few other niggles very useful software. :+1:

**Comment by sschlein** [comment]
Related to #247
