### ISSUE TITLE
No output pane

### ISSUE THREAD

**Issue by Synchro** [beyondcode/tinkerwell-community#247]
I'm running Tinkerwell 2.8.1 on macOS High Sierra (latest OS I can run on my old MacBook). The output pane does not appear at all. Selecting view->toggle output does nothing. Resizing the window doesn't help, nor does going into full screen mode.

**Comment by njames** [comment]
sounds similar to my experience ... https://github.com/beyondcode/tinkerwell-community/issues/246 

See if you can find and rename your vuex.json file ... it might just give it a kick. (you will lose saved settings though)

**Comment by Synchro** [comment]
I also noticed this slightly odd behaviour, which may be related:

![image](https://user-images.githubusercontent.com/81561/86587932-ed8c2c00-bf8a-11ea-9202-174a39166989.png)

Note that the first line is not wrapping but extends off the edge of the window, yet there is no horizontal scroll option or any way of making the line visible, though if I narrow the window it does force it to wrap eventually.

This leads me to think that the vertical divider between input and output windows may be located just beyond the right edge of the window, and this may also be why the output window ends up invisible. I tried expanding the window to two screens wide, but it did not make the divider appear. Perhaps a calculation problem with divider position on non-retina screens?

**Comment by Synchro** [comment]
@njames Sounds good but... I don't have a `~/.config/Tinkerwell` dir...

**Comment by Synchro** [comment]
I did find a settings file in `~/Library/Application Support/Tinkerwell/vuex.json`. Changing a few settings and relaunching Tinkerwell made the output window appear. I looked at the contents of the settings file and noticed that there does not appear to be a width property for the panes stored, so I guess the division point must be calculated on the fly, and there must a be small bug in there.

**Comment by sschlein** [comment]
Thanks for this hint! We'll see when we can release a fix!

**Comment by ncatanchin** [comment]
@sschlein no longer able to use the software. I'm on Windows 10. Tried some of the above, tried to uninstall / reinstall. Do you have an ETA on the fix, or any knowledge on getting it working again in Windows 10?

Confirm that previous version 2.7 was working ok, and even 2.8.1 worked well for a few days.

**Comment by mpociot** [comment]
@ncatanchin Unfortunately we're unable to reproduce this bug. Do you have the content of your vuex.json file so that we can look into it? You can also send it via mail to support at beyondco.de

**Comment by sschlein** [comment]
We were able to reproduce the bug with the provided vuex file and have fixed it. We'll release a fix soon.

**Comment by sschlein** [comment]
We just released 2.8.2 which fixes this issue.

**Comment by Synchro** [comment]
Thank you!
