### ISSUE TITLE
Add .php extension when saving a file

### ISSUE THREAD

**Issue by jmarcher** [beyondcode/tinkerwell-community#248]
I just noticed that I saved a file in Tinkerwell, omitted the .php at the end, and if I want to open the same file again I can not see the file in the list, because the file-browser is filtered to see only .php files.

I think adding the .php extension at the end when none given should suffice or another option is to allow for an option "All files" on the file-browser.

**Comment by sschlein** [comment]
@jmarcher Which operating system do you use? I just tested it on my Mac and it appends .php

**Comment by jmarcher** [comment]
@sschlein I use Manjaro Linux

**Comment by sschlein** [comment]
The next version allows opening files without extensions by switching the filter to "All files"

**Comment by jmarcher** [comment]
Nice! Thanks!
