### ISSUE TITLE
Can't install 2.8.1 or 2.8.2 on Windows 10

### ISSUE THREAD

**Issue by nachod6692** [beyondcode/tinkerwell-community#249]
Hi! 

Two days ago I had an issue on Windows very similar to #241, so I tried restarting v2.8.1. The installer got stuck halfway so I figured I'll try to delete everything related to Tinkerwell on disk and try again but the installer still won't budge.

The same thing happened with 2.8.2

![image](https://user-images.githubusercontent.com/11573483/87087082-795abe00-c200-11ea-9a84-4f5a7cca0388.png)

Is there anyway to find a log of the installer so I can attach it here? Or something that can be helpful
Anyways, thanks for making such a cool app, well worth it!

**Comment by phillipsharring** [comment]
@nachod6692 you closed this. Was there a solution? I'm having the same issue now.

**Comment by phillipsharring** [comment]
This may be caused by an install that was not uninstalled using Add/Remove Programs, but simply removed from disk. There's a possible fix [here](https://github.com/electron-userland/electron-builder/issues/4057#issuecomment-557570476), which worked for me.

**Comment by nachod6692** [comment]
Hey, yeah that's exactly what happened, using the Add/Remove Programs resolved the issue, thanks!
