### ISSUE TITLE
Behavior of api resource

### ISSUE THREAD

**Issue by Mohammed-Alama** [beyondcode/tinkerwell-community#252]
I'm trying to see how eloquent resource look after some transformation and edits 
![Screen Shot 2020-07-14 at 1 01 28 AM](https://user-images.githubusercontent.com/24527701/87361935-9fb88a80-c56d-11ea-9595-1abc0bb6f661.png)
it must be like this ..or I'm wrong
![Screen Shot 2020-07-14 at 1 01 39 AM](https://user-images.githubusercontent.com/24527701/87361956-a941f280-c56d-11ea-8a97-52d885dc20b5.png)

**Comment by sschlein** [comment]
I don't get your question

**Comment by Mohammed-Alama** [comment]
ok now this is my resource 
![Screen Shot 2020-07-14 at 7 56 12 PM](https://user-images.githubusercontent.com/24527701/87460120-a5b17880-c60c-11ea-89d3-267a71531c44.png)
when assigning the Rule model to a resource like this
![Screen Shot 2020-07-14 at 8 03 18 PM](https://user-images.githubusercontent.com/24527701/87460491-3ee08f00-c60d-11ea-9899-5c7e1774adb1.png)
the result must be like 
![Screen Shot 2020-07-14 at 1 01 39 AM](https://user-images.githubusercontent.com/24527701/87460566-59b30380-c60d-11ea-9dee-ab99bf8b766e.png)
but it returns that 
![Screen Shot 2020-07-14 at 8 06 04 PM](https://user-images.githubusercontent.com/24527701/87460668-7f400d00-c60d-11ea-818b-cc0d4ae44a77.png)

I hope it's clear now .. I don't know if it's a misunderstanding of how resource work in tinkerwell or it's the actual result

**Comment by sschlein** [comment]
That's intended behavior =)

Tinkerwell returns the RulesResource and not the array representation. If you want to return the array, your code in Tinkerwell needs to know this:

`new RulesResource[...])->toArray()`

**Comment by Mohammed-Alama** [comment]
there is an error but I can't get it
![Screen Shot 2020-07-15 at 6 25 23 PM](https://user-images.githubusercontent.com/24527701/87570225-90018900-c6c8-11ea-9974-55dbcb594c5f.png)

**Comment by sschlein** [comment]
Your `toArray` method requires a request and you are providing nothing in your Tinkerwell code. This is not a Tinkerwell issue, your code shouldn't run somewhere else too ;-)
