### ISSUE TITLE
Could not open tinkerwell

### ISSUE THREAD

**Issue by manish-manghwani** [beyondcode/tinkerwell-community#255]
I am trying to install tinkerwell in ubuntu 20.04 via AppImage and it is failing with following error:

Failed to register AppImage in AppImageLauncherFS : could not open map file

![image](https://user-images.githubusercontent.com/17725637/87569285-82f29300-c6e4-11ea-83c3-c6cfa0c7ff02.png)

**Comment by sschlein** [comment]
Do you know if this is Ubuntu 20.04 only? I just tested on 18.04 and it works there.

**Comment by njames** [comment]
Hey @manish-manghwani I am on 19.10 still and use AppImageLauncher to 'install' the appimage. 

https://github.com/TheAssassin/AppImageLauncher 

HTH

**Comment by manish-manghwani** [comment]
Hey @sschlein, I am not sure about 18.04. I removed AppImageLauncher from system, reinstalled the image file for tinkerwell. 

Later i changed the permissions and just ran it as executable, it worked and haven't faced any issue since then.

**Comment by manish-manghwani** [comment]
Hey @njames, I am not sure about 19.10. 

working fine without AppImageLauncher by changing the image file into executable and running it.

**Comment by sschlein** [comment]
So if it works for you, please close this issue :)
