### ISSUE TITLE
Tinkerwell - Dont works on Windows 10 - buggy encoding message

### ISSUE THREAD

**Issue by AlexSunlight** [beyondcode/tinkerwell-community#256]
Hi! I am new buyer of Tinkerwell. 
I run the utility for the first time and see an incomprehensible message on the right.
Most likely, this message means that php is not installed in the system.
Please fix.
My operating system is Windows 10
The message is
`""php"" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.`
This is screenshot
[https://imgur.com/a/DefOjVV]

**Comment by sschlein** [comment]
If you don't have PHP installed, please install PHP and point Tinkerwell to it in the advanced settings.
