### ISSUE TITLE
Tinkerwell is not working in visual studio code

### ISSUE THREAD

**Issue by dhruva81** [beyondcode/tinkerwell-community#257]
Not working in visual studio code.

**Comment by mikeerickson** [comment]
@dhruva81 might want to provide some additional inflammation to help track down issue

- what platform (windows, Linux, Mac)
- what version of VSCode 
- what version of Tinkerwell
- what are you doing to initiate Tinkerwell in editor 
- what is the exact issue 
- are you receiving an error message

**Comment by sschlein** [comment]
I have released docs for the plugins here https://beyondco.de/docs/tinkerwell/basic-usage/ide-plugins

Unfortunately, we are likely not able to provide plugins for Linux and Windows in the same way that the plugins work for macOS. You can find more information about this in the docs.
