### ISSUE TITLE
PHP binary path not being saved between sessions

### ISSUE THREAD

**Issue by iforwms** [beyondcode/tinkerwell-community#258]
Click Settings > Advanced > Select to change the PHP binary.

Works for current session but on re-opening Tinkerwell it is back to the default (which is currently PHP 7.3.11), so 7.4 code can't run.

**Comment by mikeerickson** [comment]
Need some additional information to help debug issue: 

- what version of Tinkerwell are you using 
- what operating system and version 
- what is the full path you are using for the PHP 7.4 binary 
- what is the path to PHP binary is it resetting to

**Comment by iforwms** [comment]
**Version**: 2.8.3
**OS**:  Mac Catalina 10.15.5
**Custom Path**: /usr/local/Cellar/php/7.4.0/bin/php
**Default Path**: php

<img width="514" alt="Screen Shot 2020-07-24 at 10 32 42" src="https://user-images.githubusercontent.com/10304616/88356012-096c3c00-cd99-11ea-8c41-6e81a4fc6e57.png">

**Comment by sschlein** [comment]
This has been fixed with 2.8.4 – but has introduced a new bug that makes the PHP binary setting for SSH connections useless.

We are going to review this feature next week

**Comment by sschlein** [comment]
https://beyondco.de/docs/tinkerwell/releases/2-8-4
