### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by niladam** [beyondcode/tinkerwell-community#261]
Hello,

Since 2.6.0 i'm unable to find an up-to-date changelog.

Is there anywhere i could maybe have a look at it ?

I think **maybe** it could be integrated in the app itself or a link to it at least ?

Thanks.

**Comment by niladam** [comment]
I'm sorry. I will close this issue.

Apparently, the changelog is now located at https://beyondco.de/docs/tinkerwell (under **releases**)

**Comment by sschlein** [comment]
Sorry, updated it with a link: https://tinkerwell.app/releases

**Comment by niladam** [comment]
@sschlein thank you!:)
