### ISSUE TITLE
Tikerwell - system error - ffmpeg.dll didnt found

### ISSUE THREAD

**Issue by AlexSunlight** [beyondcode/tinkerwell-community#262]
Today I get message: Tinkerwell ready for update. Close and restart to automatic update.
So, after closing - I cant run Tinkerwell.
I get the error
```
Tinkerwell.exe - system error
"Code execution cannot continue because the system did not find ffmpeg.dll"
```
Screenshot is here (Russian)
https://imgur.com/a/SCrjTAm

**Comment by sschlein** [comment]
Can you have a look if steps of this issue help?

We seem to have an issue but we need to investigate this further.
