### ISSUE TITLE
$apiKey 

### ISSUE THREAD

**Issue by njames** [beyondcode/tinkerwell-community#263]
This blog on forge api https://tinkerwell.app/tutorials/6-consuming-http-apis-with-laravel-7-and-tinkerwell
refers to `$apiKey` but does not refer to how it got in that variable. 

There is no doco on the forge apikey on the docs site.

I am probably just missing something. 

Thanks for the great work you do and the continual updates to improve the product. :)

**Comment by sschlein** [comment]
Hey, you get the content of the variable from your Forge account. After that, you can add it in the code - it's not in the post because we don't want to show our API code 😉

**Comment by njames** [comment]
Thanks @sschlein  but it is in the advanced settings so I thought that was doing some magic to get it from there.

Can I refer to that setting somehow in a script?

**Comment by sschlein** [comment]
The post is not related to the Tinkerwell feature to get your Forge sites. It's an example how to consume APIs and Forge was used because most Tinkerwell users know it.

**Comment by njames** [comment]
Ok ... let me ask my question another way...

There is an advanced setting to store my forge api key, how can I use this setting in my scripts?

**Comment by sschlein** [comment]
You can't. The key is only used by the feature that gets your servers from the api for the ssh connection server lost.
