### ISSUE TITLE
When two people are tinkering on the same SSH connection at the same time, you get each others results back.

### ISSUE THREAD

**Issue by adrianb93** [beyondcode/tinkerwell-community#264]
When two people are tinkering on the same SSH connection at the same time, you get each other's results back.

A colleague and I were on the same server running some Tinkerwell scripts. As an example, say my colleague is querying Authors and I was querying Posts around the same time. My colleague got a Post result, and I got an Author result.

I think we were using the same temp files on the servers via Tinkerwell?

**Comment by sschlein** [comment]
Yes, that's a limitation at the moment. I'll add this as a feature request, shouldn't be that hard to add for us.

**Comment by mpociot** [comment]
This will be fixed in the next version
