### ISSUE TITLE
Tinkerwell not working with MySQL v8.0.19

### ISSUE THREAD

**Issue by mitchazj** [beyondcode/tinkerwell-community#266]
## The problem
I've been using DBngin (free utility by TablePlus) to manage all of my database installations on macOS but for some reason I can't get Tinkerwell to connect to MySQL at all. Eg,

```php
Company::first()
```
produces
```
Illuminate/Database/QueryException with message 'SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from `companies` limit 1)'
```
It throws an error like this for every model :(

Everything else seems to work fine. I have a root user, blank password auth, etc. Laravel development & migrations all work fine from the command line so I'm not sure what's going wrong here & why Tinkerwell refuses to connect.

## What I've tried
I've tried both solutions here to no avail: https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to

## Additional Context
Here's my `.env` db configuration settings (which all work completely fine with artisan etc on the command line)
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=elearning
DB_USERNAME=root
DB_PASSWORD=
```

**Comment by mpociot** [comment]
Please make sure that you have selected the correct PHP binary in your Tinkerwell settings, as this could be the issue

**Comment by mitchazj** [comment]
Huh, that fixed it. It was set to just 'php', and needed me to manually select '/usr/local/bin/php'. Thanks :)

**Comment by tylerwiegand** [comment]
For any future googlers -- I was running PHP 7.2.*, had this issue on one docker containers connection, but not another that was similarly configured. I `brew instal php@7.4` and selected that version (/usr/local/opt/php@7.4/bin) as the tinkerwell version and THAT worked.

And yes, I know I can use the docker's version, but uh...well it's complicated heh =P
