### ISSUE TITLE
[Windows] Run code shortcut doesn't work. CTRL+R reloads page instead of running code.

### ISSUE THREAD

**Issue by ryanmortier** [beyondcode/tinkerwell-community#267]
I'm using the new Microsoft Edge based on Chromium: https://www.microsoft.com/en-us/edge

Version 84.0.522.44 (Official build) (64-bit)

When I use the shortcut CTRL+R to run the code, it instead refreshes the page.

**Comment by sschlein** [comment]
Is this related to Tinkerwell web? This repository is ony flor the desktop apps.

We can't change browser reloading behavior, if it's for web.
