### ISSUE TITLE
Getting an error while sharing.

### ISSUE THREAD

**Issue by wotta** [beyondcode/tinkerwell-community#268]
The moment I want to share some code I get the following error.
I also have no idea how to see more specific information about the error.

![Screen Shot 2020-07-26 at 11 49 40 AM](https://user-images.githubusercontent.com/13332240/88476115-196d5280-cf36-11ea-9bcb-4f6532c2de8a.png)

Is there anything I can do to provide more information?

**Comment by mpociot** [comment]
I just fixed this in my current local build and I'll publish an update later today.

**Comment by wotta** [comment]
Thank you!
