### ISSUE TITLE
Add +/- buttons to SSH connection manager

### ISSUE THREAD

**Issue by sschlein** [beyondcode/tinkerwell-community#270]
Connection manager still feels a bit off. it's not clear if you are editing a current connection, how to save a new one, etc. I think a simple +/- buttons would help tremendously in that area. 

![Ed9SzL_XgAIElo4](https://user-images.githubusercontent.com/2911113/88652584-528afb80-d0cb-11ea-9cc0-c4e057ff39b2.png)

**Comment by njames** [comment]
Ohh ohh and a copy or duplicate connection button which will save you having to pick your ip or ssh key

**Comment by mpociot** [comment]
The whole SSH manager is now rewritten so this is no longer needed.
