### ISSUE TITLE
White textbox in new tab ouput

### ISSUE THREAD

**Issue by atymic** [beyondcode/tinkerwell-community#271]
I see a white textbox in new tabs, and the query output doesn't work.
It seems when opening new tabs, it breaks the query output.

![image](https://user-images.githubusercontent.com/50683531/88741581-61cd8000-d183-11ea-89b6-c6f7a80caa32.png)

**Comment by sschlein** [comment]
Interesting, I'm able to verify this on 2.8.5 on Mac

**Comment by mpociot** [comment]
This will be fixed in the next release
