### ISSUE TITLE
Keyboard shortcuts for "minimize" and "close window"

### ISSUE THREAD

**Issue by semiherdogan** [beyondcode/tinkerwell-community#272]
Hi,

I am using macOS and most of the apps that i'm using has keyboard shortcuts for "close window" and "minimize".

Minimize: CMD + m
Close Windows: CMD + w

Is there any feature plan to add these shortcuts?

**Comment by mpociot** [comment]
We'll also add support for CMD+H

**Comment by marijnbent** [comment]
For me, it's still opening the regex search/replace

**Comment by semiherdogan** [comment]
Just updated now and for me cmd + H opens search / replace too.

**Comment by jasonvarga** [comment]
I just came here to check on the status of this again. I noticed something. You only get the search/replace toolbar if you're focused within the text itself.

If you click the sidebar or tab bar first, then press cmd+h, the application hides.

Looks like whatever editor is being used it capturing the cmd+h. (You probably knew that already though)

**Comment by sschlein** [comment]
Yeah – we debate switching to another editor in Tinkerwell 3 but haven't decided yet.

You can hit CMD+H twice and this hides your window, even if you are in the editor. Not perfect, but better than clicking somewhere else first 😅

**Comment by jasonvarga** [comment]
Oh that's a good tip. Thanks!
