### ISSUE TITLE
SQL query log window not resizable 

### ISSUE THREAD

**Issue by atymic** [beyondcode/tinkerwell-community#274]
It's possible to resize between the left/right panels, but I can't resize the sql output panel.
This should be resizable, as it's tiny (even on my huge screen)
![image](https://user-images.githubusercontent.com/50683531/88890772-76923c80-d285-11ea-83a5-4ad78720a494.png)

**Comment by mpociot** [comment]
Yeah, I agree that the whole query log UI was pretty bad.
The next version of Tinkerwell will have a better implementation: https://twitter.com/marcelpociot/status/1291027008718331905

**Comment by mikeerickson** [comment]
@mpociot looking much better!  How does one go about learning out the sql statements?

**Comment by mpociot** [comment]
> How does one go about learning out the sql statements?

What do you mean?
