### ISSUE TITLE
Does tinkerwell have autocomplete function? 

### ISSUE THREAD

**Issue by khangvo88** [beyondcode/tinkerwell-community#276]
Suppose I defined multiple variables, could I use any Cmd+Enter or something like that to complete the field name. I am fine without it, but I am just curious if that feature exists ?

**Comment by sschlein** [comment]
Hey - it doesn't. We would like to add this eventually but at the moment, we have no way to add this easily.

**Comment by mpociot** [comment]
To give some more context to this:

The only really usable language server implementation that we can use is "intelephense". Other open source language servers have a really bad performance and therefore are pretty much unusable for Tinkerwell.

Unfortunately, Intelephense does not allow commercial use though.

**Comment by khangvo88** [comment]
Thanks for your response. I am very happy with the Tinkerwell right now.
