### ISSUE TITLE
Use of undefined constant JSON_INVALID_UTF8_SUBSTITUTE

### ISSUE THREAD

**Issue by haris-sabka-mandi** [beyondcode/tinkerwell-community#277]
at vendor/laravel/framework/src/Illuminate/Log/LogManager.php:416
    412|      * @return \Monolog\Formatter\FormatterInterface
    413|      */
    414|     protected function formatter()
    415|     {
  > 416|         return tap(new LineFormatter(null, $this->dateFormat, true, true), function ($formatter) {
    417|             $formatter->includeStacktraces();
    418|         });
    419|     }

**Comment by sschlein** [comment]
Hey, can you please check your PHP version in the advanced settings? I assume that this is related and Tinkerwell has detected an older version of php somewhere on your machine.

Can you confirm that you are using a mac?

**Comment by haris-sabka-mandi** [comment]
> Hey, can you please check your PHP version in the advanced settings? I assume that this is related and Tinkerwell has detected an older version of php somewhere on your machine.
> 
> Can you confirm that you are using a mac?

Hi, yes I am using Mac, and I switched from PHP 7.1 to 7.4 in advanced settings from tinkerwell

**Comment by sschlein** [comment]
Ok cool, we are going to improve this part of the application. It's a pain for everyone...
