### ISSUE TITLE
Docker, SSH and Oracle

### ISSUE THREAD

**Issue by bakanyaka** [beyondcode/tinkerwell-community#278]
Hi. I'm using tinkerwell to connect to docker container via ssh.  My laravel app has two DB connections (regular connection to postgres DB and another connection to oracle DB using https://yajrabox.com/docs/laravel-oci8/master). Regular queries run fine inside tinkerwell but oracle queries show a warning and do not produce any result. I've tried running the same code inside laravel tinker and it works fine.
Code example:
```php
// This works
DB::connection('pgsql')->table('stores')->first();

// This doesn't
DB::connection('oracle')->table('depotcards')->first();
```

Error:
```
PHP Warning:  Use of undefined constant OCI_CRED_EXT - assumed 'OCI_CRED_EXT' (this will throw an Error in a future version of PHP) in /var/www/vendor/yajra/laravel-oci8/src/Oci8/Connectors/OracleConnector.php on line 36
```

**Comment by bakanyaka** [comment]
I've tested this with recent tinkerwell beta version with docker support. Both postgres and oracle connections work fine when in docker mode.

**Comment by mpociot** [comment]
I'm going to close this in favor of the upcoming Docker support.
 I assume that this happens because of either:
- The SSH user is missing env variables?
- The PHP binary that gets used via SSH is incorrect and does not have all extensions loaded
