### ISSUE TITLE
Docker Beta Feedback

### ISSUE THREAD

**Issue by mpociot** [beyondcode/tinkerwell-community#279]
I just uploaded a beta version that has Docker support. You can access it via the Beyond Code dashboard at https://beyondco.de/login

Either log in with your existing account or using your license key.

When you open a project that contains a docker-compose.yaml/yml file, you will see a new Docker icon in the toolbar. By clicking this, you can configure which docker compose service should be used for running PHP code as well as choosing the working directory within your container (can be auto-detected).

![](https://user-images.githubusercontent.com/804684/89544046-efebdb00-d801-11ea-902c-9def18df72ee.png)

You can also disable/enable if Docker should be used for the selected project.

Please note: The beta version currently only allows using Docker while in the standard CLI tinker mode. HTTP; Table or Testing mode is not yet modified, as I want to gather some feedback first.

If you have feedback regarding the beta version, please leave it here: #279

Please provide any feedback on the Docker beta version here

**Comment by semiherdogan** [comment]
Hi Marcel,

Opened Tinkerwell then selected project that has docker.compose.yml but no docker icon in the toolbar.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/5646041/89547498-81f9e080-d80e-11ea-939e-b6ce61ca25d2.png">

Did i miss something?

**Comment by mpociot** [comment]
Is this a typo, or is the file named `docker.compose.yml`?
You might also try and open a new tab and see if it works in there (might be an issue with migrating the "existing" tabs from an older version)

**Comment by semiherdogan** [comment]
it was typo :) opened new tab and now i see docker icon and it runs as expected.
thank you so much for this product.

**Comment by semiherdogan** [comment]
Is it normal for editor to freeze.
Probably waits connection/response from docker.

You can see below:  (when i write something it freezes a little then shows what i wrote)

![Aug-06-2020 18-40-51](https://user-images.githubusercontent.com/5646041/89552449-d2743c80-d814-11ea-91f9-be17f72e6ada.gif)

**Comment by sschlein** [comment]
@semiherdogan Does that also happen if you disable auto evaluate and run manually with the shortcut?

**Comment by semiherdogan** [comment]
Tried now, it's not freezes when auto evaluate disabled.

**Comment by sschlein** [comment]
@semiherdogan ok cool, maybe that can be solved with a bigger delay for the auto-evaluation on Docker connections

**Comment by bakanyaka** [comment]
Hello. First of all, thanks for update. It solved the issue I was experiencing with ssh mode (#278). 

Some beta feedback (using windows version):

-  I'm also experiencing editor freezes when autoevaluation is enabled
-  Docker options modal size seems to be based on main window size and ends up being super small when main window is not maximized.

![2020-08-06 19_26_28-bih](https://user-images.githubusercontent.com/11876318/89557849-1f0f4600-d81c-11ea-91d9-3e8ac5b3e847.png)

**Comment by nkoporec** [comment]
Is there any support for docker/docker-compose wrappers such as [DDEV](https://github.com/drud/ddev), [Docksal](https://github.com/docksal/docksal), [Lando](https://github.com/lando/lando) ? They don't use the docker-compose.yml file directly, since they have their own config files, but under the hood, they use docker + docker-compose, so it should be pretty easy to support them.

**Comment by fabscav** [comment]
Great work adding Docker support!

I did notice, however, that executing even a simple variable assignment takes ~5 seconds, which is about twice as long as running the statement using `docker-compose exec`. It'd be great if this could be improved. Maybe even maintain a shell session within the container for even faster execution?

**Comment by pvledoux** [comment]
Not sur why but I had to reload Tinkerwell before seeing Docker icon in the toolbar after selecting the project folder.

**Comment by pvledoux** [comment]
It looks like the table mode is not working.
![Screenshot 2020-08-07 at 17 15 55](https://user-images.githubusercontent.com/167294/89660579-d2864200-d8d1-11ea-9903-59600313583b.png)
![Screenshot 2020-08-07 at 17 17 25](https://user-images.githubusercontent.com/167294/89660627-e29e2180-d8d1-11ea-958b-7487848f29bb.png)

Is it just me?

**Comment by mpociot** [comment]
> Please note: The beta version currently only allows using Docker while in the standard CLI tinker mode. HTTP; Table or Testing mode is not yet modified, as I want to gather some feedback first.

**Comment by Lubje** [comment]
Really nice, so grateful for this tool an especially this option.

Just had to copy and edit my docker-compose.yml a little because of the source folder used in some volume mounts, because I have my docker folder and the docker-compose file a level higher up than my src folder, where the Laravel application exists:

```
my-project
├── docker  
│   ├── nginx
│   │   └── ...
│   └── php  
│       └── ...
├── src
│   ├── app
│   ├── bootstrap
│   └── ...
└── docker-compose.yml
```

Any chance it would be possible to select the docker-compose.yml by hand?
Would be great for anyone not having the docker-compose file in the root of their application folder.

**Comment by a10waveracer** [comment]
Loving this new feature! I agree, though, that it would be very helpful if we could get the ability to select the docker-compose file by hand as I routinely place my docker compose file in a separate docker directory.

**Comment by Obvinyg** [comment]
For some odd reason I can't get it to work at all (even though my colleague had no problem).

Some debugging shows that the command that Tinkerwell tries to run is a `docker cp /tmp/data.txt xxxxxx:/tmp/tinker_data.txt`

This command doesn't seem to work - not even when doing it manually from the terminal. I get the error

>lstat /tmp/data.txt: no such file or directory

If I create another file `/tmp/data2.txt` and try to copy that with `docker cp` I have the same issue.

But if I create a file outside `/tmp` it works fine.

I did notice that `docker cp` has something in its documentation about now being allowed to copy from certain directories - but it does not mention anything about the /tmp directory.

>It is not possible to copy certain system files such as resources under /proc, /sys, /dev, tmpfs, and mounts created by the user in the container.

https://docs.docker.com/engine/reference/commandline/cp/

**Comment by YannickYayo** [comment]
All is working good for me on Linux Manjaro :D

**Comment by earnjam** [comment]
> Is there any support for docker/docker-compose wrappers such as [DDEV](https://github.com/drud/ddev), [Docksal](https://github.com/docksal/docksal), [Lando](https://github.com/lando/lando) ? They don't use the docker-compose.yml file directly, since they have their own config files, but under the hood, they use docker + docker-compose.

A bit +1 to this. I primarily use Lando. I bounce back and forth between Laravel and WordPress a lot and Lando makes it easy to spin up new environments quickly. 

To use Tinkerwell with Laravel I've typically been exposing an external DB connection and then changing my DB connection information in my `.env` file every time I open Tinkerwell. Not really optimal, but easier than adding SSH. It's a fantastic tool, but this drastically limits how much I use Tinkerwell day-to-day.

**Comment by basepack** [comment]
> Is there any support for docker/docker-compose wrappers such as [DDEV](https://github.com/drud/ddev), [Docksal](https://github.com/docksal/docksal), [Lando](https://github.com/lando/lando) ? They don't use the docker-compose.yml file directly, since they have their own config files, but under the hood, they use docker + docker-compose.

I am exactly in the same boat, by using Lando. I bought Tinkerwell to work with my Lando instances, but I have yet to figure out the connection between Docker and Tinkerwell unfortunately. 

So I use Tinkwell at most for 10% of my project, which, in the end, is not what I bought it for... :)

**Comment by gpressutto5** [comment]
- I think it would be much more useful if it let me type the container name instead of requiring a `docker-compose.yml` file.
- CPU usage is very high. It takes some time to eval anything.
- I had to open and close a new tab to see the docker icon.

**Comment by evertramos** [comment]
I could not really make it work...

Windows 10 Pro
Docker Desktop Version 2,3,0,4 (stable)

My inicial error were:
![image](https://user-images.githubusercontent.com/905951/92116317-103f9300-edca-11ea-80d0-2cb11c0b6ec0.png)

Then I renamed the php container and service to 'php', than the error changed to:
![image](https://user-images.githubusercontent.com/905951/92116380-23eaf980-edca-11ea-97f5-1eb66d2f3df3.png)

In the docker set up shows:
![image](https://user-images.githubusercontent.com/905951/92116461-3e24d780-edca-11ea-8be0-1e32280439ad.png)

It's a Laravel App 4.2 we are migrating to a new version... does it impact in anything?

Here is the Dockerfile for the php container in development:

```bash
#
# Temporary container for Installing Composer Packages
# 
# We used this option in order to increase 
#
FROM composer as composer
WORKDIR /app
COPY composer.json composer.json
RUN composer --no-ansi install --no-ansi --prefer-dist --no-dev --no-scripts --no-interaction --ignore-platform-reqs --no-autoloader

# 
# Application container
#
FROM php:7.0-fpm

# Install required packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    git \
    zip \
    unzip \
    gnupg \
    libxml2-dev \
    zlib1g-dev \
    libpng-dev \
    libmcrypt-dev

# Docker extension install
RUN docker-php-ext-install \
    opcache \
    pdo_mysql \
    pdo \
    mbstring \
    tokenizer \
    xml \
    ctype \
    json \
    zip \
    soap \
    mcrypt \
    gd \
    bcmath \
    sockets \
    && docker-php-source delete

# Installing Simple SMTP (ssmtp)
RUN apt-get update && \
    apt-get install -y --no-install-recommends msmtp && \
    # echo "FromLineOverride=YES" >> /etc/msmtprc && \
    # chmod 600 /etc/msmtprc && \
    echo 'sendmail_path = "/usr/bin/msmtp -t"' > /usr/local/etc/php/conf.d/mail.ini

# Development options (REMOVE FOR PRODUCTION)
RUN apt-get update && apt-get install --no-install-recommends -y \
    procps \
    net-tools \
    vim \
    iputils-ping \
    default-mysql-client \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && echo "alias l='ls -la'" >> ~/.bashrc

# Set php.ini options
RUN echo "\n \
    log_errors = On\n \
    display_errors = On \n \
    display_startup_errors = On \n \
    error_log = /dev/stderr\n \
    error_reporting = E_ALL \n \
    post_max_size = 100M\n \
    date.timezone = America/Sao_Paulo\n \
    upload_max_filesize = 100M\n \
    always_populate_raw_post_data = -1\n \
    " \
    > /usr/local/etc/php/php.ini

# Set container language
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENV TZ America/Sao_Paulo

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && apt-get remove --purge -y curl \
    && apt-get autoremove -y \
    && apt-get clean

# Define Workdir
WORKDIR /var/www

# Copy application from composer temporary container
COPY --from=composer /app /var/www

# Copy source to container
COPY . /var/www

# Create composer autoloader
RUN composer --no-ansi dump-autoload --no-scripts --no-dev --no-interaction --optimize

# Config application storage folder
RUN chown -R www-data:www-data ./var/www/storage/

# Ports Exposed
EXPOSE 9000

# Start php-fpm
CMD ["php-fpm"]
```

**Comment by pierreribault** [comment]
@khanalpride Thanx a lot ! It's perfect, just to avoid `PHP_MEMORY_LIMIT=1G` i have set `php -d memory_limit=128M` to PHP Binary in ssh configuration.

**Comment by zack6849** [comment]
Hi Marcel,

This doesn't get along with some configurations, for example, i'm using docker with WSL, and as such, my working directory is actually inside of my ubuntu machine, eg:

\\wsl$\Ubuntu-18.04\home\zack\Projects\foo

![screenshot](https://www.zcraig.me/files/5eVqM99aTWZostCqTGctKUxDF.png)

**Comment by diwms** [comment]
I really like docker feature! But would very nice to have the ability to configure what file of docker-compose is main and should be used.

In my case, the project is a bit complex and I have 3 docker-compose files:

`docker-compose-mac.yaml`
`docker-compose-win.yaml`
`docker-compose-linux.yaml`

so for now I renamed `docker-compose-mac.yaml -> docker-compose.yaml` and everything is ok.
But would be very nice to do this via Tinkerwell settings.

Thanks for docker support!

**Comment by evertramos** [comment]
@diwms and also set a path... my dockerfiles are inside _./docker_

**Comment by iatroshchenko** [comment]
@mpociot , Hello Sir! Great product, but with docker I got this kind of issue:

use App\Models\User;
User::all();

gives

PHPUnit/Framework/InvalidArgumentException with message 'Argument #1 of PHPUnit/Framework/TestSuite::addTestSuite() must be a class name or object'

what does this mean?

**Comment by awijnands** [comment]
PHPstorm plugin does not recognise the configured remote PHP CLI which is a docker container setup via docker-compose in my case. As far as I know there is also no way to specify to Tinkerwell which container to exec it's commands to.

A way to specify a container to connect to would be greatly appreciated. Something that might help is that the remote PHP CLI configuration is stored in PHP storm's config in .idea/php.xml. Below a copy of my setup.


```xml
<component name="PhpInterpreters">
    <interpreters>
      <interpreter id="299e1a71-db42-4248-b276-af230b5192c1" name="app" home="docker-compose://DATA" debugger_id="php.debugger.XDebug">
        <remote_data INTERPRETER_PATH="/usr/local/bin/php" HELPERS_PATH="/opt/.phpstorm_helpers" INITIALIZED="false" VALID="true" RUN_AS_ROOT_VIA_SUDO="false" DOCKER_ACCOUNT_NAME="Docker" DOCKER_COMPOSE_SERVICE_NAME="app" DOCKER_REMOTE_PROJECT_PATH="/opt/project">
          <type_data command="EXEC" />
          <dockerComposeConfigurationPaths>
            <item value="$PROJECT_DIR$/.infra/docker-compose.yml" />
          </dockerComposeConfigurationPaths>
          <envs />
        </remote_data>
      </interpreter>
    </interpreters>
  </component>
```

**Comment by gpressutto5** [comment]
I get this update message every time on Linux:

![image](https://user-images.githubusercontent.com/12385501/97359179-1b1f1d00-187b-11eb-86b7-ec98a1e8cb1e.png)

**Comment by oranges13** [comment]
Our project uses docker-compose overlay for different environments, at the moment we have a main compose file and then an overlay file for each environment, (e.g.):

- `docker-compose.yml`
- `docker-compose-dev.yml`
- `docker-compose-qa.yml`
- `docker-compose-prod.yml`
- etc..

Manually, we run this with the command `docker-compose -f docker-compose.yml -f docker-compose-env.yml up -d` which overlays whichever environment you need. Can't seem to get this functionality with Tinkerwell at present.

**Comment by nickpoulos** [comment]
Any updates on this feature the last few months?  No docker support is a major blocker for wider adoption

**Comment by sschlein** [comment]
@nickpoulos Docker support is available within the normal version and we have to finish the documentation for this feature – you can open a Docker project and if there is a docker-compose.yml in the project, you see a Docker icon on the left to configure it.

**Comment by Lubje** [comment]
> Really nice, so grateful for this tool and especially this feature.
> 
> Just had to copy and edit my docker-compose.yml a little because of the source folder used in some volume mounts.
> The reason for this is that I have my docker folder and the docker-compose file at the same level as the src folder, in which the Laravel application lives:
> 
> ```
> my-project
> ├── docker  
> │   ├── nginx
> │   │   └── ...
> │   └── php  
> │       └── ...
> ├── src
> │   ├── app
> │   ├── bootstrap
> │   └── ...
> └── docker-compose.yml
> ```
> 
> Any chance it would be possible to select the docker-compose.yml by hand?
> Would be great for anyone not having the docker-compose file in the root of their application.

A simple symlink in the project folder to your actual docker-compose.yml file works for this.
Just make sure that if you are using a .env for your docker-compose, you als make those variables available in the project folder.
Secondly, you probably want to gitignore the symlink.

**Comment by jacobsmith** [comment]
@zack6849 I've managed to get Tinkerwell working with wsl2 and docker.

You'll need to map your WSL2 instance as a drive mount - 
```
PS C:\Users\jacob> net use * \\wsl$\Ubuntu-20.04
Drive Z: is now connected to \\wsl$\Ubuntu-20.04.

The command completed successfully.
```

Then, from inside Tinkerwell, I set the working directory to the directory on that drive ( `Z:/home/jacob/code/MY_APP_HERE`) where the docker-compose.yml file is. For me, I'm using Laradock, so I pointed it to the Laradock folder. Then, from within Tinkerwell, I selected the container name I wanted it to run ( `workspace` for Laradock ) and then set the working directory to `/var/www` because that's where my code is mounted in that Docker container.

Hope this is able to help someone!

**Comment by amanpatel** [comment]
Just bought this product. Expected Docker support to be built in, found this thread. But I can't find beta download option within my profile page

![Screen Shot 2020-12-12 at 9 04 36 PM](https://user-images.githubusercontent.com/226976/102001984-a9315480-3cbd-11eb-859a-1727f479bd99.png)

**Comment by amanpatel** [comment]
Please note that the feature seems to be included in the current version. No need to download the beta (and beta is not available anyway). Please update the original topic/thread.

**Comment by jayenne** [comment]
Hi @jacobsmith my Tinkerwell is connecting to laradock fine. but it's throwing a DB error which I think means it;s unable to connect using my current .env settings - would you [or anyone] have an Idea why not?
`Illuminate\Database\QueryException with message 'SQLSTATE[HY000] [2002] Operation timed out (SQL: select * from `users` where `users`.`deleted_at` is null)'`

my local L8 site works/conects perfectly.
my .env settings are as required by laradock too:
```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=mydb
DB_USERNAME=myusername
DB_PASSWORD=mypassword
```

**Comment by kyryl-bogach** [comment]
Having this setup: 
![image](https://user-images.githubusercontent.com/24867662/109631670-78d3b680-7b46-11eb-8688-c8a643d609f7.png)

Everything works unless I have another terminal running `docker-compose run --rm php bash`. I believe that tinkerwell can't distinguish between the container that is up and the one I am running in my terminal. Would be great to choose in that interface the container id you want. 

Obviously, when using the terminal, Tinkerwell outputs this error:
![image](https://user-images.githubusercontent.com/24867662/109631909-bdf7e880-7b46-11eb-995f-3a551062e24d.png)

**Comment by abiggs** [comment]
Is Docker support still in beta? I've got it connected to my Docker container, but each command takes 5 seconds to complete while I look at a blue spinner.

**Comment by mpociot** [comment]
I have some Docker performance improvements that will be added to the next version. This will result in the first execution to be a bit slower, but the other ones will be faster.
As Docker support is no longer in beta, I'll close this issue.
