### ISSUE TITLE
while loop process spawning & staying alive

### ISSUE THREAD

**Issue by stevethitchman** [beyondcode/tinkerwell-community#280]
This is probably a strange one as I suspect people would want some loops to run for a very long time but anyway, initially this was just to note that do-while loops seem to cause problems with PHP processes but I did some further testing and the same will happen with while loops.

Essentially if you are in the middle of writing a while or do-while loop and it doesn't yet finish/exit it will spawn a process that will never stop (it may stop after a long time but from what I could see that wasn't the case), if you then make alterations enough that the loop will complete the process will end as expected.

The problem here at least for me was that it meant whilst I was building out the loop I ended up with a large number of PHP processes running in the background consuming more CPU and memory over time, I resolved the problem by killing these myself.

If it's helpful this was on Windows 10.
![tinkerwell-bug](https://user-images.githubusercontent.com/3201806/89740846-5e3fd000-da84-11ea-8d0e-520374f33517.jpg)

I guess one way to solve this would be to ensure all processes are killed after any given change and before a new one is spawned

**Comment by tylerwiegand** [comment]
If you're on a mac, this helped me:
```bash
ps aux | grep tinkerwell
admin            79822   0.0  0.0  4268300    716 s005  S+    2:05pm   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox tinkerwell
admin            79796   0.0  0.2  4391668  34072   ??  S     2:05pm   0:00.29 /usr/local/Cellar/php@7.2/7.2.31_1/bin/php /Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar /var/folders/db/bxjjhqdd36j4gdgny17x91cc0000gp/T/data.txt /Users/admin/code/tinkerwell null
```

then you can `cat /var/folders/db/bxjjhqdd36j4gdgny17x91cc0000gp/T/data.txt` and verify that it matches the process running you want to kill, and `kill 79796`, so you close the process and not the tinkerwell.app =)

woo!

**Comment by mpociot** [comment]
I'll close this in favor of #311
