### ISSUE TITLE
Big Sur icon

### ISSUE THREAD

**Issue by SebastiaanKloos** [beyondcode/tinkerwell-community#281]
It would be really cool to prepare an icon for Big Sur. See https://www.cultofmac.com/715717/fantastic-fugly-all-new-app-icons-macos-big-sur/.

Maybe we can add the icon to https://macosicons.com/ for beta users now. Would be really cool to receive an official app icon to clean my dock for now ;-)
![CleanShot 2020-08-11 at 11 34 46](https://user-images.githubusercontent.com/6506510/89882187-c26aad00-dbc6-11ea-848d-4cd9a6b51467.png)

**Comment by mpociot** [comment]
We'll take care of it once Big Sur gets released ;)
