### ISSUE TITLE
BAD_DECRYPT

### ISSUE THREAD

**Issue by hansv** [beyondcode/tinkerwell-community#282]
When I try to set up a ssh connection I get the following error.

<img width="441" alt="Screenshot 2020-08-19 at 17 18 04" src="https://user-images.githubusercontent.com/29959/90654251-795ace80-e240-11ea-8d08-80fc70d1b63c.png">

Any idea how this can be resolved.

**Comment by mpociot** [comment]
What kind of SSH key are you using? Check the file header, it should tell you the key type.

**Comment by hansv** [comment]
Is this the info you need:

-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,BADA7AED0A0C8F3B554ECE14FCA75899

**Comment by eckelarsson** [comment]
Get the same type of error 
![image](https://user-images.githubusercontent.com/2752093/93274035-56600380-f787-11ea-91f4-9a6521eefca5.png)

-----BEGIN OPENSSH PRIVATE KEY-----

**Comment by Pluiesurlavitre** [comment]
Encountering the same issue. Can I do anything to help you debug this ?

**Comment by mpociot** [comment]
I've updated the supported cyphers for SSL, so this should be fine in the next version.
