### ISSUE TITLE
Tinkerwell doesn't detect project framework

### ISSUE THREAD

**Issue by LordZardeck** [beyondcode/tinkerwell-community#283]
Using v2.8.5, just bought this and it doesn't autodetect any project for me. Using Lumen on some projects, Magento 2 on others. I was able to finally get it working by copying the lumen driver manually into the project using `.tinkerwell`. This is really not ideal and I work on a large number of various projects that others would not be using Tinkerwell on. Using Valet+ if that makes a difference.

**Comment by mpociot** [comment]
Yeah there's currently a problem with the Lumen and Laravel drivers, as the driver detection works the same for both frameworks. I'll see if we can specify the Lumen driver detection some more.
