### ISSUE TITLE
Installation - initial setup issue

### ISSUE THREAD

**Issue by pdep264** [beyondcode/tinkerwell-community#285]
I have just bought Tinkerwell yesterday and installed on Mac latest OS - both the Tinkerwell download and the plugin for phpstorm. Both install without issue. But thereafter anything loaded shows the error: 

[41mPHP Parse error: Syntax error, unexpected T_EXTENDS on line 1[49m

PHP v. 7.4.1 All help or suggestions gratefully received. Thank you.

Best wishes, Peter
Sent: 09h 43m on 25-Aug-2020

**Comment by mpociot** [comment]
Could you please double-check that the PHP version that is selected in Tinkerwell is correct?

**Comment by pdep264** [comment]
Hi - thx for quick response.

PHP v.7.4.1 is now selected (see clips) but still errors even after reboot:

[41mPHP Fatal error:  Class named App/Http/Controllers/Controller already exists in Psy Shell code on line 10[49m

Best wishes, Peter
Sent: 10h 08m on 25-Aug-2020

**Comment by mpociot** [comment]
Does this happen with the built in laravel app, if you have no folder selected?
Could you attach a screenshot?

**Comment by pdep264** [comment]
Does this clip help?

Best wishes, Peter
Sent: 16h 53m on 25-Aug-2020

**Comment by pdep264** [comment]
Hi Marcel:

I’m still struggling with my Tinkerwell installation. Did that error log help you any?

Best wishes, Peter
Sent: 10h 47m on 26-Aug-2020

**Comment by pdep264** [comment]
Good morning Marcel:

I had hoped to get a response to my Tinkerwell inoperability issue by now. This still persists and there’s still no sign of a solution.

I’m now beginning to feel a refund might be in order which will be a big disappointment as I had such high hopes for this software.

Thanks for your time and attention.

Best wishes, Peter
Sent: 06h 36m on 27-Aug-2020

**Comment by mpociot** [comment]
Hi Peter,

With Laracon Online taking place yesterday I didn’t have the time to look into this. Unfortunately I don’t see any attached clips / screenshots. 
Maybe try to upload them directly to GitHub instead of sending them via mail. 

Of course I can also just give you a refund if you’d prefer that.

**Comment by pdep264** [comment]
Ah, there you are. I thought it unusual you had disappeared so fast after your initial reply.  No, I would much prefer to get this working. I have great hopes for it. 

I will try to get the screen clips with the errors to you by another route. 

Best wishes, Peter

Sent By v7s

**Comment by pdep264** [comment]
**Hi Marcel (hopefully) here are this missing screen clips.**
![code](https://user-images.githubusercontent.com/59339627/91409036-1e7b3580-e845-11ea-92b3-c007f852218a.jpg)
![tink](https://user-images.githubusercontent.com/59339627/91409050-220ebc80-e845-11ea-8f40-7123ba64e435.jpg)
![phpv](https://user-images.githubusercontent.com/59339627/91409052-23d88000-e845-11ea-93ba-8c1acac0b5c3.jpg)

Many thanks for your help. Enjoy the conf.

Best wishes, Peter
Sent: 09h 10m on 27-Aug-2020

**Comment by mpociot** [comment]
Thank you for providing the PHP information. Can you somehow come up with an example project so that I can reproduce the issue?
Does this happen with all your projects or is it only in this specific one?

**Comment by pdep264** [comment]
Hello again - good to hear from you again!

Happens in all projects. At the moment I’ve given up trying with it but I’d really love to have it working.

Best wishes, Peter
Sent: 17h 15m on 07-Sep-2020

**Comment by mpociot** [comment]
Does it also happen if you create a fresh new Laravel project? 🤔 
Could you also send a screenshot of the entire php ini? It looks as if your include path holds some files by default or something like that.

**Comment by pdep264** [comment]
Marcel, I really am grateful for your efforts but I’m busy on a project. Maybe a refund is the easiest (and saddest) way out?

Best wishes, Peter
Sent: 17h 28m on 07-Sep-2020/

**Comment by sschlein** [comment]
@pdep264 Can you please email me your license key or order number for the refund to support@beyondco.de ?

Thx!
