### ISSUE TITLE
Add Query Detector to Tinkerwell for N+1 Detection

### ISSUE THREAD

**Issue by raisonon** [beyondcode/tinkerwell-community#288]
Currently I use: https://github.com/beyondcode/laravel-query-detector

It shows N+1 queries so you can fix.

It would be great to have this within Tinkerwell.

Thanks!

**Comment by mpociot** [comment]
I'll not add this in the near future. Maybe there's a way for us to add the Laravel Debugbar - but since you can tinker with *any* PHP project, this is probably too opinionated.

**Comment by raisonon** [comment]
Hmm - yeah a debugbar integration would be nice. No idea on usage, but suspect large cohort of Laravel users would find that useful. Thanks
