### ISSUE TITLE
Editor pane missing

### ISSUE THREAD

**Issue by deanzod** [beyondcode/tinkerwell-community#289]
Shortly after installing and accidentally watching the wrong file, I had to force quit. Now the editor pane seems to be gone forever. Tried restarting the mac + went through the whole menu and can't get it back. I just have the toolbar and output pane. Also tried completely removing and re-installing

**Comment by sschlein** [comment]
It looks like Tinkerwell is stuck in the watch mode. You should be able to stop it by "File --> Stop watching file" :)

**Comment by deanzod** [comment]
Only have the option to start watching. 

If you want to recreate:

Set working directory to a laravel project 
Start watching User model file
Wait for fan to go crazy and Mac to slow to almost dead 
Force quit tnkerwell

**Comment by deanzod** [comment]
@sschlein Ah thanks - I just watched a new empty php file then stopped watching and it brought things back to normal again.

**Comment by sschlein** [comment]
You are not the first one having this issue, so it's worth resetting this on app restart in a new version!

I'll reopen this and mark it as feature request :)

**Comment by mpociot** [comment]
This will be fixed in the next release
