### ISSUE TITLE
Error "Use of undefined constant JSON_INVALID_UTF8_SUBSTITUTE" when connecting to Homestead via SSH

### ISSUE THREAD

**Issue by anjabo** [beyondcode/tinkerwell-community#291]
Hi guys, 

I get the error "Use of undefined constant JSON_INVALID_UTF8_SUBSTITUTE " when I'm connected to my local Homestead environment via  SSH on Windows. What do I do wrong?

**Comment by mpociot** [comment]
JSON_INVALID_UTF8_SUBSTITUTE is only available in PHP 7.2+
Are you using this feature in the code that you tinker with and maybe use a different PHP version in Homestead?
We're not using `JSON_INVALID_UTF8_SUBSTITUTE` internally in the Tinkerwell code base.
