### ISSUE TITLE
Typing on left side nothing happens on right

### ISSUE THREAD

**Issue by nezaboravi** [beyondcode/tinkerwell-community#293]
Haven't been using it for a while and when i tried again,  i am getting nothing but blank space on the right panel.
<img width="1341" alt="Screenshot 2020-09-04 at 09 19 12" src="https://user-images.githubusercontent.com/1515172/92210929-eb155800-ee8f-11ea-9e3b-72bb7aacf12e.png">
Press Play button changes nothing
TYpe whatever you want on left hand side, changes nothing.

**Comment by sschlein** [comment]
Can you please check if Tinkerwell has deetected the correct PHP version in the advanced settings? Sounds like there is no PHP detected at all

**Comment by nezaboravi** [comment]
Okay, apparently this behaviour happens on ONE subfolder. 
SO i navigate to Projects/Website/paper and it stop working. There is a Laravel project inside.
If i navigate to another laravel project, or to directory above, it works.
Why is not working in this particular folder, what can be the cause?

**Comment by nezaboravi** [comment]
@sschlein yes, version is detected
<img width="597" alt="Screenshot 2020-09-04 at 09 29 30" src="https://user-images.githubusercontent.com/1515172/92211732-2ebc9180-ee91-11ea-975a-9fc952ec66a8.png">

**Comment by sschlein** [comment]
Honestly, I have no idea how this can happen. The project is working fine when opened in the browser?

**Comment by nezaboravi** [comment]
ONly this sundir is not working. And pretty sure i been using tinker in the very same directory couple of weeks ago.
<img width="1075" alt="Screenshot 2020-09-04 at 09 30 41" src="https://user-images.githubusercontent.com/1515172/92211887-6fb4a600-ee91-11ea-85ce-0209302d7105.png">

**Comment by nezaboravi** [comment]
@sschlein Yes project runs fine i am actively work on it, and wanted to tinker something before start coding today.

**Comment by nezaboravi** [comment]
Seems that only in the root of the project tinkerwell will not work. If i go into app folder, it works, altho throwing me errors on \App\User...
Any ideas?

**Comment by sschlein** [comment]
Not really, I haven't seen this behaviour before and so I assume something is different with this project. Either something that happens during application bootstrap or with file permissions, etc.

**Comment by nezaboravi** [comment]
Okay, found it, it was a syntax error in one file, when i fixed it tinkerwell works again.

**Comment by sschlein** [comment]
Perfect!
