### ISSUE TITLE
Latest Lumen results in call to undefined method App\Console\Kernel::bootstrap()  

### ISSUE THREAD

**Issue by bloomlive** [beyondcode/tinkerwell-community#296]
Hey

Just bought the product, ended up with this:
`$users = User::find(1);
`

resulting

```
In LaravelTinkerwellDriver.php line 24:
                                                            
Call to undefined method App\Console\Kernel::bootstrap()  
```

**Comment by mpociot** [comment]
Right now you need to create a custom Tinkerwell driver (basically copy the current Lumen driver) and use it for your project.

https://github.com/tinkerwellapp/drivers/blob/master/src/Drivers/LumenTinkerwellDriver.php

Here's how the project-specific drivers work: https://github.com/tinkerwellapp/drivers#project-specific-drivers
