### ISSUE TITLE
Feedback - Pretty PHP

### ISSUE THREAD

**Issue by georanma** [beyondcode/tinkerwell-community#298]
First off, rather enjoy Tinkerwell. It's making for a nice development flow. 

I was rather confused as to why I couldnt get the pretty php function to work at times. I finally realized, it was because of the php errors. It would be nice if there was some sort of notification indicating why it cant run.

**Comment by polbatllo** [comment]
In fact, I would raise this issue up since prettify is no longer working at all. Even with no php errors in it.
