### ISSUE TITLE
Abstract methods in traits throw exception

### ISSUE THREAD

**Issue by JasonTheAdams** [beyondcode/tinkerwell-community#299]
Greetings!

Today I found that even the presence of an abstract method in a trait breaks Tinkerwell:
```php
trait Foo {
  abstract public function breakTinkerwell();
}
```

The output gets stuck as:
```
ErrorException with message 'Trying to get property 'name' of non-object'
```

I checked to see if abstract methods within abstract classes also fails, however they work just fine:
```php
abstract class Bar {
	abstract public function doConcreteThing();  
}
```

**Comment by mpociot** [comment]
Could you give me some example code that I can throw into Tinkerwell to reproduce this?
Or does this already occur when a trait exists within the entire project?

**Comment by mpociot** [comment]
Upon further investigation, it seems like this is an issue coming from the underlying Psy Shell class, so you should open an issue on the psysh repository.
