### ISSUE TITLE
Cursor placement is wrong after resize of input/output size

### ISSUE THREAD

**Issue by BoyeMagnus** [beyondcode/tinkerwell-community#300]
Cursor placement is wrong after resize of input/output size

**Steps to reproduce:**
1. Fill out input area with some long lines of code
2. Resize then input/output area
3. Place your cursor a new place in the input code
4. Start writing 

**Version:** 2.9.0 (Has been here for at least 2-3 minor versions ago)
**Link to video:**
https://streamable.com/6bfv8r

**Comment by mpociot** [comment]
We will switch the code editor from CodeMirror to Monaco, which will fix this issue
