### ISSUE TITLE
the shortcut key on windows to inspect query doesn't works

### ISSUE THREAD

**Issue by num3r06** [beyondcode/tinkerwell-community#302]
The shortcut key for inspect query open Search and replace and not works.
I use laragon with php 7.3

**Comment by sschlein** [comment]
It's the same on Linux, we need to define an additional one that isn't captured by the editor

**Comment by Wulfheart** [comment]
I'd go with `Ctrl/Cmd + Q` or `Ctrl/Cmd + Shift + Q`. I tried it and it triggers nothing. Futhermore Q would stand for query.

**Comment by sschlein** [comment]
That quits the application, doesnt it?

**Comment by Wulfheart** [comment]
Not in Windows. I tried it.

**Comment by mpociot** [comment]
This will be fixed in the next version
