### ISSUE TITLE
Allow ⌘+W to close the whole window

### ISSUE THREAD

**Issue by bakerkretzmar** [beyondcode/tinkerwell-community#303]
Following up on #20. I know I tweeted this at you as well sorry! I figured this is probably a more useful place to put it. Thanks so much for Tinkerwell!

<kbd>⌘</kbd>+<kbd>W</kbd> closes individual tabs if you have multiple tabs open, but it doesn't close the window itself if you only have one tab (the whole window).

**Comment by marijnbent** [comment]
Together with cmd + H support, this would be great!
