### ISSUE TITLE
Docker exec error on latest version Windows 10

### ISSUE THREAD

**Issue by Thiritin** [beyondcode/tinkerwell-community#307]
Hi,

I receive a Docker exec error as soon I select the new Docker feature. Im on Windows 10 Pro, Docker WSL Mode enabled.

![image](https://user-images.githubusercontent.com/6755282/94145746-4cb75980-fe73-11ea-80cc-b9ec4f49f31a.png)
![image](https://user-images.githubusercontent.com/6755282/94145762-5345d100-fe73-11ea-926e-e8688ab452f9.png)

**Comment by mpociot** [comment]
Do you still encounter this issue in the latest version of Tinkerwell?
