### ISSUE TITLE
Transferring license between computers

### ISSUE THREAD

**Issue by ricardobarantini** [beyondcode/tinkerwell-community#308]
I want to buy this awesome app, but I have a question about transferring license between old computer to a new one. If I buy and use one license at my work computer and later I want to remove the license to reuse in another computer (I know there is two licenses) I will be allowed to do so or this license will be unusable?

**Comment by mpociot** [comment]
Hi Ricardo.

Once you bought Tinkerwell, you can login to the Beyond Code Dashboard at https://beyondco.de/login and manage your activations.
So if you get a new computer, or simply get rid of an old license activation, you can manage those yourself in the dashboard :)
