### ISSUE TITLE
Table view not working, just shows "Error" in first row.

### ISSUE THREAD

**Issue by myleshyson** [beyondcode/tinkerwell-community#309]
Hey so I just downloaded Tinkerwell and started using it over SSH with a Bedrock project. I setup a custom driver in the root of the project, and using the CLI view works great. However, when trying to use the Table view, I just see a single row that says "Error" inside. Not too sure what I need to do to get this working.

CLI View
![Screen Shot 2020-09-29 at 3 34 39 PM](https://user-images.githubusercontent.com/11747187/94607493-faf34280-0269-11eb-85dc-2e6a1513b405.png)

Table View 
![Screen Shot 2020-09-29 at 3 34 53 PM](https://user-images.githubusercontent.com/11747187/94607482-f7f85200-0269-11eb-93c8-022fd0d207c5.png)

**Comment by myleshyson** [comment]
Ah ok so I guess it needs to be a multi-dimensional array in order to work. That makes sense to me I just didn't pick that up immediately from the docs. For anyone else that runs into this here's what I had to do to show wordpress posts in the table view. It would be kind of neat if it read an array of objects too at some point!

![Screen Shot 2020-09-30 at 9 03 00 AM](https://user-images.githubusercontent.com/11747187/94688616-d8116e80-02fb-11eb-81b1-3cbe13813ea3.png)

**Comment by sloan58** [comment]
I just upgraded my license and ran into this issue and I don't understand why this hasn't been fixed since September.  Why not cast the results to an array so it displays a single line?  It should go without saying that it's a PITA to work around this.  Am I missing something?

**Comment by sschlein** [comment]
It hasn't been fixed, because there is no open issue about this and we don't run into the problem ourselves. Please open an issue (this one was closed by the author) and we'll fix it
