### ISSUE TITLE
Line editing offset

### ISSUE THREAD

**Issue by njames** [beyondcode/tinkerwell-community#310]
Sometimes when opening a new file the cursor will be writing 6 lines above. 
Once you written something it works itself out but it can be confusing. 
I wonder if it is related to the comment banner you create on save. 
I note saving several times will create several of these banners. 

php 7.4 on ubuntu 20.04 Tinkerwell latest *.10

Have others experienced this? 
Apologies if this is a dupe (I did search first)

**Comment by njames** [comment]
also these parse errors never match 
`PHP Parse error: Syntax error, unexpected ',' on line 13`

not sure how much you can do about that though :)

**Comment by mpociot** [comment]
This will be fixed in an upcoming version where we will switch CodeMirror with Monaco editor.
