### ISSUE TITLE
"Stop" command

### ISSUE THREAD

**Issue by nathanbarrett** [beyondcode/tinkerwell-community#311]
Currently the only way to kill an unwanted long running process is to quit Tinkerwell and open it up again. Some suggestions as to where to put it:

1. In the Action menu underneath Run (Cmd + Shift + S shortcut)
2. Play button icon in the top left turns into a square stop icon while tinkerwell is executing that will stop the current execution

**Comment by squatto** [comment]
If you close the tab (instead of completely quitting Tinkerwell) does the long running process die?

**Comment by nathanbarrett** [comment]
@squatto yea that could work as well. but that would require the user to copy paste what they have into another tab. not super inconvenient. it just seems like there should be some feedback as to whether the code is currently running or stopped and provide an explicit mechanism to stop any executing code.

**Comment by squatto** [comment]
@nathanbarrett I completely agree - there is definitely a need for some visual feedback of the state of things. That and a warning if you run the code, but something is already/still running.

I asked about the tab to see if you could avoid having to completely quit and reopen Tinkerwell. Having to copy/paste the code is rather annoying though, without question.

**Comment by mpociot** [comment]
https://twitter.com/marcelpociot/status/1384816428872830978

This will find its way to the next Tinkerwell release 🎉
