### ISSUE TITLE
Vapor Can't run in any environment

### ISSUE THREAD

**Issue by gborcherds** [beyondcode/tinkerwell-community#313]
Hi there,

I upgraded so I can use Tinkerwell in vapor. I get the vapor icon, it shows both my environments, I check the box to run code and every time I do, I get "The requested resource does not exist" which is what I would get if I don't specify an environment. Is there something else I should be doing that I didn't see in the video?

**Comment by robertheydenrych** [comment]
Regardless of if I select "staging" or "production", it always connects to staging

**Comment by dustingtaylor** [comment]
Having this issue as well.

**Comment by gborcherds** [comment]
@robertheydenrych this is probably because the vapor CLI defaults the selection of staging in all of its commands if you don't specify the environment. We don't have a staging environment which is probably why we can't get it to run. This is definitely a bug in that it doesn't respect the environment choice in the app. Any chance we can get help on this @sschlein

**Comment by ibrahim-mubarak** [comment]
I have the same issue here

I noticed the following behavior

Tinker Mode CLI Always connects to Staging
Tinker Mode Table Always connects to Local

**Comment by mpociot** [comment]
I just fixed this bug in version 2.10.2, which will be available in ~10 minutes.

Sorry for the inconvenience.

**Comment by sschlein** [comment]
Some users still report this, so I'm reopening this issue that we keep track of the issue.

**Comment by gborcherds** [comment]
Okay, the update 2.10.2 fixed the issue for us on all three of my vapor projects. So thank you for getting that pushed.
