### ISSUE TITLE
Screen sizing issue - Question

### ISSUE THREAD

**Issue by gmcbroom** [beyondcode/tinkerwell-community#315]
Hi, firstly great product. Question: When clicking on the "connect ssh" button the connect and close buttons on the popup window are always hidden and I need to scroll down to click on them. Is there anyway to resize this window to avoid the need to scroll?
![Tinkerwell](https://user-images.githubusercontent.com/8322303/95210899-dd7f2500-07e3-11eb-9288-6a4ed2d1928b.png)

**Comment by sschlein** [comment]
It looks like this is exactly the space that the file menu takes - this is only present on windows and needs to be removed from this view.

**Comment by oldandgrey** [comment]
Thanks

**Comment by mpociot** [comment]
This will be fixed in the next version
