### ISSUE TITLE
Empty env and core Laravel functions not found

### ISSUE THREAD

**Issue by alistairreynolds** [beyondcode/tinkerwell-community#316]
I'm having some issues with tinkerwell where it doesn't load my env config settings, and also certain Laravel core functions don't work.

If I run core php commands, they work fine:

```php
echo('hi');

=> hi
```

Also, if I use composer packages, they work fine

```php
\Illuminate\Support\Str::kebab('Hello there');

=> "hello-there"
```

However some core Laravel functionality doesn't want to work

```php
dd('Hello there');

=> PHP Fatal error:  Call to undefined function dd() in Psy Shell code on line 1
```

Also, it doesn't seem to have loaded my env settings properly. I've tried clearing config etc but to no avail.

```php
User::find(1);

=> [!] Aliasing 'User' to 'App\Models\User' for this Tinker session.
PHP Error:  Call to a member function connection() on null in /Users/alistairreynolds/projects/main/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1344
```

```php
env('DB_DATABASE')

=> null
```

Am I missing something obvious? I'm using the correct php binary of `/usr/local/bin/php`, which is the same as I get when I run `which php`

Thanks

**Comment by mpociot** [comment]
Make sure to clear any potential application/configuration caches if this error occurs. That fixed it for me
