### ISSUE TITLE
Set Working Directory not working in Ubuntu 18.04

### ISSUE THREAD

**Issue by gauravmak** [beyondcode/tinkerwell-community#319]
I have tried setting the working directory from the left sidebar as well as the top navbar but no luck. It just stays as a fresh Laravel 8 app. Any way to debug?

Thanks.

**Comment by mpociot** [comment]
Could you verify that this still does not work with the latest version of Tinkerwell?

**Comment by gauravmak** [comment]
Yes, it is happening in v2.12.1

> We have quite a lot of Linux Tinkerwell users, so I'm assuming it's something related to your setup.
That's what I guess it could be but not sure how to debug.

**Comment by mpociot** [comment]
Could you try running Tinkerwell through the Terminal and see if there is any output in the console?

**Comment by gauravmak** [comment]
![Screenshot from 2021-04-07 19-10-09](https://user-images.githubusercontent.com/11887260/113876299-3a7c8780-97d5-11eb-80ac-a1c3bbaa1333.png)

@mpociot

**Comment by novecentonove** [comment]
> Could you try running Tinkerwell through the Terminal and see if there is any output in the console?

Well, I had the same issue. I fixed running Tinkerwell from Terminal,  I can now set Working Directory. (before the application quits unexpectedly)  I'm using Ubuntu 20.10.

**Comment by mpociot** [comment]
This should be fixed with the latest version (2.13.0)
