### ISSUE TITLE
Can't configure vapor on Windows

### ISSUE THREAD

**Issue by shaffe-fr** [beyondcode/tinkerwell-community#320]
Hi,
When I click on the vapor icon in the sidebar, the following error messages shows up:
>C:\Users\Karel\AppData\Local\Programs\Tinkerwell\resources\tinkerwall\vapor.phar
>This file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default Apps Settings page. 

I didn't find `.phar` in the Default Apps Settings page. What can I do?
Thanks

**Comment by P-James** [comment]
@shaffe-fr I had the same issue, you need to set php.exe to open .phar files.
Run `php -i` to check where your php is installed.

But now I have another problem since doing this, Tinkerwell isn't finding my vapor environments...

**Comment by shaffe-fr** [comment]
@P-James, I ended up with the same result as you, the environment dropdown doesn't contain mine but only `for`. 
Thanks

**Comment by shaffe-fr** [comment]
Is there any way to debug the output of the command executed on vapor.phar to list environments?

**Comment by mpociot** [comment]
This will be fixed in the next version of Tinkerwell.

**Comment by johnymahony** [comment]
> This will be fixed in the next version of Tinkerwell.

Hello. And when the version will be available for download? I bought Tinkerwell yesterday to debug our Vapor application, but I'm having the issue described above. Thank you.

**Comment by shaffe-fr** [comment]
@johnymahony in the mean time, I change the config vuex.json file in appdata to enable vapor and use the right environment. The file must be changed when tinkerwell is not running.
