### ISSUE TITLE
Warning: Use of undefined constant TINKERWELL_HOME_PATH

### ISSUE THREAD

**Issue by ksidibe** [beyondcode/tinkerwell-community#322]
**OS**: MacOs Catalina 10.15.6 (19G2021)
**PHP**: 7.2.34
I downloaded and install the MacOs install.
When I open Tinkerwell and type in valid Laravel or PHP instruction, it is not executed. And I get a warning with a long trace that says:
<code> Warning: Use of undefined constant TINKERWELL_HOME_PATH - assumed 'TINKERWELL_HOME_PATH' (this will throw an Error in a future version of PHP) in phar:///Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar/src/Drivers/TinkerwellDriver.php on line 44
Call Stack:
    0.0090     720776   1. {main}() /Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar:0
    0.0224    1078024   2. require('phar:///Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar/index.php') /Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar:14
    0.0261    1445568   3. TinkerwellDriver::detectDriverForPath() phar:///Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar/index.php:42
=> "/private/var/xxxx/yyyy/app"
</code>
Thanks for the help resolving this issue.

**Comment by mpociot** [comment]
Could you please check if the error still exists for you with the latest version of Tinkerwell?

**Comment by mpociot** [comment]
I'll close this due to inactivity, if the error still occurs feel free to reopen this issue.
