### ISSUE TITLE
Cannot Update on Mac

### ISSUE THREAD

**Issue by hcancelik** [beyondcode/tinkerwell-community#323]
I'm still having this issue and it actually never got fixed.

I get a notification "A new update is ready to install" notification but the app doesn't get updated on exit. The only way to update the app is to re-download it.

**Comment by njames** [comment]
I also have this issue on Ubuntu 20.04. I also have to download the new update. Not the end of the world ... def in NTH category.
Have a great day

**Comment by hcancelik** [comment]
Deleting `~/Library/Caches/de.beyondco.tinkerwell.ShipIt/` folder helped me resolve this issue.
