### ISSUE TITLE
issues since updating to 2.10.2

### ISSUE THREAD

**Issue by vesper8** [beyondcode/tinkerwell-community#324]
This was working perfectly previously, but now when I try to execute code in my local environment instead of printing true.. and working.. I am now getting

```
Class 'App/User' not found in Psy Shell code on line 6
```

And when trying to execute code through SSH, I get no feedback at all and nothing happens

**Comment by vesper8** [comment]
It would be helpful if there was a way to downgrade to a previous version using the file menu in Tinkerwell

**Comment by vesper8** [comment]
Or at the very least let us download previous versions on https://beyondco.de/licenses/tinkerwell

Right now I am completely stuck with no working Tinkerwell

**Comment by vesper8** [comment]
Luckily the `Tinkerwell-2.9.0-beta.dmg` is available for download and doesn't have this problem

But now the problem is that there is no way to disable "Auto-updates" .. please add a checkbox to disable auto-updates

**Comment by sschlein** [comment]
We are working on a system to display all old versions. For the moment, you have to guess the link by using the current download link and replacing it with an older version number.

Tinkerwell has no flag to disable to auto upter yet so every old version will still download the newest version and install it on next start :(

**Comment by mpociot** [comment]
@vesper8 Can you give me some details about how to reproduce this problem?
I don't see why this could be broken in the latest version

**Comment by vesper8** [comment]
@sschlein @mpociot it wasn't working earlier, but after installing 2.9.0-beta, and then from there reinstalling 2.10.2 from the `.dmg` installer, then now everything is working again.

Sorry can't say why it wasn't working earlier.. I haven't rebooted or done anything on my side, just reinstalling it did the trick
