### ISSUE TITLE
Add option to enable soft wrap

### ISSUE THREAD

**Issue by marijnbent** [beyondcode/tinkerwell-community#328]
It would be great to have the option to enable soft wrap for both the editor as the output, as now you often need to scroll if you encounter an error.

How PHPStorm implemented it:
![gif phpstorm](https://media3.giphy.com/media/Hrl1ISYm7kH9S8UGvK/giphy.gif)

**Comment by marijnbent** [comment]
My bad, apparently I was still running 1.2.0 (which is weird, I downloaded it fresh last week). Anyways, the new version looks shiny and the word-wrap feature works perfectly. Thanks for the great product @mpociot and Sebastian :-)!

**Comment by marijnbent** [comment]
HOLY SHIT! Love the share function 🤩

**Comment by sschlein** [comment]
We are actually thinking of removing it because there have only been ~250 shares (public + private) since the release and maintaining it forever for this small use case might slow down feature development on other ends 🙈

(not decided yet)

**Comment by marijnbent** [comment]
I get it. I don't see many situations in which I would use it myself, but the execution is done 👌🏻
