### ISSUE TITLE
Table view displays results on wrong tab

### ISSUE THREAD

**Issue by nm777** [beyondcode/tinkerwell-community#329]
Version: 2.10.2
OS: macOS Catalina 10.15.7

To Reproduce:
1. Put the following code in the first tab in Tinkerwell:
```
[
  ['name' => 'row 1', 'description' => 'Tab 1'],
  ['name' => 'row 2', 'description' => 'Tab 1'],
  ['name' => 'row 3', 'description' => 'Tab 1'],
  ['name' => 'row 4', 'description' => 'Tab 1'],
  ['name' => 'row 5', 'description' => 'Tab 1'],
];
```

2. Switch to table mode and run the code to see the results.
![image](https://user-images.githubusercontent.com/19784999/98026763-3cc75980-1dd1-11eb-87bc-70979f0b1897.png)

3. Add another tab and paste this code into the second tab (Note that the descriptions are different):
```
[
  ['name' => 'row 1', 'description' => 'Tab 2'],
  ['name' => 'row 2', 'description' => 'Tab 2'],
  ['name' => 'row 3', 'description' => 'Tab 2'],
  ['name' => 'row 4', 'description' => 'Tab 2'],
  ['name' => 'row 5', 'description' => 'Tab 2'],
];
```

4. Switch to table mode and run the code to see the results. Note that no results appear in the table view.
![image](https://user-images.githubusercontent.com/19784999/98026707-26b99900-1dd1-11eb-8754-585035c0d772.png)

5. Go to the first tab and note that the results from the second tab appear in the table view.
![image](https://user-images.githubusercontent.com/19784999/98026563-f07c1980-1dd0-11eb-972a-6b2dcbcc9f53.png)

Note: If you go to the first tab and switch to CLI mode, the results begin appearing as expected on the second tab.

**Comment by julianstark999** [comment]
Same issue with
Version 2.12.1 (2.12.1)
OS: macOS Big Sur 11.2.1

**Comment by tylerwiegand** [comment]
This may be related: if you run an HTTP request for instance (something that takes a few seconds) and switch tabs before the results, your results show up in the active tab rather than the tab you started in.

**Comment by mpociot** [comment]
This will be fixed in the next version :)
