### ISSUE TITLE
Yubi key: Remove username and password as required fields when connecting via ssh

### ISSUE THREAD

**Issue by nckrtl** [beyondcode/tinkerwell-community#330]
For ssh access to my production servers I'm using a yubi key. With applications like Tableplus and Transmit I can connect to the production servers without specifying a username or a password. This is because I use a hostname which I have configured ~/.ssh/config which takes care of the authentication process.

Currently I'm not able to connect via ssh through Tinkerwell in a similar way because the username and password field is required. I understand I could make a plain ssh key as a workaround but I prefer connecting with my Yubi key. So this is actually a feature request.

**Comment by sschlein** [comment]
Hey @nckrtl - the password field is not required if you are using SSH.

We do have an open feature request for using the ssh/config but it's not on the short term rroadmap yet: https://github.com/beyondcode/tinkerwell-community/issues/14

Closing this with reference to #14
