### ISSUE TITLE
Model and Collection data not displaying after upgrading to Lumen 8

### ISSUE THREAD

**Issue by D144** [beyondcode/tinkerwell-community#333]
I upgraded my project to Lumen 8, and now Tinkerwell does not show the actual data in models or collections.

For example, if I run this command:
`User::first()`

I get this result:
`
=> App\User {#2106
     +incrementing: true,
     +exists: true,
     +wasRecentlyCreated: false,
     +timestamps: true,
   }
`

**Comment by mpociot** [comment]
It seems like the default casters are no longer part of Laravel. You should be able to add them back by requiring `laravel/tinker` in your Lumen project.

```
Collection::class => 'Laravel\Tinker\TinkerCaster::castCollection',
Model::class => 'Laravel\Tinker\TinkerCaster::castModel',
```
