### ISSUE TITLE
Will it be available in codeigniter4?

### ISSUE THREAD

**Issue by Terrorboy** [beyondcode/tinkerwell-community#334]
I think it is difficult to officially support codeigniter4, but seeing PHP support displayed on the official site, I would like to ask if it can be used in codeigniter4.

**Comment by sschlein** [comment]
Should work, if you create a custom driver, you can bootstrap the required classes for the framework:
https://tinkerwell.app/tutorials/3-how-to-write-a-custom-tinkerwell-driver

You can have a look at examples of drivers at the official driver repository.

In case you buy Tinkerwell and you can't make it work and want a refund, you can email us :)

**Comment by Terrorboy** [comment]
@sschlein Thank you very much

**Comment by Terrorboy** [comment]
https://github.com/tinkerwellapp/drivers/pull/43
