### ISSUE TITLE
ParseError syntax error, unexpected ')'

### ISSUE THREAD

**Issue by ChinwalPrasad** [beyondcode/tinkerwell-community#335]
Hi,

Started getting the error below all of a sudden.

**Tinkerwell Version: 2.10.2**
**OS: MacOS Big Sur 11.0.1**

Attached Image:
<img width="1436" alt="Screen Shot 2020-11-14 at 10 43 19 PM" src="https://user-images.githubusercontent.com/40767861/99164294-d7c20c80-26ca-11eb-894a-c8bcb5a8fb36.png">

Error:
```php
   ParseError 

  syntax error, unexpected ')'

  at vendor/laravel/framework/src/Illuminate/Bus/BusServiceProvider.php:51
     47▕             return new DatabaseBatchRepository(
     48▕                 $app->make(BatchFactory::class),
     49▕                 $app->make('db')->connection(config('queue.batching.database')),
     50▕                 config('queue.batching.table', 'job_batches'),
  ➜  51▕             );
     52▕         });
     53▕     }
     54▕ 
     55▕     /**

      [2m+1 vendor frames [22m
  2   [internal]:0
      Composer\Autoload\ClassLoader::loadClass("Illuminate\Bus\BusServiceProvider")

      [2m+4 vendor frames [22m
  7   phar:///Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar/src/Drivers/LaravelTinkerwellDriver.php:24
      Illuminate\Foundation\Console\Kernel::bootstrap()
```

Thanks in advance.

**Comment by subdesign** [comment]
Had the same error, changed Laravel to 7.0 in the Preferences, and now it works.

<img width="672" alt="Screenshot 2020-11-24 at 10 42 09" src="https://user-images.githubusercontent.com/691695/100076721-cfdc3800-2e41-11eb-85dc-5bbaedc645d4.png">

**Comment by sschlein** [comment]
@ChinwalPrasad does this solve your issue, too?

**Comment by ChinwalPrasad** [comment]
@subdesign Thanks a lot 😄 That solved it. @sschlein closing the issue.
