### ISSUE TITLE
Output Vapor

### ISSUE THREAD

**Issue by marijnbent** [beyondcode/tinkerwell-community#336]
When running a command in Tinkerwell, the output is different than what I'm used to. Is the output in this snippet the correct one?
https://tinkerwell.app/shares/marijnbent/25ed026d-4cd3-44dc-b995-29b9429b4df2

**Comment by anthonytp** [comment]
I get the same results as you in the CLI tinker mode but if I switch to Table (menu item `Tinker Mode | Table`) I see data coming from the Vapor server.

However, any nested objects in the query are not displayed in the table view, making it of limited value as I can go straight to our database if I want to look at tabular data.

**Comment by telkins** [comment]
I'm not sure I'm experiencing the same thing, but it sure seems like it is.

When I execute the following:
```php
$user = User::first();

dump($user);
```

I get the following output:
```
{"output":"[!] Aliasing 'User' to 'App\\Models\\User' for this Tinker session.\nApp\\Models\\User {#4922\n  #fillable: array:3 [\n    0 => \"name\"\n    1 => \"email\"\n    ..."
```

I'm on 2.11.0 and I tried switching between modes, but nothing seemed to help.  😢

**Comment by adrian-webgurus** [comment]
We have the same issue. One project is working fine but in the other, we are getting a JSON output like the above example, even we are dumping or echoing a string. Did you find what can cause this issue? @mpociot

**Comment by marijnbent** [comment]
Any update on this bug yet?
![image](https://user-images.githubusercontent.com/11903095/106292630-56036900-624d-11eb-9b99-97504077a70d.png)

**Comment by mpociot** [comment]
Can you tell me the vapor-core versions that you have installed?
It's working on my project, so I'm having a hard time reproducing this error.

**Comment by anthonytp** [comment]
I have vapor v1.12.1 and Tinkerwell v2.12.1
And now, it works! Sort of...

When using Tinkerwell locally you can request a model and you get the attributes listed in the output window. But when I run a query against the vapor server I get no output unless I `print` or `var_dump` a variable. So it's the difference between  running this locally

```
use App\Booking;
Booking::find(10);
```

and getting the model displayed in the right panel, to having to do this when running against the vapor server

```
use App\Booking;
$b = Booking::find(10);
var_dump($b);
```

But the output format of `var_dump` is nowhere near as good as the stand CLI output :(

I would like it if the formatting worked the same locally as well as when running on the vapor server (if that is possible!?)

**Comment by telkins** [comment]
Seems to be working now, although it behaves a little differently than in other contexts.

I'm on Tinkerwell 2.12.1 now and here's my current `vapor-core` info: `laravel/vapor-core v2.10.2`.

I know Tinkerwell version was 2.11.0 before when it wasn't working, but I can't say what version of `vapor-core` I was on.

**Comment by telkins** [comment]
FYI, when I say that "it behaves a little differently than in other contexts", I'm basically talking about the differences in behavior that @anthonytp mentioned. 🤓

**Comment by mpociot** [comment]
Yeah, that's the behavior given by Vapor and I can't do much about it. But good to know that it's working again!
