### ISSUE TITLE
Laravel Zero and Models

### ISSUE THREAD

**Issue by Krato** [beyondcode/tinkerwell-community#337]
When using Laravel Zero and Models a simple `Model::first()` is giving me that error:

```
PHP Error:  Call to a member function connection() on null in /Users/ericlagarda/sites/peronda-crawler/vendor/illuminate/database/Eloquent/Model.php on line 1492
```

My code on Tinkerwell

```
use App\Models\Line;

Line::first();
```

**Comment by mpociot** [comment]
I haven't tried using Tinkerwell with Laravel Zero before, so you might need to create your own custom driver to properly bootstrap the CLI application before Tinkerwell can access everything.

https://github.com/tinkerwellapp/drivers
