### ISSUE TITLE
can't terminate process on ssh server after it's run

### ISSUE THREAD

**Issue by aemaddin** [beyondcode/tinkerwell-community#338]
I was trying to apply a script into my ssh server, and I figure out it's too heavy, so I decide to terminate the process by disconnect from ssh server and exit Tinkerwell, but the process still running on background.

So how I can terminate the process?

**Comment by sschlein** [comment]
You actually can't. If you add the script to a PHP file on the server and run the file, it keeps running, even if you close the browser.

The only way would be to kill the process on the server/restart PHP.
