### ISSUE TITLE
macOS - Set working direcotry with "app" ending

### ISSUE THREAD

**Issue by fabricecw** [beyondcode/tinkerwell-community#339]
We're unable to open a Laravel project with a ".app" ending on macOS since it's recognized as a macOS app. Normally, we're allowed to open the folder with a right click -> "Show package contents". But in Tinkerwell, the "Set working directory" Finder just greyed these folders out with no possibilities to select it.

Maybe I miss something in the settings... Thanks for your help.

**Comment by sschlein** [comment]
We actually haven't found a way to do this and renamed our tinkerwell.app website directory to tinkerwell-app ...

**Comment by fabricecw** [comment]
Hi Sebastian

Thanks for your fast answer.
Okay, was wondering how you do it with tinkerwell.app. I will also rename them.

**Comment by sschlein** [comment]
Yeah, annoying, but no idea how to fix that – and I think that there are more important things that we can work on to make the app better. If this is ok for you, would you close the issue?

**Comment by fabricecw** [comment]
Totally with you - renaming the folder and relink it with Valet is not that hard. :-) Danke und Gruss
