### ISSUE TITLE
Undo shortcut is closing tab instead of undoing change on french keyboard

### ISSUE THREAD

**Issue by desaintflorent** [beyondcode/tinkerwell-community#340]
I'm using the Wonderfull Tinkerwell app since April and always had a very annoying bug.
I thought it would be fixed by now, but it's still there with last version ( 2.10.2 ).

First this bug only happened when I have multiple tab open in tinkewell.
Then if I hit undo shortcut : CMD-Z , the current tab is closing instead of undoing the last change of the current tab...
It's pretty annoying because as you can imagine I use undo a lot so I always loose everything.

More info :
- I have a french AZERTY keyboard set on "Français - numérique" ( 123 )
- If I do undo from the textual menu it's working well even with multiple tab open.
- If I don't have tab open, CMD-Z is working perfectly well

Let me know if you have any questions

**Comment by sschlein** [comment]
This is related to a 3rd party library that we are using:
https://github.com/parro-it/electron-localshortcut/issues/99

I am aware that this is not a solution and annoying – but at least this is the underlying issue.

**Comment by psaikali** [comment]
Hey there, any ETA on a fix for this? It's getting quite annoying to use the app haha 😆

**Comment by AlexisSerneels** [comment]
https://github.com/beyondcode/tinkerwell-community/issues/361

**Comment by AlexisSerneels** [comment]
Fixed with latest release; Thank you for your work.
