### ISSUE TITLE
ErrorException "Composer/InstalledVersions"

### ISSUE THREAD

**Issue by n8udd** [beyondcode/tinkerwell-community#342]
Tinkerwell was working fine for me literally 15 minutes ago, and I got a prompt that an update was available. 

I've had to FC it, re-opened and now I'm getting the following message.

<img width="987" alt="image" src="https://user-images.githubusercontent.com/2293192/100466129-543fec80-30c8-11eb-9e78-612279129b35.png">

Literally nothing has changed on my machine, except presumably the version of Tinkerwell.

It's now on `Version 2.10.3 (2.10.3)`

**Comment by sschlein** [comment]
Could you please re-select your correct PHP binary in the settings, even if the correct one is shown?

**Comment by n8udd** [comment]
> Could you please re-select your correct PHP binary in the settings, even if the correct one is shown?

Just done this and I'm still getting the same error.

**Comment by n8udd** [comment]
Uninstalled from my machine and reinstalled `2.10.2` from Brew Cask, and it's working fine again, except now I'm being tld there's an update available.

Why isn't there an option to disable auto-updates?

**Comment by sschlein** [comment]
Because we haven't implemented it yet ... it's high on our priority list because it's an easy workaround for issues like yours.

**Comment by stubbo** [comment]
I have started having the same issue after updating, tried setting the php binary as you mentioned and didnt fix it.

For me it only breaks when using remotely via ssh, perfectly fine local

**Comment by sschlein** [comment]
Which PHP Versions do you use local/remote?

**Comment by n8udd** [comment]
> Which PHP Versions do you use local/remote?

I'm getting the issue when trying both local and remote.

**Comment by stubbo** [comment]
remote above local
[php7.4](https://stubbos.bigfat.wang/qkgrqz)

**Comment by sschlein** [comment]
Does it matter which code you run?

**Comment by sschlein** [comment]
I found a server where I can reproduce the issue! I doubt that we'll be able to deploy a fix until Monday but this might give us extra time to add the "Disable auto-updater" feature too.

**Comment by RicardoRamirezR** [comment]
@sschlein additionally ton Disable auto-updater, will be nice a "Revert to previous version" since I updated and got the error, so, with that option I can revert to the working one.

**Comment by sschlein** [comment]
@RicardoRamirezR I would either improve our process that we don't need that ..

**Comment by stubbo** [comment]
It seems to be fixed for me now :)

**Comment by sschlein** [comment]
Yes, we've fixed it with 2.11 a few moments ago
