### ISSUE TITLE
Class not found due to namespace being incorrect

### ISSUE THREAD

**Issue by wsamoht** [beyondcode/tinkerwell-community#343]
**Issue**
I am getting a `class not found` error when trying to run the following code. For some reason Tinkerwell is adding an extra `Carbon` in the namespace path.

*Code*
```php
use Carbon\Carbon;
use Carbon\CarbonInterval;

Carbon::now();
CarbonInterval::create('P1D');
```

*Output*
```
PHP Fatal error:  Class 'Carbon/Carbon/CarbonInterval' not found in Psy Shell code on line 5
```

Reversing the `use` statements does work.
```php
use Carbon\CarbonInterval;
use Carbon\Carbon;

Carbon::now();
CarbonInterval::create('P1D');
```

**OS**
- Linux Mint 20 (Ubuntu 20.04)

**Tinkerwell versions**
- 2.10.2 (I started using Tinkerwell on this version)
- 2.10.3

**Comment by sschlein** [comment]
It does work if you run it like this:

```
Carbon\Carbon::now();
Carbon\CarbonInterval::create('P1D');
```

**Comment by wsamoht** [comment]
Thanks for looking into this. I know that using the full namespace works but it is definitely more convenient to use `use` statements when tinkering with quite a bit of code at the same time. Are `use` statements not meant to be used in Tinkerwell?
