### ISSUE TITLE
Release Notes? 

### ISSUE THREAD

**Issue by njames** [beyondcode/tinkerwell-community#345]
I couldn't see any release notes :eyes:  as in installed 2.10.3 this morning. 

I found some on the website https://beyondco.de/docs/tinkerwell/releases/2-10-0 but nothing related to the minor versions 
 https://beyondco.de/docs/tinkerwell/releases/2-10-3

Would it be possible to link from the download page ( https://beyondco.de/licenses/tinkerwell )  so we know what treats we are in for?

**Comment by sschlein** [comment]
We just deployed 2.11 and added the release notes. 2.10.3 was a "small fix to support php8" that broke something else. Deployed on a Friday, we're sorry..

**Comment by njames** [comment]
All good @sschlein .. appreciate all the great work you do. Sending you virtual high 5's
