### ISSUE TITLE
Ctrl+T shortcut to open a new tab does not work on Windows (if cursor is focused in editor)

### ISSUE THREAD

**Issue by nickturrietta** [beyondcode/tinkerwell-community#348]
I am on Windows 10 and running Tinkerwell v2.11.0.

CTRL+T will not open a new tab (if my cursor is focused in the editor pane).

If my cursor is focused in the editor pane, then CTRL+T will just transpose the 2 characters under the cursor.

I have to click outside the editor pane in order to get CTRL+T to open a new tab.

![screencap](https://user-images.githubusercontent.com/6426374/100797752-7c389400-33d7-11eb-89cb-ea85f1da8999.gif)

**Comment by mpociot** [comment]
This will be fixed in the next version
