### ISSUE TITLE
Tinkerwell not detecting vapor environments

### ISSUE THREAD

**Issue by P-James** [beyondcode/tinkerwell-community#349]
I get the following for choices of environments on Windows.
Previously it didn't work at all because I hadn't associated .phar files with php.exe, since doing that, this bug shows.
Is it possible that .phar files should be opened with something else in the context of Tinkerwell?

![image](https://user-images.githubusercontent.com/51275753/100901996-5cc76700-34bc-11eb-8605-316e4dd6aac0.png)

**Comment by luigel** [comment]
I also get this options in a windows environment.

**Comment by notomato** [comment]
This is happening on Mac as well - I can only see one environment but we have over 10.

**Comment by P-James** [comment]
@luigel  @notomato  Are either of you using Laragon?

**Comment by mpociot** [comment]
I changed how the Vapor environment detection works, and this will be rolled out in the next version 👍

**Comment by P-James** [comment]
@mpociot awesome, thanks Marcel!
