### ISSUE TITLE
Feature request: default folder or startup folder

### ISSUE THREAD

**Issue by njames** [beyondcode/tinkerwell-community#351]
The tinkerwell driver is a powerful feature and make tinkerwell really powerful. 

Would be possible to add a start up folder or default folder setting so that all windows start with that directory / folder loaded and hence loading that tinkerwell driver? 

Thanks so much for all you do.

**Comment by mpociot** [comment]
Yeah, a couple of people mentioned this already, so I think this is a cool idea.

I would probably add this to the settings, so that you can configure what you want to happen when you open a new tab.

**Comment by mpociot** [comment]
This will be added to the next version of Tinkerwell!
