### ISSUE TITLE
Call to undefined method Psy/Shell::getLastExecSuccess()

### ISSUE THREAD

**Issue by techguydev** [beyondcode/tinkerwell-community#357]
I am having this problem if I try to run any command on tinkerwell

PHP Error:  Call to undefined method Psy/Shell::getLastExecSuccess() in phar:///Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar/index.php on line 99

**Comment by sschlein** [comment]
Most of the time this is related to an incorrect PHP binary in the settings – or you can try selecting the starter project with Laravel 8 and 7 a few times to reset this.

Selecting the PHP binary again also does the trick for some people.

Please let me know if this helps.

**Comment by frogeyedman** [comment]
Same problem here, happens on a remote vagrant connection. Running php 7.4.8 and Laravel 5.6.12

**Comment by federicocorsaro** [comment]
Same problem. Remote instance running on php 7.2 and Laravel 5.6.23
I remember that the previous version of tinkerwell ran without problems

**Comment by mpociot** [comment]
This will be fixed in the next version of Tinkerwell 👍
