### ISSUE TITLE
Sail

### ISSUE THREAD

**Issue by gtamasmolnar** [beyondcode/tinkerwell-community#358]
Hi Marcel,

I'm using 'Sail' which is fantastic. But I have no idea what settings I have to apply in tinkerwell.
I have not found anything in the docs. I might have looked at the wrong place, I don't know.

I'm using version 2.11.0
Thanks in advance.

**Comment by mludi** [comment]
Hi @gtamasmolnar,
if you open a Laravel Project including a docker-compose.yml, it will autodetect it in the sidebar.

<img width="391" alt="Bildschirmfoto 2020-12-14 um 10 11 04" src="https://user-images.githubusercontent.com/2865361/102062221-b866ee00-3df4-11eb-866b-8c1c294ba205.png">

Click this icon and enable Docker by "Use Docker" checkbox.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/2865361/102062278-c9176400-3df4-11eb-89dc-0552377f66e3.png">

Then choose your right service and let autodetect the working directory.

**Comment by sschlein** [comment]
Thank you @mludi – we are adding this to the docs later today.

**Comment by gtamasmolnar** [comment]
Thank you @mludi and @sschlein .
It's working! Fantastic :-)
