### ISSUE TITLE
Cmd+Z closes window

### ISSUE THREAD

**Issue by klaasgeldof** [beyondcode/tinkerwell-community#361]
When I press Cmd+Z to undo, the undo action happens, but at the same time the window closes. The application is still open, so when I click the icon in the dock, it's back in the correct (undone) state.

I guess it has to do with my Azerty keyboard, where W and Z are switched in comparison with Qwerty keyboards.

**Comment by AlexisSerneels** [comment]
Same here. AZERTY layout.

**Comment by AlexisSerneels** [comment]
This is not a same bug you can avoid. Imagine having your IDE minimizing every-time you hit undo.
That's where we are now.
Unusable.

**Comment by mpociot** [comment]
For reference, this is the issue causing this: https://github.com/parro-it/electron-localshortcut/issues/99
As well as https://github.com/electron/electron/issues/19747

**Comment by AlexisSerneels** [comment]
Fixed with latest release; Thank you for your work.
