### ISSUE TITLE
PHP Version is shown as `PHP is not recommended` on MacOS

### ISSUE THREAD

**Issue by ya-cha** [beyondcode/tinkerwell-community#364]
On MacOS Big Sur, if you go in to the advanced settings, the value of `DETECTED PHP Version` is 
```
WARNING: PHP is not recommended
```
Selected binary is `/usr/bin/php`

The message is generated by the OS itself. https://twitter.com/GrahamJCampbell/status/1295111982924861442

**Comment by mpociot** [comment]
Yeah, pretty unfair of Big Sur, isn't it?
We will filter that text out so no PHP dev is going to see this 🕵️
