### ISSUE TITLE
Did Christmas just come 2 days early? 

### ISSUE THREAD

**Issue by njames** [beyondcode/tinkerwell-community#366]
I just got a popup in my IDE that the tinkerwell plugin was due to update. 

So I updated and what?! Tinkerwell now works in PHPStorm. 

Thanks very much for that. 

I did notice that my tinkerwell electron and phpstorm plugin both use a license even though they are on the same machine. 

Anyway ... Thanks for all the updates in 2020 and here's to a excellent 2021. 

Cheers, 
Nigel

**Comment by sschlein** [comment]
Hey, we need to update the way this is displayed in the dashboard – feel free to ignore the plugin activation :-)
