### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by ordago** [beyondcode/tinkerwell-community#367]
![explorer_FhbfolS2tX](https://user-images.githubusercontent.com/6376814/102884595-c5fe2280-4449-11eb-829d-3160891a4561.png)

After I updated the php version on windows it stopped working and only showed that message. In the console php still worked `php -v` showed the version. So the error message wasn't that helpful.

The solution was to update the php path in settings

https://beyondco.de/docs/tinkerwell/getting-started/installation#setting-up-php

**Comment by mpociot** [comment]
Can you please provide a screenshot of the configured PHP path in the Tinkerwell settings?
This error mostly means that Tinkerwell is unable to execute PHP in the specified path.

**Comment by ordago** [comment]
Hi @mpociot 

This is my current settings:

![image](https://user-images.githubusercontent.com/6376814/111808667-20354500-88cc-11eb-92aa-758e9f51647e.png)

I think at the time the php version on my system got updated to 7.3 so Tinkerwell could find the 7.2 version. Now I've got the version pinned.

Could it be a good idea for Tinkerwell to get the path from the `path` environment variable?

**Comment by mpociot** [comment]
Thank you for the response.
We actually try to load it from the PATH variable on the very first start. But good to know that it's working now. I'll close this issue then :)
