### ISSUE TITLE
Call to undefined method Psy\Exception\ErrorException::fromError()  

### ISSUE THREAD

**Issue by matfish2** [beyondcode/tinkerwell-community#368]
Tinkerwell version: 2.11.0. 
Laravel Version: 5.1
PHP version as gleaned from phpinfo(): 7.1.33-3+ubuntu18.04.1+deb.sury.org+1

I have two issues:

1. I'm getting the following error: [Symfony\Component\Debug\Exception\FatalThrowableError]             
  Call to undefined method Psy\Exception\ErrorException::fromError()  
![2020-12-28 (6)](https://user-images.githubusercontent.com/1510460/103202293-af991080-48fa-11eb-98db-31c0c7a0c46b.png)

2. I can't find Tinkerwell in Windows search after installation.
![2020-12-28 (5)](https://user-images.githubusercontent.com/1510460/103202243-8d9f8e00-48fa-11eb-989a-0ffe3003c8f3.png)

**Comment by hxshandle** [comment]
Same error here

**Comment by mpresland** [comment]
Same `Call to undefined method Psy\Exception\ErrorException::fromError()` on Mac via Valet with Laravel 5.1

**Comment by mpresland** [comment]
The worst part is having to remember how I used to debug before Tinkerwell

**Comment by mpociot** [comment]
@mpresland Does the error occur on every Laravel project, or only with 5.1?

**Comment by mpresland** [comment]
@mpociot It looks like 5.1 for me. I'm able to use a project on 7.2.2, 7.15.1, 8.6 and 8.11.2

**Comment by matfish2** [comment]
Any update on this? Can I at least download an earlier version somehow?

**Comment by hxshandle** [comment]
Any updates?

**Comment by jzpeepz** [comment]
@mpociot I have the same issue on 5.1. I am using Homestead. Laravel 5.5 and up seemed to be fine. Unfortunately, I don't have any project between 5.1 and 5.5 to test.

**Comment by mpresland** [comment]
@mpociot with the update to 2.12.1 i'm now getting the following when trying to run tinkerwell with a L5.1 project.
![image](https://user-images.githubusercontent.com/16057824/107494947-26544980-6bdb-11eb-994e-9d2d3c8af097.png)

**Comment by rcknr** [comment]
I experience the same problem as @mpresland

**Comment by matfish2** [comment]
same as @mpresland and @rcknr using L5.1: 

```
CustomErrorException with message 'PHP Error:  Call to undefined method Psy\Shell::getBoundObject() in phar:///tmp/tinker_compressed.phar/vendor/psy/psysh/src/ExecutionClosure.php on line 81'
```

**Comment by mpresland** [comment]
@mpociot Is there any progress on this issue? 

My Tinkerwell licence came up for renewal last week, however I am unable to use Tinkerwell for the project for which I need it the most. This project is currently bound to Laravel 5.1 due to a mass of legacy code, and Tinkerwell has become a huge part of my workflow on this project. I can't justify renewing my licence if we aren't able to get past the errors here with older versions of Laravel. 

I am very keen to continue using Tinkerwell, but currently i'm a `dd();` developer, and it is a slow slow process.

**Comment by mpociot** [comment]
It took some serious tinkering (see what I did there), but I managed to fix this bug and we will release a patch shortly 🎉

**Comment by mpresland** [comment]
@mpociot Thanks Marcel! Definitely appreciate it. Looking forward to the patch.

**Comment by poovarasudev** [comment]
@mpociot I'm also facing this same issue, Kindly give a fix for this as soon as possible.

**Comment by vstyler96** [comment]
Same here Laravel 5.2 ´Call to undefined method Psy\Shell::getBoundObject()´

**Comment by rcknr** [comment]
The update finally came over today but it won't let me update due to my license being too old now.
What's the last version of Tinkerwell that worked with Laravel 5.1?
