### ISSUE TITLE
parse error on ssh connection

### ISSUE THREAD

**Issue by carlituxman** [beyondcode/tinkerwell-community#369]
connecting by ssh I have this error on every action:

Parse error: syntax error, unexpected '?' in phar:///tmp/tinker_compressed.phar/index.php on line 4

**Comment by codelinde** [comment]
I've actually got this too, SSHing into a Homestead VM. Seems like maybe the wrong binary is being used, but my project uses 5.6, which is what the command line 'php' is pointing to in the VM, so setting the binary to 'php' in the SSH connection window I thought would do the trick.

**Comment by mpociot** [comment]
Sorry, but PHP 5.6 is not supported with Tinkerwell
