### ISSUE TITLE
Unable to use laradock

### ISSUE THREAD

**Issue by akajack** [beyondcode/tinkerwell-community#370]
Hi all, I have a problem with Tinkerwell and Docker.
I have a Mac and locally I use Docker with Laradock for development. I'm trying to get Tinkerwell to connect to the workspace image of docker to make it execute commands correctly, but I just can't.
I try to configure Docker in Tinkerwell, but it keeps giving me this error:

<img width="751" alt="Schermata 2020-12-29 alle 16 44 48" src="https://user-images.githubusercontent.com/2247871/103296039-84471c00-49f5-11eb-97c3-953c18cd9726.png">

Yet Docker, Docker Compose and images are working correctly:

<img width="635" alt="Schermata 2020-12-29 alle 16 45 15" src="https://user-images.githubusercontent.com/2247871/103296092-a345ae00-49f5-11eb-817c-817eecf669e6.png">

Please help me :(

**Comment by ChrisChoTW** [comment]
Hi, I use laradock too, and I found another way to use it.

In my case, using ssh to connect would do the trick.

If you didn't change laradock's workspace ssh port, then it would be "2222", and the default private key would be at  {laradock_path}/workspace/insecure_id_rsa, and the user name is "laradock".

![ssh](https://user-images.githubusercontent.com/3102275/109772784-62f2ee00-7c39-11eb-839f-89b974a23f58.png)

Hope it helps.

**Comment by mpociot** [comment]
@ChrisChoTW Does Laradock come with SSH support out of the box? Then I would also prefer this approach as it's much faster than going through docker every time to evaluate code with Tinkerwell. 
If that's the case, I would add it to the documentation.

**Comment by ChrisChoTW** [comment]
@mpociot As mentioned previously, I used Tinkerwell with laradock via ssh.
The related document is shown as follow.
[https://laradock.io/documentation/#access-workspace-via-ssh](access-workspace-via-ssh)
According to the steps in the document, connecting laradock via ssh will work.
If you have any question about how to connect, please let me know, I'm glad to help.

**Comment by akajack** [comment]
Thank you all so much for the help!
I followed your advice and got access to Laradock using ssh.
Yesterday I updated Laradock and, trying again with "Configure Docker", Tinkerwell works fine. I first set up the working folder pointing to the Laradock folder, then select Docker and I can set everything up perfectly.
Before yesterday, Tinkerwell had never been able to find containers.

Thanks again ;)
