### ISSUE TITLE
Large memory leak when xdebug is turned off?

### ISSUE THREAD

**Issue by ipkpjersi** [beyondcode/tinkerwell-community#371]
Hello there,

I have an issue with Tinkerwell and PHP 7.4 and Xdebug 2.9.8. When I have Xdebug turned off (`phpdismod -s xdebug`) and I load up Tinkerwell and try to run the following Magento code, it takes an extremely long time to execute, and my memory quickly fills up: 
![2020-12-31_15-13-25_1609445605521773081](https://user-images.githubusercontent.com/33754783/103424750-37da1880-4b7c-11eb-8ff7-d027ae3473e1.png)

When Xdebug is turned on (`phpenmod -s cli xdebug`), the code executes instantly and the output is instant as well:
![2020-12-31_15-12-16_1609445536206517747](https://user-images.githubusercontent.com/33754783/103424811-8091d180-4b7c-11eb-8d3a-b21fde9dce10.png)

Here is an example of my `/tmp` folder when this was happening, nothing looks out of the ordinary to me:
![2020-12-29_18-12-45_1609283565118248379](https://user-images.githubusercontent.com/33754783/103424871-cc447b00-4b7c-11eb-916d-277cdc37477d.png) the data.dxt that it is writing (or reading?) looks very small to me.

Here is my PHP info:
![](https://i.imgur.com/dgIopxe.png)

Here is an example of the memory as it starts climbing:
![2020-12-29_18-30-55_1609284655100193482](https://user-images.githubusercontent.com/33754783/103424854-b59e2400-4b7c-11eb-8792-e7ba5d24266f.png)

Here is an example of the memory at it's peak with my PC quickly running out of memory and freezing shortly after:
![2020-12-29_18-11-48_1609283508277935625](https://user-images.githubusercontent.com/33754783/103424869-c9498a80-4b7c-11eb-9bf3-7030d19cd244.png)

Normally I would probably say Xdebug is at fault here, however, it makes no sense - the memory leak happens when Xdebug is *off*, not *on*, so how could it be Xdebug? Now, that either leaves Tinkerwell, Magento, or PHP itself. I don't think it's likely for it to be PHP itself, so I'm kind of thinking it might be Tinkerwell at fault here? I'm not sure.

As the default Magento driver for Tinkerwell wasn't working for me anymore, I did end up having to make `/var/www/html/magento/.tinkerwell/CustomMagento2TinkerwellDriver.php`, here is the contents of that file (It's the same as the regular Magento 2 Tinkerwell driver but it's just in a custom driver file instead): https://gist.github.com/ipkpjersi/68cbcf05989a0c336b1b388f03191cd6

System specs: 
![](https://i.imgur.com/sKh7DvF.png)

If you need any more details, please let me know.

Thanks.

**Comment by mpociot** [comment]
Hi!

Thank you for the detailed error report. I am unable to reproduce this issue locally and believe that this is a pretty specific edge case that you are running in. 
It is very strange that the evaluation becomes faster when xdebug is enabled, but I would still consider this whole setup to be quite an edge case and something out of the scope of Tinkerwell to fix.

**Comment by ipkpjersi** [comment]
Hi,

I'm quite confused how this is beyond the scope of Tinkerwell - is it because I'm using Linux (which 80% of web servers are), or is it because I'm using Magento, or is it because I'm using XDebug?

It's unfortunate to hear this won't be fixed, a system becoming entirely unresponsive when using an application is a fairly critical bug.

Thanks.

**Comment by ipkpjersi** [comment]
Also,

I should mention, I think this is actually a regression - I don't actually recall running into this issue before?

Thanks.
