### ISSUE TITLE
Error after updating to 2.11

### ISSUE THREAD

**Issue by lcbursuc** [beyondcode/tinkerwell-community#373]
Hi guys!
Great job with Tinkerwell!

I updated to the latest version and I get this:
"PHP Error:  Call to undefined method Psy/Shell::getLastExecSuccess() in phar:///Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar/index.php on line 99"

Tried reinstalling the App but the error remains.

I reverted back to 2.10.2 and I'm good to go.

**Comment by mpociot** [comment]
Could you tell me which Laravel version you are using, where you see this error?

**Comment by lcbursuc** [comment]
I'm using the standalone App, not the cmd line within Laravel, on a Mac and imported Laravel projects with 5.6 and 7 versions to work with.
Plus I tried using simple PHP sintax and still shows the same error.

I defaulted to the Tinkerwell version of Laravel and seems to work now, but when working on the previous projects I still get this error.

<img width="1680" alt="Screen Shot 2021-01-04 at 3 59 50 PM" src="https://user-images.githubusercontent.com/298942/103542755-1479db00-4ea6-11eb-880c-0b6b189358c1.png">

**Comment by nezaboravi** [comment]
I am having the exact same error, using laravel 7.xx
Tinkerwell Version 2.11.0 (2.11.0)
PHP 7.4
When open tinkerwell, there is some file you put there to be an example of a unit test with tinkerwell. 
class Tinkerwell extends... 

As soon as I delete content on screen I get an error on right-hand side

![test deleted](https://user-images.githubusercontent.com/1515172/103562862-1484d580-4ebc-11eb-93f1-aab71dac06d7.jpg)
![Untitled 2](https://user-images.githubusercontent.com/1515172/103562867-164e9900-4ebc-11eb-9571-53f0ac9ac42e.jpg)

**Comment by nezaboravi** [comment]
@mpociot any ideas how to fix this? :)

**Comment by nezaboravi** [comment]
@mpociot this still not works mate. Is there anything else I can provide to get your attention to this?

**Comment by mpociot** [comment]
Hi @nezaboravi ,

it seems like you are using Tinkerwell in the "testing" mode - which is supposed to be only used for running PHPUnit tests.
As you are not providing a test class, the error gets thrown. 
You should use the "CLI" mode. You can switch the modes by using the application menu:

![image](https://user-images.githubusercontent.com/804684/105727496-6fde3c80-5f2b-11eb-93bc-be8b8906a980.png)

**Comment by nezaboravi** [comment]
So obvious when one knows where to look. Thanks, finally can get back to tinkering

**Comment by sschlein** [comment]
We've added an issue to our backlog to show the current mode in the titlebar 😅
