### ISSUE TITLE
"Run code" Command Leads to it Running Twice

### ISSUE THREAD

**Issue by SirNovi** [beyondcode/tinkerwell-community#375]
I wonder if I am missing something obvious here. But `cmd+R` or the `Run Code` button leads to it running twice on my Laravel 8 installation. 

I've got a websockets server set up and I'm triggering an event like so

`event(new App\Events\Message('test'));`

When it get's triggered automatically after typing it it only appears once in the console but i I actively run it it appears twice. 

Any help appreciated!

**Comment by mpociot** [comment]
Do you have auto evaluation enabled in the settings? This could potentially lead to dual code evaluation

**Comment by SirNovi** [comment]
Yes, I had it enabled and yes, turning it off removes the issue. 

Now I'm just not sure what exactly that feature that and what I am missing out on now.

**Comment by SirNovi** [comment]
ah.. I wasn't thinking clearly. Of course I understand what auto evaluation is… 

So this should not happen, right? As I don't change anything on the code whatsoever. I just click the run button and it runs twice when it should only run once.

**Comment by mpociot** [comment]
This will be fixed in the next version.
