### ISSUE TITLE
Executing on Vapor fails with PHP syntax error

### ISSUE THREAD

**Issue by mitchazj** [beyondcode/tinkerwell-community#376]
Executing
```
User::all()
```
on my local version of my Laravel application works fine. However, turning on Vapor execution and trying again fails with the following error:
```
PHP Error:  syntax error, unexpected end of file in Psy Shell code(1) : eval()'d code on line 1
```
Details:
- macOS Big Sur
- PHP 7.4 via Valet
- Laravel 7
- Vapor environment is working fine in production

**Comment by mpociot** [comment]
That's because of the way that the vapor tinker method works. Tinkerwell allows you to evaluate "invalid" PHP (the semicolon is missing), while Vapor doesn't.
If you add a semicolon to your code it should work on Vapor as expected

**Comment by mitchazj** [comment]
Ahh ok. Yup, adding a semicolon makes it work, although I also have to wrap statements with "print()" to make them produce visible output of any kind.
