### ISSUE TITLE
Tinkerwell SSH working but class not all loaded

### ISSUE THREAD

**Issue by dib258** [beyondcode/tinkerwell-community#377]
I have a working connection to an instance of Homestead, where the connection seems to be made but I cannot access any element from the Laravel Framework.

I have the same connection to other Homestead instances which are working perfectly well.

For example when I try to see if `User` class model exists with the following : `class_exists('App\User');` it returns `false`.

And inside the Homestead instance when I run `php artisan tinker` with the same test, It works with this results : 
```
➜  php artisan tinker
Psy Shell v0.10.5 (PHP 7.4.13 — cli) by Justin Hileman
>>> class_exists('App\User');
=> true
```

Isn't there a way to be able to debug how Tinkerwell try to access the directory and/or see what could be causing this ?

I'm using Tinkerwell 2.11.0 and Homestead v10.17.0, v11.4.0 with Ubuntu 18.04.5 LTS, PHP 7.4

**Comment by sschlein** [comment]
Do you get any output in general?
Are the paths in the SSH connection 100% correct? Anything special with them, like a space or other character that is known for causing issues?
Do you get any output on right click in the editor? It should tell you the current Laravel version of the project.

**Comment by dib258** [comment]
For example if I run `App\User::all();` in Tinkewell, I get this message 
```
PHP Fatal error:  Class 'App/User' not found in Psy Shell code on line 1
```

And when I right-cli in the editor, I can see the version of Laravel like you said 
`Detected Laravel v7.21.0`

Can I do something else to get more info ?

**Comment by kereborn** [comment]
There may be a relation to #393 here.

**Comment by mpociot** [comment]
@dib258 Just to verify the proper framework detection, could you try running something like: `app()->version()` and `base_path()` and send a screenshot of the results?

**Comment by kevinbigfun** [comment]
> @dib258 Just to verify the proper framework detection, could you try running something like: `app()->version()` and `base_path()` and send a screenshot of the results?

I got exactly the same problem and these two method calls failed in Tinkerwell after SSHing into AWS EC2 instance:
PHP Fatal error:  Call to undefined function base_path() in Psy Shell code on line 11

I'm sure SSH is well connected, with the result of  'echo __DIR__': '/home/centos'

**Comment by mpociot** [comment]
> I'm sure SSH is well connected, with the result of 'echo DIR': '/home/centos'

Are you sure that this is the working directory of your project? Shouldn't it be in another subfolder?

**Comment by kevinbigfun** [comment]
> > I'm sure SSH is well connected, with the result of 'echo DIR': '/home/centos'
> 
> Are you sure that this is the working directory of your project? Shouldn't it be in another subfolder?

thank you for replying. just double checked ssh settings for 'App Folder', and found I got typo.
now it works.
