### ISSUE TITLE
Craft driver not working out of the box

### ISSUE THREAD

**Issue by eirabben** [beyondcode/tinkerwell-community#380]
When opening a Craft 3 project with Tinkerwell, it doesn't seem to load the Craft Driver. The Craft constant is not available.

When I copy the Craft driver into the `CustomTinkerwellDriver` in the same project, everything works.

Not sure if this is an issue on my end, or if the autodetection of Craft projects is not working as intended.

I have tried on multipe Craft 3 projects, all with the default directory structure.

**Comment by mpociot** [comment]
This will be fixed in the next version!
