### ISSUE TITLE
Get rid with highlighted result.

### ISSUE THREAD

**Issue by SupianIDz** [beyondcode/tinkerwell-community#381]
How to get rid of this red highlight on the terminal, it's really uncomfortable.

![x](https://user-images.githubusercontent.com/37969970/105389214-8dbd5000-5c52-11eb-8546-694b75faf3bb.png)

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">This tool window comes from the Tinkerwell plugin, so it makes sense to forward this request to them <a href="https://t.co/XFGmLJnFlS">https://t.co/XFGmLJnFlS</a></p>&mdash; JetBrains PhpStorm (@phpstorm) <a href="https://twitter.com/phpstorm/status/1352228669171904513?ref_src=twsrc%5Etfw">January 21, 2021</a></blockquote

My setup is:
- PHP Storm 2020.03 Latest With Nord Theme
- Zorin OS 15.3 Ultimate

Thanks.

**Comment by mpociot** [comment]
The output is using the default PHPStorm output style, so there won't be an easy fix for this soon.
