### ISSUE TITLE
Idea: Execute code under the cursor

### ISSUE THREAD

**Issue by moisish** [beyondcode/tinkerwell-community#382]
It will be nice if you can execute part of the code either by selecting the part you need or executing the code that is under the cursor.

For example if I use this code it will execute all three queries and will return the result of the last one. 
If I have selected the first line or having my cursor at the end of it, it will be nice to execute just that

```
User::first();

User::where('id',2)->first();

User::where('id',3)->first();
```

**Comment by sschlein** [comment]
Watch upcoming release notes 👀
