### ISSUE TITLE
Following the theme & Autocomplete

### ISSUE THREAD

**Issue by SupianIDz** [beyondcode/tinkerwell-community#383]
Just give advice, It would be very beautiful and nice if the sidebar and display settings followed the theme And also autocomplete by project.

![Screenshot-20210122210746-480x443](https://user-images.githubusercontent.com/37969970/105494639-0d502b00-5cf6-11eb-8232-7ef6b3f4b6ac.png)

![Screenshot-20210122210734-1920x1080](https://user-images.githubusercontent.com/37969970/105494644-0f19ee80-5cf6-11eb-9d73-3edf6deff25b.png)

**Comment by sschlein** [comment]
Hey & thanks for your suggestion.

Autocomplete is on the list but we haven't found a solution to this yet. Existing autocomplete modules that we can buy and integrate would basically double the price of the application and add maintenance overhead for us. 

The beauty of the theme is that we can simply drop in themes of the open source editor that we use for Tinkerwell. This has been added a while after we have built the application and so theming the whole application requires a full rewrite of the UI.

That said, we have this on our Version 3 list but have no release date planned. Definitely not in the first half of 2021
