### ISSUE TITLE
import / use statements on Tinkerwell never work when extending / implementing a class - i always have to use the FQCN when extending.

### ISSUE THREAD

**Issue by morrislaptop** [beyondcode/tinkerwell-community#384]
```php
use Illuminate\Contracts\Validation\Rule;

class Uppercase implements Rule
{
  
}
```

has

`PHP Fatal error:  Interface 'Rule' not found in Psy Shell code on line 3`

**Comment by sschlein** [comment]
`php artisan tinker` does not support classes, so Tinkerwell can't either – this is a limit by design

**Comment by morrislaptop** [comment]
That’s not a very helpful design and IMO is expected behaviour. At the least is there an issue upstream for this?

**Comment by sschlein** [comment]
As long as Laravel doesn't implement that at its core, we are not able to implement that on our end
