### ISSUE TITLE
Add a shortcut to toggle auto-evaluate

### ISSUE THREAD

**Issue by corbosman** [beyondcode/tinkerwell-community#385]
I absolutely love using Tinkerwell, but the one thing that makes the experience slightly less is that I often want to switch between auto-evaluate or not.  Usually when I have queries that might update the DB, or otherwise heavy SQL, I usually dont want to auto-evaluate. It would be nice if there was a way to just click that on/off right in the main UI.

**Comment by mpociot** [comment]
This will be in the next version
