### ISSUE TITLE
Is there a support for paid users?

### ISSUE THREAD

**Issue by nezaboravi** [beyondcode/tinkerwell-community#386]
I am not getting support and help here for 21 day no reply.
Is there a specialised place to get support when you pay for product?
21 days seems a lot to wait for the answer. 

Link to question:
https://github.com/beyondcode/tinkerwell-community/issues/373#issuecomment-754117633

**Comment by sschlein** [comment]
https://github.com/beyondcode/tinkerwell-community/issues/373#issuecomment-766901697

**Comment by nezaboravi** [comment]
Thanks, got an answer. All good now.
