### ISSUE TITLE
Can tinkerwell run on apple silicon m1 natively without rosetta2?

### ISSUE THREAD

**Issue by Magicgear** [beyondcode/tinkerwell-community#388]
I know tinkerwell is based on Electron. Since Electron 11.0.0 can run on m1 natively, it's possible for tinkerwell too. Just not sure if tinkerwell is using the latest Electron version.

**Comment by sschlein** [comment]
We don't use the latest version at the moment but plan to upgrade later this year – I don't see such an update within the next 2-3 months for now (but this can change if an update is easier than expected)

**Comment by leemcd56** [comment]
I've requested Tinkerwell be added to the _Does It ARM?_ list. The issue should be referenced above. 🙂
