### ISSUE TITLE
Tinkerwell doesn't allow using a different public folder name

### ISSUE THREAD

**Issue by alistairreynolds** [beyondcode/tinkerwell-community#389]
If I have a public folder name of eg "public_html" (some hosts require this), I need to change my AppServiceProvider to allow for this

```php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider

/**
 * Register any application services.
 *
 * @return void
 */
public function register()
{
    $this->app->bind('path.public', function () {
        return base_path('public_html');
    });
}
```

However, doing this means that most things in Tinkerwell throw errors and it's basically pointless to use. 

Changing to using the standard "public" folder fixes this, but it's not exactly ideal

**Comment by mpociot** [comment]
You can create a custom driver in this case to use with your project. See: https://github.com/tinkerwellapp/drivers#documentation
