### ISSUE TITLE
Keybindings on Windows don't work properly 

### ISSUE THREAD

**Issue by MiloudiMohamed** [beyondcode/tinkerwell-community#394]
I'm on windows 10, Tinkerwell version (2.11.0)

CTRL+Z and CTRL+T don't work properly.

CTRL+Z closes the current tab (or closes Tinkerwell if only one exists), and hitting CTRL+T doesn't do anything.

**Comment by sschlein** [comment]
Are you using an AZERTY keyboard layout?

**Comment by MiloudiMohamed** [comment]
Yes

**Comment by sschlein** [comment]
This is currently an issue with Electron and we do have a ticket for this:
https://github.com/beyondcode/tinkerwell-community/issues/361

I'm closing this one – I am afraid that you'll need to wait a moment until we can fix this
