### ISSUE TITLE
Provide Publisher information for a Windows installation file

### ISSUE THREAD

**Issue by slaFFik** [beyondcode/tinkerwell-community#396]
As the `.exe` file isn't signed and doesn't have a Publisher, Windows shows this screen when trying to install the app:

![6orDZqTA](https://user-images.githubusercontent.com/282234/106391305-53437800-63f5-11eb-9a43-f07f23a16571.jpg)

It would be great if you could provide all the needed information inside the installation file, so Microsoft Defender SmartScreen won't be triggered.

**Comment by mpociot** [comment]
We will look into it. In the meantime press "Run anyway" - you can trust us 😇
