### ISSUE TITLE
Unexpected syntax error with "double" comments...

### ISSUE THREAD

**Issue by telkins** [beyondcode/tinkerwell-community#399]
I haven't tried too much to narrow things down to when, where, or why it happens, but a syntax error is given when the following code is entered:

```php
$data = [
    'foo' => [
        // 'bar',
        // // 'bar',
    ],
];
```

Error: `PHP Parse error: Syntax error, unexpected ';', expecting ',' or ')' or ']' on line 4`

It seems to be tied to the two commented-out lines.  If the values are different, then no error.  If the values are the same (I've tried strings/integers/bools), then there's an error.  If I remove the "double" comment, then no error.

I won't spend too much (more) time looking into this...unless, of course, someone has questions.

I'm on 2.11.0 and running it on my Macbook Pro.  Let me know what else you might need to know.

Thanks.

**Comment by mpociot** [comment]
This error occurs because Tinkerwell internally removes PHP comments/doc-blocks before the code gets evaluated.
I don't think this issue is common enough to fix in our code-base, so please just avoid double-comments :D
