### ISSUE TITLE
adverts in Tinkerwell

### ISSUE THREAD

**Issue by anugupta** [beyondcode/tinkerwell-community#401]
Is there a way to stop Tinkerwell displaying adverts – I don't remember signing up to anything that says BeyondCode can put adverts into Tinkerwell for other products they create.

Please either stop doing this, or add an opt-in setting to show adverts for other BeyondCode products.

**Comment by mpociot** [comment]
This is a message of the day, that we only use when updates of the app get published. You only see this message once after opening the app and then not anymore. 
I'll add an option to the settings to disable showing the message of the day 👍

**Comment by anugupta** [comment]
Thank you 👍
