### ISSUE TITLE
HTTP Mode - Returning View

### ISSUE THREAD

**Issue by fargonse** [beyondcode/tinkerwell-community#404]
When i use a Default Laravel App, all works fine:

![Captura de pantalla de 2021-03-06 11-58-59](https://user-images.githubusercontent.com/15324006/110211031-5f4aab80-7e73-11eb-8b75-4162985e79b4.png)

But, when i select an existing project, the same example, returns a 404 error:

![Captura de pantalla de 2021-03-06 12-01-05](https://user-images.githubusercontent.com/15324006/110211078-a8026480-7e73-11eb-90f0-4926ad8e00a8.png)

Any ideas?

Thx!

**Comment by mpociot** [comment]
Please clear your view and route cache in the Laravel application. This will fix the issue, as Tinkerwell is adding a custom route, while it's being used in your Laravel app.
