### ISSUE TITLE
Unable to launch Tinkerwell 

### ISSUE THREAD

**Issue by msbuilds** [beyondcode/tinkerwell-community#405]
Attempting to open Tinkerwell on macOS 11.1 (20C69) on an M1 Pro.
Immediately crashes and creates a problem report:

Process:               Tinkerwell [23166]
Path:                  /Applications/Tinkerwell.app/Contents/MacOS/Tinkerwell
Identifier:            de.beyondco.tinkerwell
Version:               ???
Code Type:             X86-64 (Translated)
Parent Process:        ??? [1]
Responsible:           Tinkerwell [23166]
User ID:               501

Date/Time:             2021-03-12 08:57:10.388 -0500
OS Version:            macOS 11.1 (20C69)
Report Version:        12
Anonymous UUID:        07DC1D97-D4E8-6A83-88F8-214611EE932D

Sleep/Wake UUID:       C51BDCE8-17F1-4145-BC21-2D38C2049B7F

Time Awake Since Boot: 80000 seconds
Time Since Wake:       6100 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: E2B1A630-68DD-30AC-A036-6AC018B154DA
Library not loaded: /usr/local/opt/libssh2/lib/libssh2.1.dylib
  Referenced from: /Applications/Tinkerwell.app/Contents/MacOS/Tinkerwell
  Reason: image not found

Binary Images:
       0x1048aa000 -        0x104908fff + (0) <3E8313BA-836F-30CD-AE2F-30E5C80310CC> 
       0x10cca0000 -        0x10cd76fff +org.cocoapods.Alamofire (5.0.0 - 1) <354E2043-A17C-3338-977E-44652F747357> /Applications/Tinkerwell.app/Contents/Frameworks/Alamofire.framework/Versions/A/Alamofire
       0x10d206000 -        0x10d264fff +com.paddle.Paddle (4.0.13 - 4.0.13) <18F70294-2C31-3AA5-B789-EAF177B9CC73> /Applications/Tinkerwell.app/Contents/Frameworks/Paddle.framework/Versions/A/Paddle
       0x10d425000 -        0x10d476fff +org.sparkle-project.Sparkle (1.22.0 33-gd5222353e - 1.22.0) <1DA0A252-CD33-3E99-8A87-F67893C479C8> /Applications/Tinkerwell.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x10d58b000 -        0x10d5adfff +org.cocoapods.SwiftyJSON (4.3.0 - 1) <B60DDEB5-89D5-3F60-8EE8-4A8CA42C082A> /Applications/Tinkerwell.app/Contents/Frameworks/SwiftyJSON.framework/Versions/A/SwiftyJSON
       0x204b07000 -        0x204ba2fff  dyld (832.7.1) <DEA51514-B4E8-3368-979B-89D0F8397ABC> /usr/lib/dyld
    0x7ffdffd67000 -     0x7ffdffddafff +runtime (203.13.2) <3B9E4ADB-AB4E-30AD-A642-B74313FB48A8> /Library/Apple/*/runtime
    0x7fff24698000 -     0x7fff24b35fff  com.apple.CFNetwork (1209.1 - 1209.1) <60DE4CD6-B5AF-3E0E-8AF1-39ECFC1B8C98> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff3c8bf000 -     0x7fff3d2f8fff  com.apple.WebKit (16610 - 16610.3.7.1.9) <6B379251-21D4-3FB9-BD1E-11EF1AC2D623> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit

Model: MacBookPro17,1, BootROM 6723.61.3, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Oct 20 2020 12:49:54 version 18.20.222.14.7.8.100 FWID 01-ba327c2d
Bluetooth: Version 8.0.2f9, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
USB Device: USB3.2 Hub
USB Device: USB2.1 Hub
USB Device: USB 2.0 Hub
USB Device: BillBoard Device
USB Device: 4-Port USB 2.0 Hub
USB Device: Razer BlackWidow Ultimate 2016
USB Device: Yeti Stereo Microphone
USB Device: USB Receiver
USB Device: SteelSeries Rival 3 Wireless
USB Device: HID Device
Thunderbolt Bus: MacBook Pro, Apple Inc., 0.0
Thunderbolt Bus: MacBook Pro, Apple Inc., 0.0

**Comment by sschlein** [comment]
It looks like the M1 Mac is missing a library:
`Library not loaded: /usr/local/opt/libssh2/lib/libssh2.1.dylib`

We normally bundle this with the application but there could be an issue with the M1 (but it works on our M1 machines and so it seems to be machine-related)
