### ISSUE TITLE
App Crash and Freeze

### ISSUE THREAD

**Issue by Omnius1234** [beyondcode/tinkerwell-community#406]
When i open Tinkerwell,the app crash and freeze

**Comment by sschlein** [comment]
Which operating and Tinkerwell version do you use?

This is the first time that someone mentions this

**Comment by Omnius1234** [comment]
i'm using the version 2.12.1,
the problem appears when i open a php file but not always,
when i open some php file,the app crash and freeze and i can't write or do anything

**Comment by mpociot** [comment]
Can you tell me the operating system you use?
I'm also unable to reproduce the issue - and "but not always" is always hard to reproduce 😅

**Comment by Omnius1234** [comment]
windows 10  20H2 19042 ,you're right too 😅 but that's all

**Comment by Omnius1234** [comment]
how can i help debug that?

**Comment by mpociot** [comment]
This should be fixed with the latest version (2.13.0)
