### ISSUE TITLE
Shortcut "Ctrl+T" did not open a new tab

### ISSUE THREAD

**Issue by ajcastro** [beyondcode/tinkerwell-community#409]
It is suppose to open a new tab when shortcut "Ctrl+T" is pressed

**Comment by sschlein** [comment]
Which OS do you use?

**Comment by ajcastro** [comment]
@sschlein I use windows 10

**Comment by sschlein** [comment]
At the moment, this sounds like an issue that only happens on your machine. There was no update of the application in the last week and we haven't heard anything from other Windows users.

Maybe your settings file got corrupted somehow and that's really hard to debug for us. 

Can you try to reset your application by deleting your application cache and settings folders? 

You find this files here: https://beyondco.de/docs/helo/troubleshooting/common-issues#paths. Please swap the HELO folder with Tinkerwell :-)

**Comment by sschlein** [comment]
It could also be related to this: https://github.com/beyondcode/tinkerwell-community/issues/407

**Comment by mpociot** [comment]
@ajcastro Can you also tell us the keyboard layout that you use? It could be related to a keybinding issue.

**Comment by ajcastro** [comment]
I am not very sure with the keyboard layout but afaik this is just a regular keyboard layout. Our company bought 2 licenses which is good for 4 computers, none of them works for the Ctrl+T to open new tab

**Comment by ajcastro** [comment]
I checked it, it is QWERTY, English US

**Comment by mpociot** [comment]
This will be fixed in the next release.
