### ISSUE TITLE
Run code on Azure WebApp is not showing any output

### ISSUE THREAD

**Issue by rick20** [beyondcode/tinkerwell-community#410]
I just purchased Tinkerwell this week and I would like to test a code on my Azure WebApp.
The SSH connection is made through tunnel (```az webapp create-remote-connection```).
I can see that the Tinkerwell can successfully established the SSH connection.
However running any code gives no output at all.
I tested it using other servers and it works perfect.
Perhaps it would be very helpful if there's a debugging info so we can see where the problem is?

PS: my OS is macOS Catalina

**Comment by mpociot** [comment]
Is the configured path to your PHP binary, as well as your project path, correct?

**Comment by rick20** [comment]
@mpociot yes....I've set PHP binary and simulate it directly in the ssh.
Project path was initially pointed to a symlink /home/site/wwwroot, but then I tried with real physical path as well.
None of them works.
But I think this is not related to project path, since a simple ```echo "hello";```  should works anywhere.
I tried in another server, random directory, and it still works.

**Comment by rick20** [comment]
Just got an update from my teammate that he can use Tinkerwell on webapp, so I give it another try and surprisingly it's working perfectly on azure webapp now, with same settings, same webapp instance. I guess the issue was on the kudu service and they already fixed it.
