### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by mdk999** [beyondcode/tinkerwell-community#412]
Using Laravel sail.. Connected to Sail instance in docker and..

ran 
`composer require --dev beyondcode/tinkerwell-helper`

got 
  ```
[InvalidArgumentException]                                                                                                          
  Package beyondcode/tinkerwell-helper has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
```
```
Composer: 2.0.11 2021-02-24 14:57:23
PHP version: 8.02
```

**Comment by mpociot** [comment]
We are working on some bigger changes coming to the tinkerwell-helper package. It doesn't affect the usage of Tinkerwell itself, so I'd advise you to not use the helper package in the meantime. The app (in combination with your Laravel app) is going to work fine of course.
