### ISSUE TITLE
Strange error when running PHP 8.1 and using Enums

### ISSUE THREAD

**Issue by mazedlx** [beyondcode/tinkerwell-community#414]
Hi there!

Tinkerwell Version 2.12.1 (2.12.1) on MacOS

PHP Version 8.1.0-dev

```php
enum Status {
  case Pending;
  case Active;
  case Archived;
}

var_dump(Status::Pending);
```

This should output `enum(Status::Pending)`(works on CLI)

Tinkerwell throws an error: `ErrorException with message 'Undefined array key 335`

**Comment by mpociot** [comment]
As PHP 8.1 is not yet released, I'll look into this when we get closer to a release. 
I would assume that the underlying PHP Parser simply doesn't yet know about the new syntax/token.
