### ISSUE TITLE
Results screen shows white with number '1'

### ISSUE THREAD

**Issue by fri3ndly** [beyondcode/tinkerwell-community#418]
Just want to highlight the same issue i've been having with Tinkerwell for the last year. My [related past issue ](https://github.com/beyondcode/tinkerwell-community/issues/286) was recently closed.

I have had Tinkerwell for a year - it worked like a dream at first and I loved it. Then as the new versions kept self upgrading after a while it just did not work correctly any longer.

The Tinkerwell results screen just shows this for every successful data fetch:

<img width="450" alt="Screenshot 2021-04-14 at 06 19 52" src="https://user-images.githubusercontent.com/2011395/114658275-73db5880-9ce9-11eb-8118-b2c5f05df61f.png">

I do seem to receive an error correctly when there is a syntax issue. e.g:

<img width="877" alt="Screenshot 2021-04-14 at 06 20 56" src="https://user-images.githubusercontent.com/2011395/114658397-9ec5ac80-9ce9-11eb-99ad-93a50376cf0d.png">

But as soon as I add the semicolon and the result should be returned the white screen with '1' returns:

<img width="881" alt="Screenshot 2021-04-14 at 06 21 24" src="https://user-images.githubusercontent.com/2011395/114658445-b4d36d00-9ce9-11eb-93ea-3eb7aa91af90.png">

Sadly I haven't used Tinkerwell for the last 11 months as could never resolve this issue and my licence has now expired.

If anyone is experiencing a similar issue or is able to replicate please let me know.

Environment details:

Tinkwerwell 2.12.1
OSX Catalina (10.15.7)
PHP 7.3 (I've tried loading up different versions in settings)

**Comment by fri3ndly** [comment]
I meant to add that in my past ticket I tried rolling back to previous versions but unfortunately could not get back far enough to 2.0.0 which did work as I could no longer download this version

**Comment by sschlein** [comment]
Have you tried the cli mode? It looks like you are using the http mode for tinkering and you don't have an output view.

**Comment by fri3ndly** [comment]
@sschlein Wow is that all it was - thanks so much
