### ISSUE TITLE
Tell windows you guys are cool?

### ISSUE THREAD

**Issue by danielme85** [beyondcode/tinkerwell-community#420]
Ya'll might wanna give Microsoft a call... I don't wanna put my computer at RISK!!!! 🙈 

![image](https://user-images.githubusercontent.com/1576219/115263539-83044100-a103-11eb-81f0-ba30bbc86910.png)

So is it safe or not? 😅

**Comment by mechelon** [comment]
Getting approved by Microsoft takes some effort and time, but we are on it. :) 
You can press "Run anyway" - HELO is safe 😇

Related to #396
