### ISSUE TITLE
Follow MacOS System Theme

### ISSUE THREAD

**Issue by n8udd** [beyondcode/tinkerwell-community#421]
As per https://github.com/beyondcode/tinkerwell-community/issues/185 customs themes are a way off yet, but it would be great if Tinkerwell would respect the System Wide theme. Select a default light and dark theme, and it toggles based on the OS theme.

**Comment by mpociot** [comment]
Which theme are you speaking of? Editor themes, or UI themes?

**Comment by n8udd** [comment]
The editor theme. 

Eg, so I could set to "Solarized Dark" when the system theme in MacOS is dark, and "Github" with the light OS theme.

**Comment by sschlein** [comment]
I'm closing this issue as we don't plan to add that anytime soon. That doesn't mean that this will never be part of Tinkerwell but it won't be in the near future.

The reason is that this requires a rewrite of the whole UI and we don't plan this for V2.
