### ISSUE TITLE
VSCode Plugin, does not work as tab in the control panel

### ISSUE THREAD

**Issue by vstyler96** [beyondcode/tinkerwell-community#426]
It would be great, to have a similar plugin in VSCode as PHPStorm, the current existing one, does not even open.

**Comment by mpociot** [comment]
Hey!

We currently don't have plans to focus on the VSCode plugin again. The current version of the plugin requires the existence of the Tinkerwell desktop app, while PHPStorm works as a stand-alone plugin and we are going to focus on the PHPStorm plugin first.
