### ISSUE TITLE
Cannot open any file

### ISSUE THREAD

**Issue by lszymkowiak** [beyondcode/tinkerwell-community#427]
Since upgrading to 2.13.0 I'm unable to open any file, either using File -> Open File or shortcut Ctrl+Shift+O.
Explorer window appears, I'm selecting the file, but nothing happens.

Version: 2.13.0
OS: Windows 10

**Comment by sschlein** [comment]
This has already been fixed and we are going to release an update very soon.

Sorry!

**Comment by lszymkowiak** [comment]
Ok, in that case I'm waiting for the update.
Thanks.

**Comment by ctorresr** [comment]
Also the Open Recent has never worked.

**Comment by mpociot** [comment]
This was fixed in 2.13.1
