### ISSUE TITLE
Save state when closing the app

### ISSUE THREAD

**Issue by klaasgeldof** [beyondcode/tinkerwell-community#43]
It would be nice if the state (current code, current working directory...) is saved when you quit the application. Sometimes what you want to test is quite a lot of code, and it sucks when you lose it. 

Laravel Web Tinker (spatie/laravel-web-tinker) does it and it think it's great. The same with Sublime for example. You can just quit the app any time, if you saved or not and never have to worry about losing anything.

**Comment by Corben78** [comment]
As several settings are saved (current code, window position), it would be great if also the working directory for that code would be saved.
Atm I have to set the working directory again after each fresh start of the App (currently 2.5.0).

**Comment by sschlein** [comment]
This has been released with 2.8.x
