### ISSUE TITLE
Ability to both ssh and execute inside docker container.

### ISSUE THREAD

**Issue by laraworx** [beyondcode/tinkerwell-community#437]
Good Day,

I would be really helpful to be able to have Tinkerwell ssh into a remote machine and then execute within a docker container.

Regards,
Andrew

**Comment by opengis** [comment]
I second this, I really love Tinkerwell but it's almost useless to me in my current setup (dev and prod)...

**Comment by laraworx** [comment]
I was hoping this would get a bit more attention as its an quick win: but for those of you wanting a work around... this is what i do:

1) create a bash file [/home/user/php]: 
----
#!/bin/bash
for i in /tmp/tinker_*; do
    docker cp $i <container_name>:$i
done
docker exec <container_name> php "$@"
----

2) In the tinkerwell ssh settings, set the 'php binary' to: /home/user/php.

All done!

**Comment by rigasyahrul** [comment]
Hi there @laraworx , i have tried your solution, but find error in tinker well, on MacBook Pro 14, OS BigSur, 

is there any step that i missed?<br>
my bash script `/home/user/php-web`
```
#!/bin/bash

CONTAINER_NAME="d67008b8652b"

for i in /tmp/tinker_*; do
    sudo docker cp $i $CONTAINER_NAME:$i
done

sudo docker exec $CONTAINER_NAME php "$@"
```

<img width="1381" alt="Screen Shot 2021-07-13 at 17 48 04" src="https://user-images.githubusercontent.com/2996881/125439461-a9384e3e-c56d-488f-bcfd-bb8473387a5c.png">

**Comment by laraworx** [comment]
Hi @rigasyahrul 

Apologies for the late reply.

I haven't used the mac version, but don't think would be different.

The scripts acts as a middle man on the remote server.... So we would place the script somewhere on the remote server.

In the tinkerwell SSH config we set the connection to the remote server and change the following settings:

Application Folder: <site dir within the container> so if you inside the container, could be something like /var/www/my-site/
PHP Binary Path: <path to bash script on the remote server>

The script basically proxies the arguments to the docker exec.

**Comment by rigasyahrul** [comment]
Hi @laraworx , 

> Application Folder: site dir within the container - so if you inside the container, could be something like /var/www/my-site/
PHP Binary Path: path to bash script on the remote server

This point that i missed. Now it is working. thank you very much. God bless you~
