### ISSUE TITLE
Cannot prettify PHP if short closures are used

### ISSUE THREAD

**Issue by squatto** [beyondcode/tinkerwell-community#439]
You can't prettify your code if short closures are used. Here's an example:

![prettify-php-short-closures](https://user-images.githubusercontent.com/748444/117503450-35c70280-af3e-11eb-88ff-a5e332bd68ba.gif)

Thanks!

**Comment by sschlein** [comment]
This is a limit of the editor that we are using and as long as the editor doesn't ship this feature, we don't have plans to add that ourselves.
