### ISSUE TITLE
JetBrains Mono font support

### ISSUE THREAD

**Issue by plakhin** [beyondcode/tinkerwell-community#441]
Despite the fact `JetBrains Mono` font is installed system-wide on Windows 10, it is not listed in Tinkerwell app.
Would be nice to have a fix.

**Comment by mpociot** [comment]
I just tried this on my Windows setup and I can not reproduce this. 

![image](https://user-images.githubusercontent.com/804684/117776620-1250d000-b23c-11eb-9a59-4a429ba36882.png)

**Comment by plakhin** [comment]
@mpociot, What version of the Font do you have installed?
This is mine:
 
![image](https://user-images.githubusercontent.com/25561058/117781434-3c71b480-b273-11eb-9418-914fbaa0abf6.png)

**Comment by plakhin** [comment]
![image](https://user-images.githubusercontent.com/25561058/117781598-64f9ae80-b273-11eb-96ee-f0862868794a.png)

**Comment by plakhin** [comment]
Updated to 2.14.0, still can't use JetBrains Mono

**Comment by plakhin** [comment]
Updated to 2.14.1, still can't use JetBrains Mono

**Comment by plakhin** [comment]
Still can't use JetBrains Mono on v2.15.0

**Comment by plakhin** [comment]
After updating `JetBrains Mono` to `v2.241` it is appeared in Tinkerwell app.

**Comment by rinodrummer** [comment]
Sorry for reopening a closed issue, but today I brought Tinkerwell and I'm having the same issue: I already had JetBrains Mono installed (manual installation) when installed Tinkerwell.

After checking that it wasn't available, I downloaded it with FontBase, but still isn't listed.

**Comment by rinodrummer** [comment]
> Seems like when one uses normal ttf fonts (not variable weight) on Windows it won't show in settings dropdown. However, I edited settings json manually and it works. Another option is to install variable width font, however this wasn't my choice due some software still doesn't support this.

I forced the font editing the file `%Appdata%\Tinkerwell\vuex.json`.
Thanks!
