### ISSUE TITLE
Ability to hide menu bar

### ISSUE THREAD

**Issue by plakhin** [beyondcode/tinkerwell-community#442]
It would be nice to have an ability to hide menu bar on Windows and show it only on `alt` key pressed.

**Comment by plakhin** [comment]
implemented in 2.14.0

**Comment by plakhin** [comment]
@mpociot after updating to 2.14.1 menu bar is always visible again

**Comment by mpociot** [comment]
We will keep the menu bar visible, as we received a lot of support requests asking why the menu bar is gone. Seems like this is not as commonly known as I thought 😅

**Comment by plakhin** [comment]
@mpociot can you please just add an option for this in settings?
