### ISSUE TITLE
No about window - aka still having trouble with auto update on ubuntu

### ISSUE THREAD

**Issue by njames** [beyondcode/tinkerwell-community#444]
I was just trying to open the about window and found it not to open (ubuntu 20.04 using appimage)
In fact it has been doing this for a while. 
I assume this is where the version is. 

I check the `Check for Updates` and yay `2.14` is available but no cigar on the auto update. 

I guess it just doesn't work for AppImage type installations

**Comment by njames** [comment]
Happy to take a zoom call to help see if this can be improved @sschlein

**Comment by mpociot** [comment]
@njames We have basically rewritten the updater in version 2.14, so hopefully this won't be the case when we release 2.14.1 / 2.15.
But I'd gladly hop on a zoom call with you to debug this further if it still exists then. Thank you for offering this! :)
