### ISSUE TITLE
Preferences shortcut on Windows

### ISSUE THREAD

**Issue by plakhin** [beyondcode/tinkerwell-community#445]
Current shortcut `win+comma` for Preferences doesn't work on Windows.
Better to change to "standard" `ctrl+comma`

v2.14.0

**Comment by mpociot** [comment]
Ah I didn't know that Ctrl+Comma is a standard shortcut for opening preferences on Windows. I'll change that in the next version!

**Comment by plakhin** [comment]
It's not a standard, but used in many software like vscode, sublime, windows terminal and others by default, so becomes a kind of "standard".
Thank you!

**Comment by plakhin** [comment]
Any updates on this?

**Comment by mechelon** [comment]
Will be updated in the next released!
