### ISSUE TITLE
[Bug] [Psy] Psy method incompatibility using PHP 7.1.33 and Laravel 5.2

### ISSUE THREAD

**Issue by vstyler96** [beyondcode/tinkerwell-community#446]
OS: Arch Linux
PHP: 7.1.33
Laravel: 5.2

Expected output: The same output like we get on tinker when we type any expression.
Obtained output: <del>An exception</del> A Fatal Error related with incompatible methods.

![image](https://user-images.githubusercontent.com/46312870/117916486-defa5980-b2ac-11eb-9005-7de22672b861.png)

> **Further Context: The common echo output works perfect**
![image](https://user-images.githubusercontent.com/46312870/117917046-ee2dd700-b2ad-11eb-8095-50d8cac8a4e1.png)

> **Further Context: The dump does not work with objects, but only arrays**
![image](https://user-images.githubusercontent.com/46312870/117917172-26351a00-b2ae-11eb-9728-9638c7ffcb87.png)
![image](https://user-images.githubusercontent.com/46312870/117917361-86c45700-b2ae-11eb-9058-0c5ba37fad49.png)

**Thanks in advance!!**

**Comment by lszymkowiak** [comment]
PHP: 7.1.33
Laravel: 5.5.27
Tinkerwell: 2.14

![image](https://user-images.githubusercontent.com/1734546/117945905-1568c080-b30f-11eb-8c9e-aaa991ad5701.png)

Works perfect with Tinkerwell 2.12.
Is there any way to prevent Tinkerwell from being updated?

**Comment by vstyler96** [comment]
> PHP: 7.1.33
> Laravel: 5.5.27
> Tinkerwell: 2.14
> 
> ![image](https://user-images.githubusercontent.com/1734546/117945905-1568c080-b30f-11eb-8c9e-aaa991ad5701.png)
> 
> Works perfect with Tinkerwell 2.12.
> Is there any way to prevent Tinkerwell from being updated?
> 

Which os is this?
And do you mean the auto-print after write?

**Comment by lszymkowiak** [comment]
> > PHP: 7.1.33
> > Laravel: 5.5.27
> > Tinkerwell: 2.14
> > ![image](https://user-images.githubusercontent.com/1734546/117945905-1568c080-b30f-11eb-8c9e-aaa991ad5701.png)
> > Works perfect with Tinkerwell 2.12.
> > Is there any way to prevent Tinkerwell from being updated?
> 
> Which os is this?
> And do you mean the auto-print after write?

The example above is from Tinkerwell on Windows 10, connecting via SSH to CentOS with Laravel 5.5 and PHP 7.1.33.
Any code run in this configuration gives the same error.

**Comment by vstyler96** [comment]
> > > PHP: 7.1.33
> > > Laravel: 5.5.27
> > > Tinkerwell: 2.14
> > > ![image](https://user-images.githubusercontent.com/1734546/117945905-1568c080-b30f-11eb-8c9e-aaa991ad5701.png)
> > > Works perfect with Tinkerwell 2.12.
> > > Is there any way to prevent Tinkerwell from being updated?
> > 
> > 
> > Which os is this?
> > And do you mean the auto-print after write?
> 
> The example above is from Tinkerwell on Windows 10, connecting via SSH to CentOS with Laravel 5.5 and PHP 7.1.33.
> Any code run in this configuration gives the same error.

Try using Tinkerwell 2.15 that same issue was resolved, at least that seems from Arch Linux.

**Comment by mpociot** [comment]
Yeah, the latest version of Tinkerwell should fix this issue 👍
