### ISSUE TITLE
Model auto-aliasing doesn't work when SSH-ing into local Homestead VM

### ISSUE THREAD

**Issue by mangrovestudios** [beyondcode/tinkerwell-community#447]
Vagrant 2.2.9
Homestead 9.5.1
Laravel 6.20.27

When I set up an SSH connection to my local VM, I can successfully connect and use Tinkerwell. However, doing a simple:

`User::first();` returns `PHP Fatal error:  Class 'User' not found in Psy Shell`

I would need to provide the full path `App\User` to make it work. Interestingly, this doesn't occur with SSH connections to remote servers. Does anyone know if this is a bug or a settings issue?

**Comment by mpociot** [comment]
The auto-aliasing depends on the given Laravel version and the existence of the `Laravel\Tinker\ClassAliasAutoloader` class in your project.
