### ISSUE TITLE
ctrl+shift+r shortcut on Linux (Fedora)

### ISSUE THREAD

**Issue by gtarcea** [beyondcode/tinkerwell-community#449]
On my Linux system (Fedora, currently 33, but also had issue on 32), ctrl-shift-r doesn't show the query. At the moment it doesn't do anything. Is there a way to map short cuts to different keys?

**Comment by roni-estein** [comment]
Mac either, this feature would be 🔥🔥🔥🔥

**Comment by allandereal** [comment]
This is the same issue on Ubuntu 18.04. @mpociot

**Comment by mpociot** [comment]
The query detection works slightly different than running normal code - so you need to add a semicolon.

This does not work:

```php
User::first()
```

While this one does:

```php
User::first();
```

Then, highlight the code and press cmd+shift+r. I'll make the code highlighting optional in a future version!
![Uploading image.png…]()

**Comment by allandereal** [comment]
@mpociot , this actually does not work on both ubuntu 18.04 and 20.04.  
I've tested it with a semicolon `;` and nothing happens when i highlight `User::first();` and press ctr+shift+r .

**Comment by gtarcea** [comment]
Same issue for me on Fedora as @allandereal is having on Ubuntu. Ctrl+shift+r is still doing nothing, whether I have a semi-colon (and the semi-colon is included in the highlighted snippet) or not.
