### ISSUE TITLE
CLI launcher to set working directory

### ISSUE THREAD

**Issue by drehimself** [beyondcode/tinkerwell-community#45]
Similar to using `subl .` or `sublime .` to open Sublime Text in the current directory

or `code .` to open VSCode in the current directory.

Something like `tinkerwell .` or `tw .` would be awesome and would totally replace my current `php artisan tinker` workflow.

**Comment by sschlein** [comment]
I'm closing this issue as we don't plan to add that anytime soon. That doesn't mean that this will never be part of Tinkerwell but it won't be in the near future.
