### ISSUE TITLE
Cursor not showing during run when using keyboard initiation

### ISSUE THREAD

**Issue by roni-estein** [beyondcode/tinkerwell-community#450]
I will often run some long queries on tinkerwell while I'm exploring real problems for tests. When running on large datasets a query might take 30 second or a minute. There is a run indicator but it's not that noticeable under the run widget at times. If I move my mouse I'll see the "running" cursor that lets me know things are processing. but if I am typing and just initiate a run [command + R] on a mac it no mouse indicator will show up with a busy cursor.

This threw me a couple of times during long running queries. Maybe just showing that mouse cursor right away when the app is busy running or some other more visible indicator would be a helpful.

I also run this in full screen on a small M1 monitor which is a bit far on the desk rather than on my main working monitor which is massive. So that might also play into why I'm finding it hard to see.

**Comment by mpociot** [comment]
> But if I am typing and just initiate a run [command + R] on a mac it no mouse indicator will show up with a busy cursor.

Hm I'm unable to reproduce this. When I'm typing something and press CMD+R, the cursor immediately becomes visible and busy for me.
Does it remain hidden for you?

**Comment by roni-estein** [comment]
Perhaps this might help, sorry about any video I'm just using basic screen cap on the apple. To explain, this is a huge database, transform and cleanup take tens of seconds or minutes. 
Occasionally I think I'm running a query but I'm not. Here is a reproduction. 

1. setup the query looking for corrupt data, and let it run.
2. on the right you'll see the old data leave the screen when it starts running. 
3. notice there is no mouse cursor with the running indicator, on the mac its a blue spinning circle with an arrow pointing tot he top left but on the video it recorded odd, I don't know why.
4. As soon as I move the mouse, the cursor comes back and gives me the proper indicator.

I don't use the mouse that much in my workflow, and its happened a couple fo times where a query I know that takes 10-15 minutes to run has gotten away from me since I apparently hit a wrong key or plain just forgot. Having something visual is helpful. Large is better, I wear glasses  and the very cool running indicator on the left which I just noticed while recording the video though it's not on it is barely noticeable.

I hope that clears up what I was describing before.


https://user-images.githubusercontent.com/8517475/119179145-324e7380-ba34-11eb-9cc2-3d7188570886.mov

**Comment by mechelon** [comment]
Thanks for the clarification. We'll discuss about improving the loading indicator in the toolbar. :)
