### ISSUE TITLE
Would love to configure my own shortcut to the run command

### ISSUE THREAD

**Issue by roni-estein** [beyondcode/tinkerwell-community#451]
Command + R is great but not my preference, would love to see this as an option to configure. [command + enter] is the sauce for me, so much muscle memory I reach for it to execute all the time.

**Comment by aryehraber** [comment]
Until this is natively possible via Tinkerwell's preferences, you can add a custom keyboard shortcut via: 

`System Preferences > Keyboard > Shortcuts > App Shortcuts`

As far as I know, this works for any app where you want to add/override a keyboard shortcut (as long as it appears in the app's menu items; File, Edit, etc.)

![Screenshot 2021-05-17 at 11 48 54](https://user-images.githubusercontent.com/5065331/118469305-e0d97800-b705-11eb-8f3d-c80974e79d20.jpg)

**Comment by roni-estein** [comment]
What!!! Nice find there! You are awesome!!!🎉😃👏

**Comment by mechelon** [comment]
Thank you, @aryehraber! :)
