### ISSUE TITLE
Keystrokes not being detected.

### ISSUE THREAD

**Issue by nckrtl** [beyondcode/tinkerwell-community#452]
Running latest version of Tinkerwell (2.14) on Mac M1 but keystrokes are not being detected. When I type nothing happens. There are no errors showing. As far as I can tell PHP is linked correctly in the settings.

Any idea what might be wrong? Already tried removing the app and reinstalling it.

**Comment by RahulDey12** [comment]
I am facing same issue with linux version as well as the windows version

**Comment by OmarZuritaEC** [comment]
I have the same problem with the app for windows.

**Comment by opengis** [comment]
Same problem here on Windows

**Comment by OmarZuritaEC** [comment]
Where can i download version 2.13?

**Comment by officialdave** [comment]
> Same problem here on Windows with version 2.14, I uninstalled 2.14 are downloaded 2.13, I confirm that 2.13 is working ok.

@opengis same. v2.14 not working. I just bought this. :( Where can I grab v2.13?

**Comment by sschlein** [comment]
Hey,

We're very sorry but there seems to be a bug in the initial tour.

If you skip the tour with ESC, the event that enables the editor doesn't fire and you can't type. Please restart the tour via Help -> restart on boarding and press the skip button. That enables the editor.


We're fixing this tomorrow!

**Comment by OmarZuritaEC** [comment]
where is the option <<Help>> ?
how do i restart on boarding?

![image](https://user-images.githubusercontent.com/1316308/118386979-03be3c00-b5e1-11eb-9603-6d36338d997e.png)

**Comment by sschlein** [comment]
Press the alt key to show the menu. This has been requested by so many people on windows that we expected this to be a standard 😩

Seems like the default should be to show the menu @mpociot

**Comment by RahulDey12** [comment]
@OmarZuritaEC @officialdave copy the download link and change the version

**Comment by sschlein** [comment]
@RahulDey12 This will trigger the auto-updater and you're running into the issue after 5 minutes again – restarting the onboarding solves this until we have a fix, sorry.

**Comment by nckrtl** [comment]
Restarting onboarding fixes it indeed. Thanks for the quick response @sschlein.

**Comment by RahulDey12** [comment]
This issue still not fixed

**Comment by mpociot** [comment]
I already fixed this for everyone that downloads the current version as well as for everyone that updates to the latest version
