### ISSUE TITLE
lost menus

### ISSUE THREAD

**Issue by njames** [beyondcode/tinkerwell-community#453]
![image](https://user-images.githubusercontent.com/491726/118423196-ce603e00-b707-11eb-8333-c47b0e9362a7.png)
I seem to have lost my menus ?!

Is there a shortcut to toggle these I might have set unintentionally?

TIA, 
Nigel

**Comment by mpociot** [comment]
Please press the alt key. I added this as a lot of people requested this and I thought it's common. Seems like I have to revert that 🙈

**Comment by njames** [comment]
Ahhh :+1: Thanks 

It is in the windows world so I just didnt know where to find it 

Keep it then ... now I know it is a good feature .
