### ISSUE TITLE
Menu options unresponsive in 2.14 (AppImage)

### ISSUE THREAD

**Issue by nkabiru** [beyondcode/tinkerwell-community#456]
After updating to 2.14, most menu options are unresponsive when clicked on.

#### Tinkerwell

- About
- Preferences
- Manage License
- Check for Updates
- Hide Tinkerwell
- Show Others
- Show All

#### File
- Save File

#### Tinker Mode
- (All Menu Items)

#### Action 
- (All Menu Items)

#### View
- Add Tab
- Increase Font Size
- Decrease Font Size
- Toggle Toolbar
- Toggle Output

#### Help
- Show latest MOTD
- Restart Onboarding

## Sidebar

- Connect to SSH
- Set Working Directory

## Steps to Reproduce

- Restart Tinkerwell 2.13 after  'restart to update' notification is sent

## What I've tried

- Clearing config files in home directory (The editor became unresponsive after this step)
- Reinstalling Tinkerwell 2.14 
- Reinstalling Tinkerwell 2.13 **(Works)**

# Machine Specifications

- Manjaro Linux
- Kernel 5.9.16-1-MANJARO
- Laravel Homestead 11.0.0

My temporary fix is to revert to 2.13, but I can't prevent the auto-update. I was unable to find the error log for this problem and the debug log only had data on updates (before I cleared the config). Any help would be appreciated.

**Comment by mpociot** [comment]
We just released Tinkerwell 2.14.1 that fixes thi issue
