### ISSUE TITLE
Comment code key shortcut won't work with VIM mode

### ISSUE THREAD

**Issue by ricardohs35** [beyondcode/tinkerwell-community#458]
Steps to reproduce:

1. Activate VIM mode.
2. Try to comment a line of code with `cmd + /`.
3. Keybind won't work.

Although, this works well with VIM mode `turned off`.

**Comment by sschlein** [comment]
Hey, this is a shortcut that only works with Sublime Text Keybindings. VIM has no easy comment/uncomment shortcut per default.
