### ISSUE TITLE
Typing is working or showing any text

### ISSUE THREAD

**Issue by mohkoma** [beyondcode/tinkerwell-community#459]
I just installed the App for the first time, I added the Licence but I can't type anything, I tried to reinstall it, I have checked all the issues posted on Github but I still can't solve it.
I have it in MacBook Pro 2020 BigSur.

**Comment by sschlein** [comment]
Hey – can you please go to Help -> Restart Onboarding and press skip?

It seems like there are still ways do get trapped into this mode..

**Comment by mohkoma** [comment]
Thank you! that was exactly the reason for that
