### ISSUE TITLE
Option to use Cmd+Enter to Run code (MacOS)

### ISSUE THREAD

**Issue by pwrdk** [beyondcode/tinkerwell-community#460]
Option to use Cmd+Enter to Run code (MacOS)

**Comment by sschlein** [comment]
Hi – we don't have plans for that but someone has posted a workaround that you can use:

https://github.com/beyondcode/tinkerwell-community/issues/451

**Comment by pwrdk** [comment]
Brilliant - thank you, and sorry for the mixup :)

---

Med venlig hilsen / best regards
Peter Wærum
