### ISSUE TITLE
Shortcut for quit on Linux doesn't work anymore

### ISSUE THREAD

**Issue by Corben78** [beyondcode/tinkerwell-community#467]
Looks like with one of the recent updates, the standard shortcut for quitting applications on Linux doesn't work anymore.

ctrl + q normally quits applications on Linux (like alt + f4 does on Windows).

Please restore this behavior (e.g. Invoker 2.5.0 still does quit on ctrl + q).

**Comment by thiagobraga** [comment]
I confirm this problem. It also happens to me.
<kbd>Alt</kbd> + <kbd>F4</kbd> works on Ubuntu, but the others not, like:

<kbd>Ctrl</kbd> + <kbd>T</kbd>
<kbd>Ctrl</kbd> + <kbd>W</kbd>
<kbd>Ctrl</kbd> + <kbd>Q</kbd>

Ubuntu 20.04.2 LTS
Using latest Tinkerwell.

**Comment by mechelon** [comment]
Will be fixed in the upcoming release, tested with Ubuntu 20.04.2.
