### ISSUE TITLE
Context menu does not update when switching tabs

### ISSUE THREAD

**Issue by wunc** [beyondcode/tinkerwell-community#468]
**Issue**: When multiple tabs are open, each to a different project, the context menu only reflects the last opened working directory, not the working directory of the currently-focused tab.

**Steps to reproduce**:
- Open tab 1 and set a working directory (e.g. to a Laravel 7 project)
- View context menu (should show Laravel v7 identified)
- Open tab 2 and set a different working directory (e.g. to a Laravel 8 project)
- View context menu (should show Laravel v8 identified)
- Click on tab 1
- View context menu (should show Laravel v7, but still shows Laravel v8)

 It would be nice if the context menu updated to the proper customizations for the working directory of the focused tab when switching to that tab. In practice, this isn't a big deal when opening two Laravel projects, but if the tab 2 project is a non-Laravel project then after opening it you lose all the Laravel-specific context menu items in tab 1.

This is for my installation of Tinkerwell 2.15.0 on macOS 11.3.

**Comment by mechelon** [comment]
Thank you for pointing this out. The bug will be fixed in the next release!
