### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Manager' not found in

### ISSUE THREAD

**Issue by bilalusean** [beyondcode/tinkerwell-community#470]
**Reproduce Information:**

Tinkerwell version: 2.15.0
Magento version: 2.4.2 CE
PHP version: 7.4.13
OS: Ubuntu 18.04.3 LTS

I have downloaded the Tinkerwell from this [link](https://tinkerwell.app/).

I have opened Tinkerwell by below command.

    $ ./Tinkerwell-2.15.0.AppImage

After that, I set Magento 2 root folder as the working directory in the Tinkerwell. I'm getting the below error while running the code.

`PHP Fatal error:  Uncaught Error: Class 'Manager' not found in phar:///tmp/.mount_TinkerocPNu4/resources/tinkerwell/tinker.phar/src/Drivers/Magento2TinkerwellDriver.php:36
Stack trace:
#0 phar:///tmp/.mount_TinkerocPNu4/resources/tinkerwell/tinker.phar/index.php(39): Magento2TinkerwellDriver->bootstrap()
#1 /tmp/.mount_TinkerocPNu4/resources/tinkerwell/tinker.phar(12): require('phar:///tmp/.mo...')
#2 {main}
  thrown in phar:///tmp/.mount_TinkerocPNu4/resources/tinkerwell/tinker.phar/src/Drivers/Magento2TinkerwellDriver.php on line 36`

![tinkerwell](https://user-images.githubusercontent.com/20036350/123509275-1b81e900-d692-11eb-87c1-18b611d3047c.png)

Please check and advise me. Thanks.

**Comment by bilalusean** [comment]
For a quick fix, I have fixed this issue like below. 

I observed something is wrong with the driver class based on the error I posted above. I found we can create a custom driver class in this [documentation](https://beyondco.de/docs/tinkerwell/extending-tinkerwell/custom-drivers).

I found the Magento driver class here https://github.com/tinkerwellapp/drivers/blob/master/src/Drivers/Magento2TinkerwellDriver.php

I have created a folder .tinkerwell
I created a php file **CustomTinkerwellDriver.php** inside .tinkerwell folder.
I have copied the content from **Magento2TinkerwellDriver.php** to **CustomTinkerwellDriver.php**
Restart the Tinkerwell

Now it is running fine. 
![tinkerwell-1](https://user-images.githubusercontent.com/20036350/123509149-8121a580-d691-11eb-8374-16460f6f9347.png)


I hope it helps.

**Comment by keevitaja** [comment]
yeah, got it working with that.

**Comment by bilalusean** [comment]
any updates on this?

**Comment by mechelon** [comment]
We will ship an updated Magento Driver with the upcoming release.
