### ISSUE TITLE
Line numbers are incorrect when there are comment lines

### ISSUE THREAD

**Issue by mertasan** [beyondcode/tinkerwell-community#475]
<img width="881" alt="screenshot 103" src="https://user-images.githubusercontent.com/13007665/128825098-029d63a6-ff73-4a12-9435-3835d476ac43.png">

**Comment by mpociot** [comment]
Yeah, I'm afraid this is more or less a feature that we can't/won't fix. 
The comments get stripped out from the evaluated code, as they might lead to invalid evaluation results - especially when the last line is commented out
