### ISSUE TITLE
Tinkerwell doesn't show any result via SSH

### ISSUE THREAD

**Issue by fahu** [beyondcode/tinkerwell-community#476]
Hi there,

I'm trying to use Tinkerwell for Magento 2.4.3 via remote SSH to a server running Ubuntu 20.04. I was able to establish an SSH connection but it never returns a proper result (just a blank screen).

Tinkerwell is running on MacOS Big Sur (11.5.1) and additionally I have IntelliJ Ultimate installed.

Additionally I don't see any error message that would point me to the issue.
![image](https://user-images.githubusercontent.com/2507037/129544239-0ba828ee-4a71-4b6d-b30b-5bb3ed34c8bb.png)

Help is highly appreciated :)

**Comment by mechelon** [comment]
We already have a an issue that is maybe related to this. Thank you for pointing this out, we're working on it!

**Comment by mechelon** [comment]
This should be fixed in the upcoming release, please reopen if this is not the case.

**Comment by fahu** [comment]
Hey @mechelon  that's great news! What version will the upcoming release be?
