### ISSUE TITLE
Fatal error: [FILE] already exists in Psy Shell code on line

### ISSUE THREAD

**Issue by LucasDoro** [beyondcode/tinkerwell-community#477]
Hi!

I bought tinkerwell license. However, when I try to run in my laravel 8 project, I get the result:

![Captura de Tela 2021-08-16 às 06 59 38](https://user-images.githubusercontent.com/1340350/129546452-20d60bc5-533e-48da-ba7f-c0c93f07cd1d.png)

I bought tinkerwell's license. However, when I try to run in my laravel 8 project, I get the result

saw this there is #285 no solution?

My settings:
![Captura de Tela 2021-08-16 às 07 02 38](https://user-images.githubusercontent.com/1340350/129546893-5f2a125a-8833-404d-9161-3cf947446a3e.png)

Thx!

**Comment by mechelon** [comment]
From the code you provided here I assume that you're defining a class that's already existing somewhere in your Laravel project.
Can you try the following code in Tinkerwell and see what happens:

```php
$action = new App\Domain\Room\Actions\GetCompaniesToExclusiveHoursAction();

get_class($action);
```

**Comment by mechelon** [comment]
I will close this issue due to inactivity.

If this issue still exists, feel free to reopen and, if applicable, provide more details.
