### ISSUE TITLE
Custom-written Aritisan commands not available

### ISSUE THREAD

**Issue by ksorbo** [beyondcode/tinkerwell-community#479]
When I right-click and select Artisan, none of my custom commands are listed. Only built-in. Commands from installed additional packages are not available either.

Surely this wouldn't be too hard to implement.

Using version 2.15.0

**Comment by mechelon** [comment]
Thank you for pointing this out.
This is because the Drivers aren't loaded when connecting via SSH (which Homestead is as well, basically). 
I will add this to our short-term feature list.

Thank you!

**Comment by mechelon** [comment]
Will be available in the upcoming release!

**Comment by ksorbo** [comment]
Just got the latest update and custom artisan commands are now working.

Thanks.
