### ISSUE TITLE
[Feature Request]: Connect to a kubernetes clusters (k8s)

### ISSUE THREAD

**Issue by ajcastro** [beyondcode/tinkerwell-community#480]
### Feature Description

Is there a way to connect tinkerwell to a kubernetes cluster? We are using linode kubernetes cluster and I want to connect tinkerwell to it.

### Is this feature valuable for other users as well and why?

Yes. Because lots of people are using kubernetes.

**Comment by sschlein** [comment]
Hi @ajcastro 

thank you for your feature request. We don't have this on the short-term roadmap and I don't think that we are going to implement this feature this year. So don't take this as a "no" forever but I'm closing the issue for now.

Thanks, Sebastian
