### ISSUE TITLE
[Bug]:  Tinkerwell does not work with laravel 5.4 and PHP 7.1

### ISSUE THREAD

**Issue by MarlonEtiene** [beyondcode/tinkerwell-community#483]
### Operating system

Ubuntu 18.04

### Laravel Version

Laravel Framework 5.4.36

### PHP Version

PHP 7.1.33-40+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug 26 2021 15:55:30) ( NTS )

### Project Location

Local

### Bug description

Tinkerwell no work in any of my projects with laravel 5.x and php 7.1.x
The `php artisan tinker` works normally

I have double checked my tinkerwell configuration.

### Steps to reproduce

I just open a laravel project (CTRL+ O) in version 5.x, with PHP 7.1.x

### Relevant log output

```shell
PHP Fatal error:  Declaration of _PhpScoperc223a629f245\Psy\Output\ShellOutput::doWrite($message, $newline) must be compatible with _PhpScoperc223a629f245\Symfony\Component\Console\Output\Output::doWrite(string $message, bool $newline) in phar:///tmp/.mount_Tinkerqa1H7B/resources/tinkerwell/tinker.phar/vendor/psy/psysh/src/Output/ShellOutput.php on line 8
PHP Stack trace:
PHP   1. {main}() /tmp/.mount_Tinkerqa1H7B/resources/tinkerwell/tinker.phar:0
PHP   2. require() /tmp/.mount_Tinkerqa1H7B/resources/tinkerwell/tinker.phar:12
PHP   3. _PhpScoperc223a629f245\Psy\Configuration->getPresenter() phar:///tmp/.mount_Tinkerqa1H7B/resources/tinkerwell/tinker.phar/index.php:143
PHP   4. _PhpScoperc223a629f245\Psy\Configuration->getOutput() phar:///tmp/.mount_Tinkerqa1H7B/resources/tinkerwell/tinker.phar/vendor/psy/psysh/src/Configuration.php:483
PHP   5. spl_autoload_call() phar:///tmp/.mount_Tinkerqa1H7B/resources/tinkerwell/tinker.phar/vendor/psy/psysh/src/Configuration.php:355
PHP   6. Composer\Autoload\ClassLoader->loadClass() phar:///tmp/.mount_Tinkerqa1H7B/resources/tinkerwell/tinker.phar/vendor/psy/psysh/src/Configuration.php:355
PHP   7. Composer\Autoload\includeFile() phar:///tmp/.mount_Tinkerqa1H7B/resources/tinkerwell/tinker.phar/vendor/composer/ClassLoader.php:322
PHP   8. include() phar:///tmp/.mount_Tinkerqa1H7B/resources/tinkerwell/tinker.phar/vendor/composer/ClassLoader.php:444

In ShellOutput.php line 8:
                                                                               
  Declaration of _PhpScoperc223a629f245\Psy\Output\ShellOutput::doWrite($mess  
  age, $newline) must be compatible with _PhpScoperc223a629f245\Symfony\Compo  
  nent\Console\Output\Output::doWrite(string $message, bool $newline)
```

**Comment by sschlein** [comment]
Hey,

we tried to email you multiple times but our emails aren't accepted from your mail server, so we closed the ticket.

This is the email:

Hey,

unfortunately, Tinkerwell 2.10 has no way to disable the auto-updater and so it will overwrite your app again every time you install it.

I have attached 2 phar files. Please use the latest Tinkerwell version (2.16) and replace both phar files in them. After that, you can skip updates and it will work with PHP 7.1 again. The current version requires PHP 7.2.

The phar files is in the app image and based on your logs, the path is at /tmp/.mount_Tinker4tjdqR/resources/

Best regards,
Sebastian

**Comment by sschlein** [comment]
please let me know when you've downloaded the file
[phar.zip](https://github.com/beyondcode/tinkerwell-community/files/7185310/phar.zip)

**Comment by MarlonEtiene** [comment]
Hello,

Again I'm going to ask you for help... It seems that you don't really like to help, after someone buys a license of your products.
I've already answered this email 2 times and you didn't reply back, and you received the email because I received the delivery status notification from the provider.
So, once again, here's my answer:

I didn't find on my computer, the way
`/tmp/.mount_Tinker4tjdqR/resources/`

I have no clue where this path is.

I await your return.

**Comment by sschlein** [comment]
As mentioned above, your provider blocks our emails and we can't email you. It seems that the product is not a good fit for you and I'd like to give you a refund.

**Comment by sschlein** [comment]
Which I did a minute ago
