### ISSUE TITLE
[Feature Request]: Re-open closed tab

### ISSUE THREAD

**Issue by Corben78** [beyondcode/tinkerwell-community#485]
### Feature Description

Provide the possibility to restore a closed tab.

As known from other programs (browsers, editors),  being able to re-open the last tabs with a shortcut like ctrl + shift + t would fit into the workflow of other programs people are used to.

As ctrl + shift + t is already used for switching to tinkermode: table in tinkerwell, my suggestion would be to use ctrl + shift + n (in conjunction with #484 to use ctrl + n for opening a new tab instead of ctr + t)

### Is this feature valuable for other users as well and why?

It happens that tabs are closed accidentally, so being able to re-store a closed tab would save a lot of time. Especially with the current convenience that tabs with the current code are restored when tinkerwell is opened again, it does cost quite some time to a) set the working directoy again and b) rewrite the code to tinker with.

**Comment by mechelon** [comment]
We will release a history feature in the next release that will allow you to restore used code. If you still think reopening tabs is useful for another reason, feel free to reopen.
