### ISSUE TITLE
[Feature Request] : Manage Snippet

### ISSUE THREAD

**Issue by SupianIDz** [beyondcode/tinkerwell-community#486]
### Feature Description

I'm not good at explaining it, but I can give a good example for the feature :[Tinkerun]( https://github.com/tinkerun/tinkerun)

### Is this feature valuable for other users as well and why?

By being able to store and manage snippets, users can use the code repeatedly, such as changing passwords, without having to rewrite it because the previous code was replaced by another.

Indeed in tinkerwell there are tabs, but it's not easy to go back to the old snippet, because there is no naming on the tab, even worse, the tab was closed accidentally.

**Comment by mechelon** [comment]
We are already working on this, coming soon. 😋
