### ISSUE TITLE
[Bug]: Upgrade cycle loop

### ISSUE THREAD

**Issue by Blackpig** [beyondcode/tinkerwell-community#489]
### Operating system

macOS Catalina 10.15.7

### Laravel Version

 v8.*

### PHP Version

7.38

### Project Location

Local

### Bug description

I've just renewed my Tinkerwell license.

I'm stuck in an upgrade cycle from 2.14 - it attempts to download 2.17.  Restarts Tinkerwell after 'applying' the upgrade and then presents me with the Upgrade dialog again as I'm still on 2.14

<img width="285" alt="Tinkerwell_-_Default" src="https://user-images.githubusercontent.com/1029317/134190344-6cc6d645-cb5b-4c14-86da-933403737779.png">

<img width="671" alt="Tinkerwell_-_Default" src="https://user-images.githubusercontent.com/1029317/134190484-8b618fea-e629-42f3-8aac-2901e7d6b7f8.png">

**Comment by sschlein** [comment]
Can you please log in into your Beyond Code account and download the new version manually? 

https://beyondco.de/licenses/tinkerwell

That sometimes happens and instead of debugging this with you for an hour, it might be easier to just replace the current version :-)
