### ISSUE TITLE
 Fatal error: Uncaught PharException: SHA1 signature could not be verified

### ISSUE THREAD

**Issue by shafiramaki** [beyondcode/tinkerwell-community#490]
### Operating system

windows

### Laravel Version

8

### PHP Version

7.4.19

### Project Location

Remote (Server)

### Bug description

Fatal error: Uncaught PharException: phar "/tmp/tinker_compressed.phar" SHA1 signature could not be verified: broken signature in /tmp/tinker_compressed.phar:10
Stack trace:
#0 /tmp/tinker_compressed.phar(10): Phar::mapPhar()
#1 {main}
  thrown in /tmp/tinker_compressed.phar on line 10

**Comment by mechelon** [comment]
Can you delete the file `/tmp/tinker_compressed.phar` on the remote server and try it again?
