### ISSUE TITLE
[Bug]: KeyParseError for ed25519 SSH keys

### ISSUE THREAD

**Issue by pxlrbt** [beyondcode/tinkerwell-community#493]
### Operating system

macOS Big Sur 11.6

### Laravel Version

v6.0

### PHP Version

PHP 8.0.8 (cli) (built: Jul 12 2021 02:58:53) ( NTS )

### Project Location

Remote (Server)

### Bug description

When trying to create a new SSH connection with an ed25519 SSH key, I get the following error:
> KeyParseError: Failed to parse (unnamed) as a valid auto format key: bcrypt_pbkdf function returned failure, parameters invalid

### Steps to reproduce

- Create new SSH Connection
- Select an ed25519 SSH Key
- Press "Save changes"

**Comment by mechelon** [comment]
I just tried this (Monterey) and I was able to connect to a server with a regular ed25519 key. Are you sure the key has the right format + uses the right passphrase?

**Comment by pxlrbt** [comment]
Hm. Not sure what changed, but currently it's working for me, too. Also on Monterey now. I'll test a little more the next days, but close this for now.
