### ISSUE TITLE
connecting to forge via SSH getting the below error

### ISSUE THREAD

**Issue by shafiramaki** [beyondcode/tinkerwell-community#495]
### Operating system

windows

### Laravel Version

8.x

### PHP Version

8

### Project Location

Remote (Server)

### Bug description

![tinkerwell](https://user-images.githubusercontent.com/35919418/137849868-3790245e-d27d-440c-a58a-be8725800f2f.PNG)

**Comment by mechelon** [comment]
Closed due to #490
