### ISSUE TITLE
Support SSH agent for authentication

### ISSUE THREAD

**Issue by paneidos** [beyondcode/tinkerwell-community#50]
It is currently not possible to use e.g. Yubikeys or GPG keys for authentication, because these keys are only available through an SSH agent. It also means the passphrase of the key is not stored anywhere.

**Comment by skeemer** [comment]
This is a critical feature for me. I have all of my private keys stored in KeePassXC and only exposed to the system via SSH agent. My SSH config points to the public keys which is enough to pull from the agent when my KeePassXC database is unlocked.

It would also be really nice to just enter the name specified in the config to connect to a server like I do in Transmit/CyberDuck.

**Comment by nickaguilarh** [comment]
Is this feature considered to be release any time soon? 
At the place I work we can only connect to remote instances using a Yubico Key and the only missing feature for me is the ability to use the running ssh agent.

Would be really nice to have this feature.

**Comment by sschlein** [comment]
I'm closing this issue as we don't plan to add that anytime soon. That doesn't mean that this will never be part of Tinkerwell but it won't be in the near future.
