### ISSUE TITLE
[Bug]: Not executing script on remote server

### ISSUE THREAD

**Issue by nnerijuss** [beyondcode/tinkerwell-community#502]
### Operating system

macOS 12.0.1 monterey

### Laravel Version

v8

### PHP Version

php8

### Project Location

Remote (Server)

### Bug description

When executing any script for example `echo "test"` tinkerwell do not execute it - loader icons spins under 'run' button for a long time and nothing happens

### Steps to reproduce

1. Connect to remote server
2. Try to execute php script

**Comment by mechelon** [comment]
Could you share the output of the following command, when connected via SSH to the server you're trying to evaluate code on:

ls -la /tmp/*.phar

This should show all PHAR files and their file permissions. Maybe that's where you run into issues.

**Comment by nnerijuss** [comment]
Yeh I know where is the problem. My whole development team work on one workstation, and we are using separate users to connect to ssh server. In tmp directory I can see my colleague(andrius) tinkerwell_compressed.phar file, and my user is 'nerijus'. Is there any way to solve this problem, that at the same time more than one user could connect to the server via ssh ?

```
-rw-rw-rw- 1 andrius andrius 592903 Nov 12 10:47 /tmp/tinker_compressed.phar
```

**Comment by nnerijuss** [comment]
@mechelon can we expect fix any time soon ? Software with this bug is absolutely unusable.

**Comment by nnerijuss** [comment]
Is there anything I could help with fixing this ?

I bought licences of all my team members, but we can not work with Tinkerwell, until this problem is not fixed.

**Comment by mechelon** [comment]
We're currently working on a fix for this, will be available in one of the next releases.

**Comment by mechelon** [comment]
Integrated in 2.19.0
