### ISSUE TITLE
[Bug]: PHP 8.1 and Enums

### ISSUE THREAD

**Issue by verschuur** [beyondcode/tinkerwell-community#505]
### Operating system

macOS Catalina 10.15.7

### Laravel Version

v8.x

### PHP Version

PHP 8.1.0, build: Nov 28 2021 04:13:56

### Project Location

Local

### Bug description

When defining an Enum, the output contains an error

```
enum Status: string
{
    case DRAFT = 'draft';
    case PUBLISHED = 'published';
    case ARCHIVED = 'archived';
}

echo Status::PUBLISHED->value;
```

(example taken from [stitcher](https://stitcher.io/blog/php-enums))

**Expected**
`published`

Actual
```
TypeError: _PhpScoperc223a629f245/PhpParser/Lexer::getNextToken(): Return value must be of type int, null returned

Warning: Undefined array key 336 in phar:///Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 198
```

**Tinkerwell version used**: 2.18.1

I saw there was already an older, similar [bug](https://github.com/beyondcode/tinkerwell-community/issues/414) reported. Now that PHP 8.1 is out, any updates on when Tinkerwell gets 8.1 compatibility?

### Steps to reproduce

1. Start Tinkerwell
2. Run the code from the bug description above.

**Comment by mechelon** [comment]
Tinkerwell will receive PHP 8.1 support in the next release, so I'll close this for now :)
