### ISSUE TITLE
[Bug]: PHP 8.1 and dump()

### ISSUE THREAD

**Issue by tmrouse** [beyondcode/tinkerwell-community#506]
### Operating system

Windows 10 Pro 20H2 19042.1348

### Laravel Version

v8.73.2

### PHP Version

PHP 8.1.0, built: Nov 25 2021 20:21:44

### Project Location

Remote (Server)

### Bug description

When using the `dump()` function an error is thrown

```
dump([]);
```

**Expected:**

```
[]
=> []
```

**Actual:**

```
Symfony\Component\ErrorHandler\Error\FatalError 

During inheritance of ArrayAccess: Uncaught _PhpScoperc223a629f245\Psy\Exception\ErrorException: PHP Deprecated:  
Return type of _PhpScoperc223a629f245\Symfony\Component\VarDumper\Cloner\Data::offsetExists($key) should either be 
compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used 
to temporarily suppress the notice in phar:///tmp/tinker_compressed.phar/vendor/symfony/var-dumper/Cloner/Data.php 
on line 99 in phar:///tmp/tinker_compressed.phar/vendor/symfony/var-dumper/Cloner/Data.php:99

3▕ namespace _PhpScoperc223a629f245\Symfony\Component\VarDumper\Cloner;
      4▕ 
      5▕ use _PhpScoperc223a629f245\Symfony\Component\VarDumper\Caster\Caster;
      6▕ use _PhpScoperc223a629f245\Symfony\Component\VarDumper\Dumper\ContextProvider\SourceContextProvider;
  ➜   7▕ class Data implements \ArrayAccess, \Countable, \IteratorAggregate
      8▕ {
      9▕     private $data;
     10▕     private $position = 0;
     11▕     private $key = 0;

Whoops\Exception\ErrorException 
```

### Steps to reproduce

1. Open Tinkerwell
2. Run locally or Connect to remove server Ubuntu 18.04.2 (Both have the same issue due to PHP 8.1)
3. Run the code snippet above

**Comment by mechelon** [comment]
Tinkerwell will receive PHP 8.1 support in the next release, so I'll close this for now :) If the problem still exists, feel free to reopen.

**Comment by BramVanBerkel** [comment]
PHP 8.1 has been released for a few days now, when is the release planned?

**Comment by renoirtech** [comment]
Hello, any update on this issue?

**Comment by Vercoutere** [comment]
@tmrouse can you reopen this issue?

**Comment by mpociot** [comment]
Did you try this with the latest available Tinkerwell version?

**Comment by ccc-developer** [comment]
> Did you try this with the latest available Tinkerwell version?

Getting the same report in Ray. 
Running Mac OS X 11.6.2
Tinkerwell Version 2.21.0 (2.21.0)
PHP 8.1.2

![tinkerwell-2-21-0](https://user-images.githubusercontent.com/45178131/153500700-bd5dfd14-6d0a-41f4-afb5-59d2f8e46d5a.png)

**Comment by hotmeteor** [comment]
+1

**Comment by gander** [comment]
#548

**Comment by jjjrmy** [comment]
Still having this issue. Any updates? It's kinda annoying.

**Comment by sschlein** [comment]
I just tested it with Tinkerwell 2.24 and it works with PHP 8.1.4. Please make sure you are on the latest Tinkerwell version.
