### ISSUE TITLE
[Feature Request]: Clone connection

### ISSUE THREAD

**Issue by gander** [beyondcode/tinkerwell-community#507]
### Feature Description

"In SSH Connections" allow clone connections to speedup adding similar connections.

**Comment by sschlein** [comment]
I'm closing this issue as we don't plan to add that anytime soon. That doesn't mean that this will never be part of Tinkerwell but it won't be in the near future.

**Comment by gander** [comment]
> Ohh ohh and a copy or duplicate connection button which will save you having to pick your ip or ssh key
_Originally posted by @njames in https://github.com/beyondcode/tinkerwell-community/issues/270#issuecomment-665387877_

> For a small client I have multiple environments running from a single server so the SSH connections are identical except for `App Folder`. Having a `Duplicate` button where the new label is `Copy of <original>` would be handy.
_Originally posted by @c17r in https://github.com/beyondcode/tinkerwell-community/issues/239#issue-645590596_

There are at least 3 people who reported a need for this feature. Still not enough? How many people have to write about it?
