### ISSUE TITLE
[Feature Request]: Export and Import connections

### ISSUE THREAD

**Issue by gander** [beyondcode/tinkerwell-community#508]
### Feature Description

Allow export and import configured SSH Connections. This allows backup configuration, share connections with teammates, and speedup making many similar connections by copy-paste (alternative solution for #507).

### Is this feature valuable for other users as well and why?

Backup and share connections.

**Comment by sschlein** [comment]
I'm closing this issue as we don't plan to add that anytime soon. That doesn't mean that this will never be part of Tinkerwell but it won't be in the near future.

**Comment by gander** [comment]
@sschlein where is the list of what are you planning to do so that I don't waste any more time?

**Comment by sschlein** [comment]
Thank you for your contributions!

We don't have an official roadmap and decide this on the go. Mostly based on the things that we like to have for us 😅

**Comment by gander** [comment]
Since you are selling and not making available for free, you must not be deaf to the needs of your customers.

I have purchased a license. I say what else would be useful for me in this application. You tell me "but I don't need it, so it won't be." WTF?

**Comment by sschlein** [comment]
We are not deaf to our customers but carefully decide how important a feature is and how much business value it has. We are the ones that have to maintain every new line of code for years and this is why we decide against most requests.

**Comment by gander** [comment]
Okay, maybe **Import and Export** are not having business value. But what you have at Invoker, #507, so I guess it has business value, suddenly it's not in another similar product? Explain it to me, please.

**Comment by gander** [comment]
@bilfeldt They created this repository for users to report bugs and propose new ideas. Configuration export and import is one of the most basic functionalities. I was surprised it wasn't there yet, so I suggested it. And what the answer is, you can see above. Lots of people report "we need it" but the developers of the software say "but we don't". When creating software with the purpose of selling a license, there is no such thing as "we ignore customers and do only what we like."

**Comment by bilfeldt** [comment]
> @bilfeldt We do have a Forge import :) You can add your Forge API key under "Settings / Advanced". This will instruct Tinkerwell to automatically import all of your Laravel Forge sites.

I kind of feel like it's my birthday just now @mpociot  🥳 For my next birthday I wish for the ability to add multiple Forge API keys 🤣

**Comment by comes** [comment]
> It would be super cool with an export/import option when changing to a new Mac instead of having to manually recreate all of them manually 😆 But hey, an import from Forge would also be super cool 😉

Why not copy some files from `~/Library/Application Support/Tinkerwell`? or share some of them in a private accessible github repo? The `vuex.json` file seams to be very interesting.

just an idea...

Btw, @mpociot, storing the `passphrase` of the ssh key in clear text is maybe not a good idea. It is, from my point of view, a super bad idea! Maybe you find another solution for this. Maybe you can store this kind of informations in the apple key ring or crypt them with some sort of algorithm.

all the best, J.
