### ISSUE TITLE
[Feature Request]: Moonlight Theme

### ISSUE THREAD

**Issue by SupianIDz** [beyondcode/tinkerwell-community#538]
### Feature Description

Hi, can you add Moonlight theme and Material Lighter theme like Material Theme plugins for Jetbrains IDE ?

<img width="1440" alt="Screen Shot 2022-01-22 at 20 25 20" src="https://user-images.githubusercontent.com/37969970/150638533-25ca075c-7c3b-4469-9f49-00b70d741eea.png">

### Is this feature valuable for other users as well and why?

Moonlight dark theme is more comfortable than Dracula in my opinion.

Thanks

**Comment by sschlein** [comment]
We'll implement a full skin system in Tinkerwell 3.x and you'll be able to add custom themes on your own. We have no plans adding this to Tinkerwell 2.x and so I am closing this issue for now.

Tinkerwell 3 will be ready soon.
