### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by simoebenhida** [beyondcode/tinkerwell-community#539]
### Operating system

Mac m1

### Laravel Version

v8

### PHP Version

8.1

### Project Location

Local

### Bug description

Vapor env is empty! 

<img width="867" alt="Screen Shot 2022-01-25 at 18 25 09" src="https://user-images.githubusercontent.com/19809072/151027496-d02bd47a-bd98-4dc1-8d43-3e61584b62de.png">

**Comment by cyrodjohn** [comment]
@simoebenhida How did you resolve this?
