### ISSUE TITLE
[Bug]: Vapor Environments Not Appearing

### ISSUE THREAD

**Issue by cyrodjohn** [beyondcode/tinkerwell-community#549]
### Operating system

MacOS Monterey 12.1

### Laravel Version

8.82.0

### PHP Version

PHP 8.1.2

### Project Location

Local

### Bug description

<img width="645" alt="Screen Shot 2022-02-10 at 11 43 35 AM" src="https://user-images.githubusercontent.com/509760/153334013-99ef7f87-0650-4fe8-935b-ee6126b5a957.png">

Vapor environments not showing up

**Comment by mpociot** [comment]
Are you using the latest Tinkerwell version?

**Comment by cyrodjohn** [comment]
Yup 2.21.0

**Comment by vbudkins** [comment]
I have same issue on version 2.22.0 (macOS, Big Sur, Intel)

**Comment by JohnOakwood** [comment]
Not working on MacBook Pro (13-inch, M1) Version 2.22.0

**Comment by OKrisss** [comment]
Got the same issue - not working on v.2.22.0 (macOS, Big Sur, Intel)

**Comment by cyrodjohn** [comment]
It appears to be fixed now. thanks
