### ISSUE TITLE
[Bug]: Latest version unusable over SSH connection

### ISSUE THREAD

**Issue by digiservnet** [beyondcode/tinkerwell-community#551]
### Operating system

Win 10 Pro

### Laravel Version

6.18.43

### PHP Version

7.3.33

### Project Location

Somewhere else (please specify in the description!)

### Bug description

Connecting via an SSH connection to a docker container, the latest version throws an error.

These screenshots are connected exactly the same, the only change is Tinkerwell 2.20.0 to 2.21.0.

![image](https://user-images.githubusercontent.com/57901585/153565005-41fa9ee9-f4ae-4d9d-b51d-40273c4288f7.png)

![image](https://user-images.githubusercontent.com/57901585/153565023-bc73909f-b294-4622-9ad4-53af4e28a343.png)

### Steps to reproduce

Using Tinkerwell 2.21.0, create an SSH connection and try to run some (any) PHP code.

**Comment by digiservnet** [comment]
This issue still prevails in 2.22.0.

**Comment by sschlein** [comment]
How do you connect to your application? There is no general SSH problem and it is somehow related to your setup

**Comment by digiservnet** [comment]
SSH running in a docker container.
Container running under WSL2 on Win10 Pro
Tinkerwell running in Windows (native Windows version).

Something definitely changed in Tinkerwell. I've used this setup for ages (in fact, added SSHd in the docker container (only for local dev) _just_ for Tinkerwell as it won't connect to Docker through WSL by default and the rendering isn't great using the Linux AppImage through X410 X tunnel).

As can be seen in the above screenshots though, it works just fine in 2.19.0 (and multiple versions before that).

These are my SSH config settings.
![image](https://user-images.githubusercontent.com/57901585/154495571-16c76697-02c3-40d6-80c2-e87e8c4eead4.png)

I know it's an old Laravel instance and PHP version (something I'm already in the process of upgrading (it's a company product, not my own)). I've reinstalled Tinkerwell `2.19.0` again and it's all working fine and as expected. I'd be fine with it "being my fault" as such, if it wasn't that it worked previously with all versions before `2.20.0` 🙂

**Comment by sschlein** [comment]
Hmm – PHP 7.3 could be the issue. We'll check that but if this is the reason, we might not be able to support that with new versions and this project can only use an older Tinkerwell version. We haven't touched the SSH parts or other internals for a while but have changed things to remove PHP 7.4 deprecation warnings

I'll keep you posted.

**Comment by digiservnet** [comment]
Thanks Sebastian. If it is a case that >=`2.20.0` has newer requirements (which in essence is understandable as that's how evolvement works) I can continue to use 2.19.0 for now on all projects until I'm able to migrate this work project to something newer. Only thing I'd add to that though that _if_ this is the case, wouldn't that have warranted a major version release due to a "breaking change"?

Interesting to know though if there were underlying changes in (probably) PHP version requirements.

**Comment by sschlein** [comment]
Tbh, we don't have a major version schedule yet and it's often hard to say if it is a breaking change or not until it breaks in a scenario that we haven't tested 🙈

We're currently working on ways to automate this process and find ways to run automated tests for all kinds of setups, but the PHP ecosystem is so spread out on devices, php versions, development environments that it's hard to solve that.

I am closing this issue for now and fix the release notes to mention that 2.21 drops PHP 7.3 support

**Comment by sschlein** [comment]
https://beyondco.de/docs/tinkerwell/releases/2-21-0#breaking-changes
