### ISSUE TITLE
[Bug]: Cannot install sublime text package

### ISSUE THREAD

**Issue by loranger** [beyondcode/tinkerwell-community#556]
### Operating system

macOS Monterey 12.2.1

### Laravel Version

v9

### PHP Version

PHP 8.1.3 (cli) (built: Feb 18 2022 09:12:41) (NTS)

### Project Location

Local

### Bug description

I try to install tinkerwell IDE extension, but it fails to install

### Steps to reproduce

- Launch Sublime Text (Stable build 4126)
- Trigger Package Control (cmd + maj + p)
- Select Install package action
- Type tinker in order to show TinkerWell package
- Tpye enter to install

### Relevant log output

```shell
Sublime text show a popup saying `Unable to download Tinkerwell. Please view the console for more details.`

The console displays a error regarding certificate :


Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host tinkerwell.app returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:548))) downloading https://tinkerwell.app/download/sublime/Tinkerwell.sublime-package.
error: Package Control

Unable to download Tinkerwell. Please view the console for more details.
```
```

**Comment by loranger** [comment]
Here is a screenshot of the issue:

<img width="1215" alt="Capture d’écran 2022-02-19 à 13 07 32" src="https://user-images.githubusercontent.com/6014/154800257-9c48d4f0-567d-4bab-b88f-a52b5b51ae95.png">

**Comment by sschlein** [comment]
Hey, the sublime text extension is deprecated and unmaintained. See https://beyondco.de/docs/tinkerwell/basic-usage/ide-plugins
