### ISSUE TITLE
[Bug]: PHP 8.1. issues

### ISSUE THREAD

**Issue by edalzell** [beyondcode/tinkerwell-community#566]
### Operating system

macOS Monterey 12.2.1

### Laravel Version

v8.83.4

### PHP Version

8.1.3

### Project Location

Local

### Bug description

If you run Ray, you see this when Tinkerwell starts up:

<img width="1234" alt="CleanShot 2022-03-10 at 15 20 14@2x" src="https://user-images.githubusercontent.com/6069653/157771958-977ec122-9526-4c8d-85fd-76390acf0888.png">

### Steps to reproduce

Open Ray, then open Tinkerwell

**Comment by mpociot** [comment]
This will be fixed in Tinkerwell 3.0
