### ISSUE TITLE
[Bug]: Run With Tinkerwell not working on PhpStorm 2022.1

### ISSUE THREAD

**Issue by ralphjsmit** [beyondcode/tinkerwell-community#571]
### Operating system

macOS Monterey 12.3

### Laravel Version

9.8.1

### PHP Version

PHP 8.1.4 (cli) (built: Mar 18 2022 09:32:37) (NTS) Copyright (c) The PHP Group Zend Engine v4.1.4, Copyright (c) Zend Technologies     with Zend OPcache v8.1.4, Copyright (c), by Zend Technologies

### Project Location

Local

### Bug description

This week I updated my PhpStorm installation to the new update, version 2022.1. Before that, I was on version 2021.3.3.

Yesterday I noticed that my usual shortcut for Run with Tinkerwell wasn't working. Today this happened again, so I thought that it was a missing keybinding or sth. That wasn't the case: manually triggering a run with the right-click menu also didn't work.

Tinkerwell has always worked great (the PhpStorm plugin is the only reason I'm renewing my license :)), so I installed the previous version again (2021 version), where it did work. 

Could you try to take a look at this and fix it (as soon as possible)? 

Thanks a lot!

### Steps to reproduce

Install the PhpStorm 2022.1 version and try to run Tinkerwell from a scratch file. 

### Relevant log output

```shell
There's not logging or error whatsoever.
```

**Comment by squatto** [comment]
When you run the "Run with Tinkerwell" command, nothing appears to happen. Interestingly, however, when you run the "Inspect with Tinkerwell" command, your code is executed and you get the inspection output. Your code is also executed if you run the "Show Table with Tinkerwell" command. You don't get the output in a Tinkerwell tool window with any of the commands though.

You can see in Ray on the right that "Run with Tinkerwell" doesn't do anything, but "Inspect with Tinkerwell" does:

![Tinkerwell bug in PhpStorm 2022 1](https://user-images.githubusercontent.com/748444/164110891-d60b0b4d-0b30-476d-b9cf-68ca4532a2b3.gif)

**Comment by sschlein** [comment]
The right click menu is also disabled.

<img width="413" alt="CleanShot 2022-04-20 at 10 44 00@2x" src="https://user-images.githubusercontent.com/2911113/164188561-2f5bb855-9481-4355-b85b-712a7eb59bb5.png">

**Comment by ralphjsmit** [comment]
@sschlein Can you give an indication when your team will be able to look at this? It's very frustrating not to be able to use this properly. When downgrading you also need to configure plugins and settings again.. :(

**Comment by sschlein** [comment]
We've been busy with Laracon EU this week and it's still travel-back day today. So I hope we can check this later this week or early next week.

**Comment by CarlJohnson1296** [comment]
Plugin has been updated, issue has been fixed? I had the same issue on windows. It works fine for me now with PhpStorm 2022.1 and plugin version 2.1

**Comment by mpociot** [comment]
Yup, version 2.1 fixes PHPStorm 2022.1 compatibility

**Comment by ralphjsmit** [comment]
Awesome, thanks a lot!
