### ISSUE TITLE
[Bug]: Vapor Environments Not Appearing

### ISSUE THREAD

**Issue by gilbitron** [beyondcode/tinkerwell-community#573]
### Operating system

macOS Monterey 12.3.1

### Laravel Version

v9.9.0

### PHP Version

PHP 8.1

### Project Location

Remote (Docker)

### Bug description

This is the same error that was reported in #549 (that issue was closed but the problem still persists for me). When enabling Vapor the environment dropdown is blank and can't be selected. Running code does work but is always run in the first environment (production for me).

**Comment by mpryfogleDS** [comment]
I'm able to work around this by pointing the PHP CLI on Tinkerwell to PHP 7.4, it doesn't seem to play well with 8.1

**Comment by gilbitron** [comment]
I've just upgraded to v2.29.0 and it seems to be working again.

**Comment by mpryfogleDS** [comment]
I'm on 2.29.0 and still experiencing the problem.

**Comment by mechelon** [comment]
This problem is related to the used PHP version (8.0 should work) and will be fixed in the upcoming 3.0
