### ISSUE TITLE
Configure tinkerwell to watch custom text file?

### ISSUE THREAD

**Issue by jesseleite** [beyondcode/tinkerwell-community#60]
As a terminal Vim user with an established vimrc full of mappings, plugins, etc., I'm wondering if there'd be some way to have tinkerwell watch and run on a configurable text file?

I'm imagining I could set a preference to watch `~/tinkerwell.php` (for example).  If a custom path is set, a watcher button would appear in the left sidebar/menu.  Enabling the watcher would also collapse the left-hand editor panel.  This would free us up to use any external editor, with our preferred key mappings, plugins, etc., yet still be able to see live output in the Tinkerwell window.

Thoughts?

**Comment by jesseleite** [comment]
[And if you end up implementing JS support](https://twitter.com/marcelpociot/status/1207699838747455488?s=20), could also have a second preference for custom `~/tinkerwell.js` path 😬

**Comment by sschlein** [comment]
Solved with the driver feature: https://github.com/tinkerwellapp/drivers :)

**Comment by sschlein** [comment]
Re-read your post and it's something different :D

**Comment by jesseleite** [comment]
Yessir, quite different!  Every time I'm in Tinkerwell, I miss my Vim key bindings, snippets, code intelligence, etc.  I think it'd be rad to edit a configurable tinkerwell file in my editor environment of choice, and have the tinkerwell window watch for external changes to that file, acting just as a preview/output window.

**Comment by mpociot** [comment]
Watching files is already added in the current version of Tinkerwell.
