### ISSUE TITLE
Add Connect to SSH through password instead of key (windows)

### ISSUE THREAD

**Issue by tiagosimoesdev** [beyondcode/tinkerwell-community#75]
unfortunately there are some cases it's the only option.

**Comment by wwwroth** [comment]
+1

I just purchased Tinkerwell and I'm trying to connect to an Azure App Service container through Azure's CLI `az webapp create-remote-connection`. It creates a virtual tunnel via Docker with a password (no key).

**Comment by wwwroth** [comment]
@mpociot does this mean we shouldn't expect password authentication in the roadmap?

**Comment by sschlein** [comment]
Nope, it has been released with the latest update :)

The issue was closed automatically by a pull request in a different repository. That's hidden from github if you don't have access to this internal repo.
